### ISSUE TITLE
Mapping Marathon Runners [Project]

### ISSUE THREAD

**Issue by maijaliisa** [jsoma/data-studio-projects#10]
Please complete all of the following sections, or a robot will spookily dance around your issue! A completed version of this template can be found at https://github.com/jsoma/data-studio-projects/issues/1

# Pitch:

## Summary

Recent attempts by Nike to 'perfect' the marathon put attention on the great feat of long-distance running. While elite marathon runners are considered some of the best athletes in the world, recreational marathon running has grown exponentially in the past decade (with well over half a million finishers in the United States last year).
The biggest marathons in the US - Boston, Chicago and LA, bring runners from around the world to compete for prize money or just the chance to run on historic routes. For the project, I want to explore where runners with the US come from...and how far are they willing to travel to compete in some of the most well-known races.

## Details
Inspiration!: https://medium.com/running-with-data/the-runners-of-the-boston-marathon-2017-56d2db7326c1 

**Possible headline(s):** 
In the biggest US marathons, runners travel XXX miles to compete
Traveling for races becomes a new part of running culture

**Data set(s):** 
https://www.trackshackresults.com/lamarathon/results/2017/mar_results.php?Link=9&Type=2&Div=W&Ind=21 
https://www.kaggle.com/rojour/boston-results 

**Code repository:** 
https://github.com/maijaliisa/studio-projects/tree/master/code/marathon 
	
**Possible problems/fears/questions:** 
It look me a while to figure out how to get all of the data...because most results databases are set up so that you have to search per bib number/name (and doesn't easily give you a full list) 

## Checklist

This checklist must be completed before you submit your draft.

- [x] I have already spent time with my data set, opening it, exploring it, etc
- [x] I have created a "DIARY.md" file to save links and list all of the terrible, no good problems I come across
- [x] My issue issue has `[Project]` in the title
- [x] My issue links to my data set(s)
- [x] My issue links to my code repository
- [x] My issue explains what I'd like to explore in the data set
- [x] My issue includes images - either inspiration or what I've done so far
- [x] I have received two comments of peer feedback on my pitch issue

**Comment by wonderfulexperience** [comment]
I like to see where are the best runners coming from? A title like: "Here are the fastest Americans are coming from" would be intriguing.

**Comment by deniseajiri83** [comment]
I liked the idea a lot! It would be great to see some comparisons, for example "where are most of the runners coming from, comparing men and women, what's the average age,...".

**Comment by SYChJung** [comment]
So you can make a map the regions with best runners and might be able to map out their running cultures and something.

**Comment by maijaliisa** [comment]
# Update

## Content

![screen shot 2017-07-21 at 8 56 43 am](https://user-images.githubusercontent.com/28814389/28464321-9cfd9522-6df2-11e7-96ba-074343b22cf9.png)

I am having trouble determining what the actual 'story' would be! I have a lot of information, but the problem is that it isn't that same across all 6 datasets. I've found a very rough outline of 'out of state runners' but the correlation isn't all that interesting. 
    	
## Any changes in direction or topic?

I do want to find a way to correlate State of Origin for the runners with their Total Time (finding what is the 'fastest city' in a marathon. 

## Problems/Questions

I am not sure this is a particularly interesting story...

## Checklist
    	
- [X] I have included my visuals
- [X] I have added writing about my topic
- [X] I have been updating my DIARY.md with details about my process
- [X] I have uploaded/updated any Jupyter Notebooks or other datasets into my code repository
- [ ] I have received two comments of peer feedback on my project update

**Comment by wonderfulexperience** [comment]
I think it is interesting! Personally I would like to know why some states have a much higher number of runners per capita. Do they have famous runners? Or are these countries with a specific population which is more attracted to running?

**Comment by SYChJung** [comment]
I also think that may be you should make a graph about the marathon winners in each state.

**Comment by qdinhbui2** [comment]
Depending on how much data you can scrape, you could ask yourself where the future of marathon running would likely be. Looking at the youngest marathon runners and finding out where they're from.

**Comment by sarahslo** [comment]
What if you did map the distance each runner traveled to get to the state, and did this for just the one state that has the most out of state runners? Instead of going wide on the entire dataset, go deep on just a piece of it.

Chris Canipe at Axios recently made this trade map https://www.axios.com/the-flow-of-goods-2463665414.html 
<img width="726" alt="screen shot 2017-08-09 at 21 15 55" src="https://user-images.githubusercontent.com/659014/29150354-ff8ea726-7d47-11e7-9c6c-46d572e15aa8.png">
that shows the flow of goods. What if you looked at one state and then saw where the most runners came from. Let's say you look at Texas and for 1 marathon 100 runners come from out of state, but a whopping 45 of them come from N. Carolina. You could then reverse engineer this and look at where the N. Carolina runners go. Or if you did the math to figure this out overall, you could then do, which state has the most runners who GO to marathons instead of which state has the most runners who travel to get there.

Anyway, I'd be curious to see which states have the youngest runners too. And the oldest. Look for the superlatives, A to Z, Z to A. 

Nice start!
