### ISSUE TITLE
Greek PM sentiment analysis before and after signing the MoU with EU[Project]

### ISSUE THREAD

**Issue by chrgavalas** [jsoma/data-studio-projects#100]
Please complete all of the following sections, or a robot will spookily dance around your issue! A completed version of this template can be found at https://github.com/jsoma/data-studio-projects/issues/1

# Pitch
In 2015, Syriza, the greek leftist party and Alexis Tsipras, the leader of the opposition in parliament won the snap elections on the premise of re-negotiating terms of an already signed MoU between indebted Greece and its European creditors that would help the country stay afloat, even of totally cancelling it. His enraged speeches in parliament didn't change much after he became PM. But what happened in his wording after he was forced by Europe to concede defeat and sign a cursed agreement that included most if not all of the measures he once promised to reject?  

## Summary
Through the examination of Mr Tsipras' speeches in parliament we want to define to scope of change he had to undertake after his government was defeated in the negotiations with its European counterparts. We will be using equal number of speeches before the signing (July 13, 2015) and after it, timely ranging from 2013 to 2017. 

## Details
There are certain words Mr Tsipras had been using quite often before coming to power. Has he been using them since and how often? We will also try to draw conclusions from a more generic sentiment analysis based on the Emolex's greek version, measuring the level of positivity and/or negativity of his speeches over time.  

**Possible headline(s):** 
Sentiment Analysis: How the signing of the MoU cooled Tsipras' speeches off 

**Data set(s):** 
http://www.hellenicparliament.gr/
**Code repository:** 
https://github.com/chrgavalas/data-projects/tree/master/code/project7
**Possible problems/fears/questions:** 
The greek version of Emolex doesn't seem to be doing a good job in nailing down the clear emotional difference in the PM speeches prior and after the MoU. So I'll need to find the correct use of it that will make sense to present and support my argumentation. 
## Work so far
Downloaded almost 25 parliamentary speeches of Mr Tsipras and created txt files. Requested the greek version of Emolex. Have done some preliminary analysis, play around with words and try to find the right combination to show the change. Finally, have also done some initial graphs.  
## Checklist

This checklist must be completed before you submit your draft.

- [x] I have already spent time with my data set, opening it, exploring it, etc
- [x] I have created a "DIARY.md" file to save links and list all of the terrible, no good problems I come across
- [x] My issue issue has `[Project]` in the title
- [x] My issue links to my data set(s)
- [x] My issue links to my code repository
- [x] My issue explains what I'd like to explore in the data set
- [x] My issue includes images - either inspiration or what I've done so far
- [ ] I have received two comments of peer feedback on my pitch issue

**Comment by demetriospogkas** [comment]
People coming from Greece can understand how greatly relevant this analysis is to the current political and public discourse.

**Comment by chrgavalas** [comment]
# Update
	
## Content
In 2015, Syriza, the greek leftist party and Alexis Tsipras, the leader of the opposition in parliament won the snap elections on the premise of re-negotiating terms of an already signed MoU between indebted Greece and its European creditors that would help the country stay afloat, even of totally cancelling it.
But after six months of dramatic negotiations, he was forced by Europe to concede defeat and sign a cursed agreement that included most if not all of the measures he once promised to reject.
By using sentiment analysis tools in Python we concluded that the Greek PM gave **his most emotionally loaded speeches in the parliament** right at the time when the crisis peaked: July 2015. Both the negativity and positivity of his speeches reached their maximum level, which might seem like contradicting but ensures the speeches were full of emotional words. 

![download-5](https://user-images.githubusercontent.com/30135399/29428239-7961fcac-835a-11e7-92b2-9b7ffe093c9a.png)

![download-7](https://user-images.githubusercontent.com/30135399/29428244-7cfff242-835a-11e7-8ce5-17641ec71e8b.png)

Also, our analysis shows that Mr Tsipras had been **using the word "memorandum"** far more times before he was forced to sign it to keep Greece in Europe than after he did so. The assumption is he was more adamant in its use as a tool of mobilizing the base of his party's supporter when he was leader of the opposition and in the first few months of his presidency when he was still technically opposing most of the proposed measures on the negotiating table. But once his role became much more presidential and had to implement these measures, his tone changed and the use of the word 'memorandum' lost ground in his speeches.  

![download-4](https://user-images.githubusercontent.com/30135399/29428212-667921c4-835a-11e7-91d7-365e7c91b601.png)

## Any changes in direction or topic?
Yes indeed the headline will be based on the conclusion that Mr Tsipras speeches around the time he signed the memorandum were both negatively AND positively in their peak, thus collectively in their emotional peak. It will be like a scientific proof of how much polarized the political environment was at this very time. 
	
## Problems/Questions
The Emotional Lexicon didn't reach the levels of accuracy I was hoping in order to draw deeper and safer conclusions on the variations of Mr Tsipras speeches in parliament. So that will make me very careful in how I present my conclusion, especially if that was a publishable type of story. 	

## Checklist
	
- [x] I have included my visuals
- [x] I have added writing about my topic
- [x] I have been updating my DIARY.md with details about my process
- [x] I have uploaded/updated any Jupyter Notebooks or other datasets into my code repository
- [ ] I have received two comments of peer feedback on my project update

**Comment by chrgavalas** [comment]
# Final

## Project visuals/text

<img width="1066" alt="tsipras-pic" src="https://user-images.githubusercontent.com/30135399/29575635-1ec9eba6-8733-11e7-8f37-61a98577be49.png">

In early 2015, Syriza, the greek leftist party until then in opposition, came to power promising to confront the 'troika' of Greece’s creditors and terminate austerity under which people were suffering. However, six months of high-drama negotiations -followed by a national referendum- later, **Alexis Tsipras**, the party's president and elected Greek PM, signed a third memorandum lumbering on implementing **anti-left measures** of historic magnitude. 

But how much of this unprecedented capitulation was reflected in his speeches in parliament? Did the sentiment of his speeches change as the country was getting closer to a possible EU exit? And how much of this sentiment was actually based on the sentiment of his own words?   

Through the **sentiment analysis** of most of the key speeches he gave in parliament before and after the signing of the third MoU, we get a clearer picture of his **feelings’ variation** and *tend to conclude* that his monumental double back was connected with much more heavy - loaded addresses.   

For our analysis we used the **Emotional Lexicon** that includes all kind of words and defines whether they determine anger, anticipation, disagreement etc. or more generally whether they have a negative or positive inclination. 

Each word of the lexicon is assigned a number (0 or 1) based on whether it represents a given sentiment (0=False, 1=True). 

The **TdifVectorizer** will help us define the level of positivity/negativity by giving us back a percentage of usage of words with positive/negative aspect within a speech, whereas through the **CountVectorizer** will bring us in a position to look into how many times a specific set of words appears in each speech.

We grouped our sample of 25 Mr Tsipras’ speeches in parliament by month - year and marked the **July 2015** date time as the defining moment of this analysis, as this was the time when he agreed to terms with the European creditors. 

<img width="1200" alt="positivity" src="https://user-images.githubusercontent.com/30135399/29575611-096da522-8733-11e7-8084-82bce0772177.png">

<img width="1200" alt="negativity" src="https://user-images.githubusercontent.com/30135399/29575617-0e7704be-8733-11e7-88a6-d53d2017127b.png">

More specifically, we examined the level of negativity and positivity of his speeches over time by adding up each negative and positive used word’s percentages in each speaking which resulted into a decimal number. 

For both cases we came up with the same finding: on that month the sentiment of this wording spiked. 

*"It’s a crucial moment and I’d ask you to allow me to use a personal tone in today’s intervention. Since the first moment I became prime minister, maybe during the most crucial days in the country’s post-constitutionalism era, I acted based only on my conscience so as to stand up for our people’s justice with all my forces but to also protect our national interests"*, he said on July 10 before the parliament in his initial remarks, preparing the ground for a clearly **emotional speech** just a few hours before going to Brussels for the decisive session with the EU creditors.   

In the years and months preceding the date of the MoU signing in Brussels in a dramatic night long session, Mr Tsipras seems to have been very adamant in using the word **‘memorandum’** in his parliamentary speeches to directly criticize the previous government and to hold out to his partisan voters. 

But right after he accepted to initiate a third bailout program with the EU creditors, he radically **changed the course of his discourse**, and ceased using the word almost entirely, with the exception of last May’s speech before the parliament. 

<img width="1200" alt="memorandum" src="https://user-images.githubusercontent.com/30135399/29575596-fb7752e2-8732-11e7-9c57-06afa8e7ad32.png">

Referring to the voting of yet another tough set of measures that would serve in finalizing the second review, which would lead to another disbursement, the Prime Minister, **utilized the word in his rhetorics more than ever**, creating thus a notable outlier. 

This trend is presented clearly in the data. In the period prior to the MoU signing he had used the word 76 times, whereas in the period right after, the use was significantly decreased to only 9 times in the course of 22 months, with the exception of his May speech.

This clearly shows the **fluidity of rhetorics** and discourse in greek politics. Greece appears to be one of the only highly developed states which demonstrates such *radical changes in policy positioning*. 

This is only exasperated by the duality of PM Tsipras’ rhetoric abroad: from the one hand the PM seems to be completely in agreement with the european side after signing the third MoU, however in the domestic scene, the PM still maintains fiery anti-austerity rhetorics for internal consumption purposes. 

Perhaps this explains very well the case of **our May 2017 outlier speech** as it was an attempt to justify his choices domestically blaming the conservative opposition party -which has a dominant lead in the current polls- of being the instigator of the austerity brought by the MoU in the first place. 

## Details

**Headline:** 
When Greek PM doubled back on MoU, his words spoke volumes

**Published website version:**
https://chrgavalas.github.io/data-projects/Tsipras-Sentiment-Analysis/

**Code repository:**
https://github.com/chrgavalas/data-projects/tree/master/code/project7

**Final data set(s):** 
http://www.hellenicparliament.gr/
http://sentiment.nrc.ca/lexicons/

## What did you find to be the most difficult part of this project?
Trying to figure out if there's actually a real story to report. The Emotional Lexicon in Greek wasn't so accurate but as a journalist I couldn't just rush to conclude what I had been aspiring to in the beginning. I ended up working with an outlier that couldn't even imagine finding and which honestly don't seem the most interesting finding. 

## Are you satisfied with what you produced? Is there anything you would like to change or improve?
I guess I would improve my lexicon and I would have tried to include many more speeches of the PM probably not just the ones he gave in parliament so as to improve my sample. 

## Checklist

- [x] I have included my visuals
- [x] I have posted my project to my project website
- [x] I have been updating my DIARY.md with details about my process
- [x] I have uploaded/updated any Jupyter Notebooks or other datasets into my code repository
