### ISSUE TITLE
Twitterbot for party donations [Project]

### ISSUE THREAD

**Issue by marcelpauly** [jsoma/data-studio-projects#101]
# Pitch

## Summary

For once a project without a visual: a few weeks ago I launched a [Twitterbot](https://twitter.com/grossspenden) that scrapes the German parliament's website [where party donations larger than €50,000 are published](https://www.bundestag.de/parlament/praesidium/parteienfinanzierung/fundstellen50000/2017/2017-inhalt/488236). Unfortunately the website is completely managed by hand and they make mistakes. A lot of mistakes. Some of them drive my scraper completely crazy and that drove the bot's followers crazy. That's why I want to spend time on make the script bulletproof.

## Details

**Possible headline(s):** Twitterbot for party donations 2.0

**Data set(s):** https://www.bundestag.de/parlament/praesidium/parteienfinanzierung/fundstellen50000/2017/2017-inhalt/488236

**Code repository:** https://github.com/marcelpauly/parteispenden (going to translate it very soon)
	
**Possible problems/fears/questions:** to anticipate all possible mistakes they could make

## Work so far

The scraper works - if the websites content is like it is supposed to be.

## Checklist

This checklist must be completed before you submit your draft.

- [x] I have already spent time with my data set, opening it, exploring it, etc
- [ ] I have created a "DIARY.md" file to save links and list all of the terrible, no good problems I come across
- [x] My issue issue has `[Project]` in the title
- [x] My issue links to my data set(s)
- [x] My issue links to my code repository
- [x] My issue explains what I'd like to explore in the data set
- [ ] My issue includes images - either inspiration or what I've done so far
- [ ] I have received two comments of peer feedback on my pitch issue

**Comment by demetriospogkas** [comment]
Congrats for amazing work during Lede @marcelpauly, keep it up!!

**Comment by marcelpauly** [comment]
I'm very flattered, thank you very much @demetriospogkas!
