### ISSUE TITLE
All the Presidents' Cabinets [Projects]

### ISSUE THREAD

**Issue by maijaliisa** [jsoma/data-studio-projects#102]
Please complete all of the following sections, or a robot will spookily dance around your issue! A completed version of this template can be found at https://github.com/jsoma/data-studio-projects/issues/1

# Pitch

I'm looking to visualize/explore the people who have made up each Presidents' cabinet over the years.

## Summary

We hear a lot about the Cabinet members that Presidents have around them, but we rarely look at the change of cabinets over time. I have created a dataframe with each cabinet member since 1781 (including those acting/sworn in). I will create a timeline to show how the cabinet changes over time, including some necessary historical facts to put it into context. I will also create several charts and graphs that show the number of states represented and the gender breakdown. These visuals will be a way of going in and exploring the data of US Presidents' cabinets more fully. 

## Details

**Possible headline(s):** 
"All the Presidents' Cabinets 

**Data set(s):** 
https://docs.google.com/spreadsheets/u/1/d/1NzRh82NJjuUjCdwUkLoBQ8whB7YPhWlwXDDB7r3DxCM/edit?usp=drive_web
Created with data from WhiteHouse.gov and Wikipedia pages on each Department 

**Code repository:** 
https://github.com/maijaliisa/studio-projects/tree/master/code/AllThePresidentsCabinets 
	
**Possible problems/fears/questions:** 
-It's not so much a reporting story as a feature about Presidential Cabinets/a sort of explainer for those who might not really think about these positions on a regular basis. 
-I'm not sure if I should include acting cabinet members (those not sworn in by Congress but still in the interim role) 

## Work so far

I created the dataframe and cleaned the information into the columns I need. I also created an additional column that groups states by Region. I've done the first draft of the Illustrator 'timeline'
## Checklist

This checklist must be completed before you submit your draft.

- [X] I have already spent time with my data set, opening it, exploring it, etc
- [X] I have created a "DIARY.md" file to save links and list all of the terrible, no good problems I come across
- [X] My issue issue has `[Project]` in the title
- [X] My issue links to my data set(s)
- [X] My issue links to my code repository
- [X] My issue explains what I'd like to explore in the data set
- [ ] My issue includes images - either inspiration or what I've done so far
- [ ] I have received two comments of peer feedback on my pitch issue

**Comment by IoannisAntypas** [comment]
Excellent idea! Maybe go for diverse colorings and/or shapes of your points based on gender, race, age group etc

**Comment by maijaliisa** [comment]
# Update
	I created a full visual timeline of changes in cabinet positions in Illustrator (included below)...but it doesn't actually showcase anything particularly interesting (other than a recap of history). So I am now going back and restructuring the dataframe so I can see what president had the most cabinet members...and when I see a discrepancy I will explore that for story 
## Content
	
## Any changes in direction or topic?
Not really...just honing in on more specifics 
	
## Problems/Questions
I think the timeline I created is cool but not really for a journalistic project. I'm hoping I can use it somewhere else! 	
## Checklist
	
- [X] I have included my visuals
- [X] I have added writing about my topic
- [X] I have been updating my DIARY.md with details about my process
- [X] I have uploaded/updated any Jupyter Notebooks or other datasets into my code repository
- [ ] I have received two comments of peer feedback on my project update
![cabinet copy copy](https://user-images.githubusercontent.com/28814389/29337600-d7c6931a-81df-11e7-998d-2ecb319a04f0.png)

**Comment by maijaliisa** [comment]
Final

## Project visuals/text
https://maijaliisa.github.io/studio-projects/a-very-cool-project/GitHubPresCabinet/
## Details

**Headline:** 
Cleaning a Presidential Cabinet 
**Published website version:**

**Code repository:**
https://maijaliisa.github.io/studio-projects/a-very-cool-project/GitHubPresCabinet/
**Final data set(s):** 
-included in GitHub...but scraped/taken from Wikipedia and WhiteHouse.gov 

## What did you find to be the most difficult part of this project?
-Determining the scope...there is a lot of data and a lot of ways to go with it. 
## Are you satisfied with what you produced? Is there anything you would like to change or improve?
-I wish I made more clear the difference between acting and sworn in and why that is important. But I also wish I included a little bit about rejected cabinet/withdrawn cabinet nominations 

## Checklist

- [X] I have included my visuals
- [X] I have posted my project to my project website
- [X] I have been updating my DIARY.md with details about my process
- [X] I have uploaded/updated any Jupyter Notebooks or other datasets into my code repository
