### ISSUE TITLE
Spying on an entire undergraduate dormitory [Project]

### ISSUE THREAD

**Issue by adaskalopoulou** [jsoma/data-studio-projects#104]
# Pitch

## Summary
In this project, I plan to analyze a mobile phone dataset put together by the MIT Human Dynamics Lab and includes the dynamics of 70 residents of an undergraduate dormitory.  This dataset contains surveys and sensor data about the diffusion of political opinions, diet, exercise, obesity, eating habits, epidemiological contagion, depression and stress, political issues through interpersonal relationships of these students. 

## Details

![screenshot 2017-08-07 09 30 18](https://user-images.githubusercontent.com/28814404/29028683-198e5b04-7b53-11e7-8ad2-675fe2be36d0.png)

**Possible headline(s):** 

**Data set(s):** 
https://github.com/adaskalopoulou/studio-projects/tree/master/code/project4/Datasets

**Code repository:** 
https://github.com/adaskalopoulou/studio-projects/tree/master/code/project4

**Possible problems/fears/questions:** 

## Work so far
I requested, received, opened and cleaned the csv files. 
I studied the datasets and I plan to look for the following relationships:
- body weight of subject compared to the changes of the body weight of his/her weekly contacts
- healthy diet of subject compared to the diet of his/her weekly contacts
- number of close friends and level of sadness
- music genre preference and stress levels
- music genre preference and level of sadness

It would be interesting also to look for a relationship between music genre preference, healthy diet, level of loneliness level of sadness, and his/her political opinions. 

## Checklist

This checklist must be completed before you submit your draft.

- [x] I have already spent time with my data set, opening it, exploring it, etc
- [x] I have created a "DIARY.md" file to save links and list all of the terrible, no good problems I come across
- [x] My issue issue has `[Project]` in the title
- [x] My issue links to my data set(s)
- [x] My issue links to my code repository
- [x] My issue explains what I'd like to explore in the data set
- [x] My issue includes images - either inspiration or what I've done so far
- [ ] I have received two comments of peer feedback on my pitch issue

**Comment by chrgavalas** [comment]
Mysteriously interesting topic Aspasia! Do you maybe want to also analyze how their field of study affects their levels of stress or anxiety as well as the number of close relationships they form in the dorm? Interested to see what the outcome will be!

**Comment by adaskalopoulou** [comment]
# Update
	
## Content

I explored the relationships between different characteristics of the students:
- Music genre preference & preferred political party
- Music genre preference & levels of sadness
- Music genre preference & levels of stress
- Total numbers of close friends & levels of sadness
- Total numbers of people with whom they socialize twice a week & levels of sadness
- Total numbers of Facebook friends & levels of sadness
- Total numbers of close friends & levels of stress
- Total numbers of people with whom they socialize twice a week & levels of stress
- Total numbers of Facebook friends & levels of stress
- Similarities in healthy diet between close friends
- Similarities in weight loss/gain between close friends

None of the above-listed relationships yielded any meaningful results. 

## Next steps

I will try to explore the differences between freshman, sophomore, junior and senior students in:
a) weight loss/gain, b) healthy diet, c) exercise.

## Any changes in direction or topic?
If this last attempt doesn't yield any results, I will just try to make this graph human-readable: 

![screenshot 2017-08-21 19 28 12](https://user-images.githubusercontent.com/28814404/29542123-e530fd12-86a6-11e7-9fa1-46eedb0a7ceb.png)

## Questions
Do you have any suggestions about how can I make this graph human-readable?

## Checklist
	
- [x] I have included my visuals
- [x] I have added writing about my topic
- [x] I have been updating my DIARY.md with details about my process
- [x] I have uploaded/updated any Jupyter Notebooks or other datasets into my code repository
- [ ] I have received two comments of peer feedback on my project update

**Comment by adaskalopoulou** [comment]
# Review

## Content
<img width="1366" alt="artboard" src="https://user-images.githubusercontent.com/28814404/29785787-dae617ac-8bf6-11e7-8cd6-ed6c24cf7972.png">

I plan to create a visualization that will reflect the habits and psychological condition of students in different stages of their studies. 

![whatsapp image 2017-08-25 at 10 06 45](https://user-images.githubusercontent.com/28814404/29785894-30f874c8-8bf7-11e7-9bc3-e97d2b035eba.jpeg)

## Problems/Questions
With my limited Illustrator skills, it will probably be challenging to create an appealing result. 
	
## Checklist
	
- [x] I have included my visuals
- [x] I have added writing about my topic
- [x] I have been updating my DIARY.md with details about my process
- [x] I have uploaded/updated any Jupyter Notebooks or other datasets into my code repository
- [ ] I have received two comments of peer feedback on my project update

**Comment by adaskalopoulou** [comment]
# Final

## Project visuals/text

## Details
As the beginning of the academic year approaches, what should students prepare for or be cautious about during the upcoming months? In this project I analysed data collected by MIT’s Human Dynamics Laboratory (http://hd.media.mit.edu/) which cover the dynamics of 70 residents of an undergraduate dormitory during the academic year 2008-2009. This dataset contains surveys and sensor data about the diffusion of political opinions, diet, exercise, obesity, eating habits, epidemiological contagion, depression and stress, among the students.

In this analysis I used data from self-reported surveys to investigate the diet habits, the frequency of exercise and the emotions of students during the four years of their studies. From a quick overview of the results freshmen play the most sports, sophomores gain the most weight, juniors are sad more often and seniors eat the least healthy food.

In detail

Freshmen reported that they consume on average three portions of fruits and vegetables every day and two salads every week. During the week they play sports twice and they do at least 20 minutes of aerobic exercise three times a week. In the course of the academic year they tend not to gain a lot of weight, just one kilogram on average. During the spring semester they reported being stressed 7 days, and sad 8 days.

<img width="750" alt="artboard_fresh" src="https://user-images.githubusercontent.com/28814404/29983934-09ca52c2-8f26-11e7-9295-f4b8479d2826.png">

Sophomores reported that they consume on average two portions of fruits and vegetables every day and just on salad per week. During the week they play sports only once and they do at least 20 minutes of aerobic exercise two times a week. In the course of the academic year they tend to gain a lot of weight, about 5 kilogram on average. During the spring semester they reported being stressed 8 days, and sad only 3 days.

<img width="750" alt="artboard_soph" src="https://user-images.githubusercontent.com/28814404/29983932-062ee308-8f26-11e7-87a6-b942720d104e.png">


Juniors reported that they consume on average two portions of fruits and vegetables every day and two salads per week. During the week they don’t play any sports and they do at least 20 minutes of aerobic exercise three times a week. In the course of the academic year they tend to gain about 2 kilograms in body weight. During the spring semester they reported being stressed 19 days, and sad 13 days.

<img width="750" alt="artboard_junior" src="https://user-images.githubusercontent.com/28814404/29983930-0172e940-8f26-11e7-9a08-0871ca5d8293.png">


Seniors reported that they consume on average one portion of fruits and vegetables every day and one salad per week. During the week they play sports once and they do at least 20 minutes of aerobic exercise three times a week. In the course of the academic year they tend to gain about 1 kilogram in body weight. During the spring semester they reported being stressed 18 days, and sad 10 days.

<img width="750" alt="artboard_seniors" src="https://user-images.githubusercontent.com/28814404/29983927-fbe6048a-8f25-11e7-931f-5b85f5944738.png">

Complete chart

<img width="750" alt="artboard_all" src="https://user-images.githubusercontent.com/28814404/29983956-2ac0c10a-8f26-11e7-9e84-30757dcc0b1c.png">

**Headline:** 
What seniors should learn from freshmen?

**Published website version:**
https://adaskalopoulou.github.io/studio-projects/project-4/

**Code repository:**
https://github.com/adaskalopoulou/studio-projects/tree/master/code/project4

**Final data set(s):** 
https://github.com/adaskalopoulou/studio-projects/tree/master/code/project4

## What did you find to be the most difficult part of this project?

## Are you satisfied with what you produced? Is there anything you would like to change or improve?

## Checklist

- [x] I have included my visuals
- [x] I have posted my project to my project website
- [x] I have been updating my DIARY.md with details about my process
- [x] I have uploaded/updated any Jupyter Notebooks or other datasets into my code repository
