### ISSUE TITLE
Where do city governments store their stuff?

### ISSUE THREAD

**Issue by kromreig** [jsoma/data-studio-projects#11]
Where is it? What is it? Is it in special buildings, or normal storage units?

# Project issue checklist

- [x] My pitch issue has `[Project]` in the title
- [x] My pitch issue has `[Data request]` in the title if I need additional data
- [x] My pitch issue links to my data set
- [ ] My pitch issue links to my data studio repository
- [ ] My pitch issue explains what I'd like to explore in the data set
- [ ] My pitch issue includes multiple possible headlines or plan Bs
- [ ] My pitch issue includes any links/images I'm using as inspiration
- [ ] I have received two comments of peer feedback on my pitch issue

**Comment by jsoma** [comment]
Hi there, I'm the Playfair Bot!

Would you mind **adding a category to your issue title?** It should probably be [Project], or maybe [Meta] if it happens to be a bug. That way we can organize things nice and neat.

Thanks! :pray:

**Comment by jsoma** [comment]
Hi there, I'm the Playfair Bot!

Would you mind **posting the appropriate checklist** in the main body of your issue? You might have posted it as the first comment, but it turns out it works *way better* in the actual body of the issue - just go up to the veeery top right and click the **pencil icon** to edit. You'll probably want to edit the comment to copy the checklist, then edit the original issue to paste it in.

Thanks! :pray:

**Comment by jsoma** [comment]
Hi there, I'm the Playfair Bot!

Thanks for posting your project issue, but would you mind adding editing the issue to **add a draft or inspirational image?** You have my sincere apologies, but it's easier for dumb robots like me when the comments are only used for updates.

Thanks! :pray:

**Comment by jsoma** [comment]
Hi there, I'm the Playfair Bot!

Would you mind **linking to your project repository** ? It'll hopefully help us keep things neat and organized.

Thanks a zillion! :pray:

**Comment by kromreig** [comment]
# Project issue checklist

- [ ] My pitch issue has `[Project]` in the title
- [ ] My pitch issue has `[Data request]` in the title if I need additional data
- [ ] My pitch issue links to my data set
- [ ] My pitch issue links to my data studio repository
- [ ] My pitch issue explains what I'd like to explore in the data set
- [ ] My pitch issue includes multiple possible headlines or plan Bs
- [ ] My pitch issue includes any links/images I'm using as inspiration
- [ ] I have received two comments of peer feedback on my pitch issue
