### ISSUE TITLE
Visualization of the hidden art in federal buildings. [Project]

### ISSUE THREAD

**Issue by mathieulede** [jsoma/data-studio-projects#12]
# Pitch
Give an idea of the size of the hidden art in federal buildings.

## Summary
> The Fine Arts Collection is one of the nation's oldest and largest public art collections. It consists of mural and easel paintings, sculptures, architectural and environmental artworks, as well as prints and other works on paper dating from the 1850s to the present. These civic artworks are displayed in federal buildings and courthouses nationwide.

I want to focus on basic perceptions: size of the average piece of art, surface occupied by all the frames. I want to give an idea of the actual number of pieces of arts by showing them all in one place, compare this number for each city and give information about the appraisal of all this collection.

## Details
The Fine Arts Database records information on federally owned art in the control of the GSA (General Services Administration); this includes the location, current condition and information on artists.

[The Federal Art Project](http://depts.washington.edu/depress/FAP.shtml)  
[About the Collection](https://gsa.gov/fa/#/about-the-collection)

**Possible headline(s):** 
1. Everydays museums, who owns the civic art?  
2. The hidden art of the everydays buildings  
3. 1 million m2 of art that nobody see

**Data set(s):** 
[Link to the data set](https://catalog.data.gov/dataset/fine-arts-database-fad)

**Code repository:** 
[https://github.com/mathieulede/data-studio/tree/master/code/project1](https://github.com/mathieulede/data-studio/tree/master/code/project1)

**Possible problems/fears/questions:** 
Visualization of a great (more than a million) number of items.

## Sketches/inspiration
![](https://github.com/mathieulede/data-studio/blob/master/code/project1/moodboard/Screen%20Shot%202017-07-16%20at%209.39.37%20PM.png?raw=true)
[FiveThirtyEight - Gun deaths in America](https://fivethirtyeight.com/features/gun-deaths/)

![](https://github.com/mathieulede/data-studio/blob/master/code/project1/moodboard/Screen%20Shot%202017-07-16%20at%209.40.39%20PM.png?raw=true)
[Power of ten](https://www.youtube.com/watch?v=0fKBhvDjuy0?raw=true)

## Work so far
Histogram of the art acquisition by year, appraisal value, cleaning

## Checklist

This checklist must be completed before you submit your draft.

- [x] I have already spent time with my data set, opening it, exploring it, etc
- [x] I have created a "DIARY.md" file to save links and list all of the terrible, no good problems I come across
- [x] My issue issue has `[Project]` in the title
- [x] My issue links to my data set(s)
- [x] My issue links to my code repository
- [x] My issue explains what I'd like to explore in the data set
- [x] My issue includes images - either inspiration or what I've done so far
- [x] I have received two comments of peer feedback on my pitch issue

**Comment by hichenwang** [comment]
After analyzing all the cities, I would like to focus on some cities that surprise me...

And I will consider using mapping, just easier for people to relate to. maybe just static ones are enough.

**Comment by mathieulede** [comment]
# Update

## Content
![](https://github.com/mathieulede/data-studio/blob/master/code/project1/viz-A.png?raw=true)

![](https://github.com/mathieulede/data-studio/blob/master/code/project1/viz-B.png?raw=true)

![](https://github.com/mathieulede/data-studio/blob/master/code/project1/viz-C.png?raw=true)

## Any changes in direction or topic?
My first idea was to give a sense of the size/scale of all this collection hidden away from the public. The number of pieces of art in the datasets was about 16 million... but after having cleaned the dataset by removing the duplicates, this number dropped to 16,000.

I added a list of famous artists that are displayed in bureaucratic buildings.

## Problems/Questions
I would like to focus on the first visualization by adding more information: sort by date, show the type of art, the dimensions of each painting, etc. to crate a kind of virtual museum of the hidden art. But not sure whether it worth it or not.

## Checklist
    
- [x] I have included my visuals
- [x] I have added writing about my topic
- [x] I have been updating my DIARY.md with details about my process
- [x] I have uploaded/updated any Jupyter Notebooks or other datasets into my code repository
- [x] I have received two comments of peer feedback on my project update

**Comment by hichenwang** [comment]
The charts are super cool and the messages are well conveyed! 
Something I would be interested in knowing more: 
* What is GSA? why they own so many art works? at least some short background info.  
* I would like to see the pics of some selected art works. 
* If I was from one of the cities, I would be very interested in knowing where should I go to find them. And I am also curious about why you highlighted 'The Town-Ho's Story'.

The virtual museum idea is super cool; however, as it is a journalistic work, I would argue that's an overkill. I would imagine people trying several clicks and moving on. I would prefer an interactive work with a focus on the top cities, which provides the readers something they can relate to.

**Comment by MarinaBraem** [comment]
Great idea and a strong subtile impact – great research and examples. I like most the headline "The hidden art of the everydays buildings". Makes me wondering and thinking about a topic I never did before! Would be interesting to see the diversity of the hidden art. Which kind of art is hidden?  Whats the surprise behind the closed doors?  A correlation between the hidden areas, the scales is great. Perhaps it would be nice to symbolize this metapher like "opening a door" and to let us exploring the strong diversity which nobody can see behind the everyday buildings.
