### ISSUE TITLE
Particulate matter alarm in Stuttgart, Germany [project]

### ISSUE THREAD

**Issue by ElisaHarlan** [jsoma/data-studio-projects#19]
Please complete all of the following sections, or a robot will spookily dance around your issue! A completed version of this template can be found at https://github.com/jsoma/data-studio-projects/issues/1

# Pitch

## Summary
Stuttgart is the dirtiest city in Germany. In case of particulate matter measurements, the city with a population of 600,000 inhabitants regularly hits the official limits introduced by the European Union. The reason: Stuttgart’s special topography with its elevation and valleys surrounded by forests and vineyards. Due to its location in a basin, certain weather conditions can lead to relatively little airflow in the inner city, producing conditions conducive to the build-up of air pollutants such as fine dust or nitrogen oxide. 
After years of discussion in the local council, the city administration introduced a so-called "fine-dust alarm" in 2016. On days with a high load, the city calls publicly on the radio and in newspapers on its citizens to take the bicycle or public transport instead of cars. This is especially tricky because Stuttgart is the city of Mercedes (over 19,000 employees) and Porsche (14,000), therefore particulate matter measurement is very controversial. So far, the action that is taken by the administration relies upon the good will of Stuttgart's citizens. 
The alarm was triggered when the German Meteorological Service (DWD) forecasts particular limitations in atmospheric airflow on at least two consecutive days between 15th of October 2016 and 15th of April 2017. During that time period, this was the case 13 times over a total of 85 days.

My question: Do citizens voluntarily change their behavior? I developed two approaches: Firstly, I plan to use data that comes from two bicycle counting stations in the center of the city to check whether there was a rise in cyclists during the alerts. This data is not published by the city, but was provided to me by an OpenSource network. Secondly, I would like to take a look at the ticket sales of Stuttgart's public transport. The figures could provide information about whether during the alerts actually more people switched from their cars to bus and subway than usually.

## Details

**Possible headline(s):** 
Biking instead of driving: how good is the good will of Stuttgarters?

**Data set(s):** 
Data
https://gist.github.com/mfa/455f7a278ea0099e8862d0dd1b04c46a

**Code repository:** 
https://github.com/ElisaHarlan/studio-projects/tree/master/code/2_Project%20Stuttgart%20Cyclists
	
**Possible problems/fears/questions:** 
Still waiting for some data from public transport in Stuttgart

## Work so far
I use data that comes from two bicycle counting stations in the center of the city to check whether there was a rise in cyclists during the alerts. This data is not published by the city, but was provided to me by an OpenSource network. I have done some basic analysis with the data yet. 
Secondly, I would like to take a look at the ticket sales of Stuttgart's public transport. The figures could provide information about whether during the alerts actually more people switched from their cars to bus and subway than usually.

## Checklist

This checklist must be completed before you submit your draft.

- [x] I have already spent time with my data set, opening it, exploring it, etc
- [x] I have created a "DIARY.md" file to save links and list all of the terrible, no good problems I come across
- [x] My issue issue has `[Project]` in the title
- [x] My issue links to my data set(s)
- [ ] My issue links to my code repository
- [ ] My issue explains what I'd like to explore in the data set
- [x] My issue includes images - either inspiration or what I've done so far
- [x] I have received two comments of peer feedback on my pitch issue

**Comment by kcough** [comment]
This is a great idea. As you mentioned, I think drawing this out would help tremendously-what do you imagine the final product being? I'm imagining a graph with bicycle use on the y axis (in numbers) and days or months on the x axis. If you could somehow overlay the days when there were air quality alerts (maybe by simply adding a different colored point or circle around the air quality alert day) that might be useful. 

I think if all of the info can be in one place that would be most user-friendly.

This is a terrible drawing but sort of what I'm imagining.

![image](https://user-images.githubusercontent.com/22796338/28276684-ad3bccfc-6ae5-11e7-8515-e889bc560517.png)
