### ISSUE TITLE
Ufos 

### ISSUE THREAD

**Issue by cathrinesot** [jsoma/data-studio-projects#20]
# Pitch

## Summary

I found an interesting dataset with UFOs sightings over the years in National UFO Reporting Center and I thought that it will be nice to map the UFOs appearances and the most common shapes and colors of them. Also maybe there are some trends, like:
In California appear red fireballs and in Toronto Blue Disks. 

## Details

The visualization could be a map with the number of the sightings and when you hover over the point the most common shape of this area could appear. Or if we want a not clickable viz I could try to make a timeline, but I don’t know how. 
The viz could be like this:
(http://www.mufon.com/track-ufos.html)

![sample](https://user-images.githubusercontent.com/28814380/28273077-4b6f81ee-6adb-11e7-9fda-efe15f67dc15.jpg)

### Possible Headlines:
UFOs fashion trends, what is the trend for 2017.
States attractive to UFOs.

### Dataset: http://www.nuforc.org/webreports/ndxevent.html

**Possible problems/fears/questions:** : The dataset is huge and selenium crashes after a while, I used a sample and I will try to find a way to get all the data. 

Also I have to do some digging, because I stumbled upon some articles about Area 51 and the Roswell Incident in 1947 and I believe that around those areas - dates there should be traffic. 

### Work so far:
I scraped a dataset for the last month, cleaned it and plot this graph about shapes:

![screen shot 2017-07-17 at 10 37 58 am](https://user-images.githubusercontent.com/28814380/28273338-1a4769dc-6adc-11e7-92df-4bc5dbedb108.png)

**Code repository:** 
https://github.com/cathrinesot/studioprojects/blob/master/code/Ufos/UFOS.ipynb

## Checklist

This checklist must be completed before you submit your draft.

- [x] I have already spent time with my data set, opening it, exploring it, etc
- [x] I have created a "DIARY.md" file to save links and list all of the terrible, no good problems I come across
- [x] My issue issue has `[Project]` in the title
- [x] My issue links to my data set(s)
- [x] My issue links to my code repository
- [x] My issue explains what I'd like to explore in the data set
- [x] My issue includes images - either inspiration or what I've done so far
- [x] I have received two comments of peer feedback on my pitch issue

**Comment by amandolinjames** [comment]
Love this idea!! It's really fascinating! I would suggest having a section of images that shows images over time of what people said the UFOs looked like- personally fascinated by this

**Comment by chrgavalas** [comment]
Great idea! I like the idea there are different UFO shapes! Make sure the testimonies are are valid as possible so that the data is accurate!

**Comment by RodrigoMenegat** [comment]
- I like the idea of researching 'UFO scares'. If you find that the sightings cluster around some dates, maybe these sightings are related to pop culture phenomenas, such as alien movies or something like that? That would be an interesting hypothesis to test!
- Looking at the map, it seems that sightings seem to cluster around highly populated areas. That's something to keep in mind when plotting the most UFO-obsessed states

**Comment by cathrinesot** [comment]
# Update
	
1 notebook

https://github.com/cathrinesot/studioprojects/blob/master/code/Ufos/UFOS-Final.ipynb

1 backup notebook ( I worked there while I was scraping on the original)

https://github.com/cathrinesot/studioprojects/blob/master/code/Ufos/UFOS-Final-Copy1.ipynb

## Content

https://github.com/cathrinesot/studioprojects/blob/master/code/Ufos/start.pdf

https://github.com/cathrinesot/studioprojects/blob/master/code/Ufos/draft1.pdf
![screen shot 2017-07-21 at 1 50 42 pm](https://user-images.githubusercontent.com/28814380/28475788-a932681c-6e1b-11e7-9c9e-75abde86b129.png)
![screen shot 2017-07-21 at 1 50 18 pm](https://user-images.githubusercontent.com/28814380/28475789-aaccbdc6-6e1b-11e7-8161-4cc84469337b.png)


	
## Any changes in direction or topic?
	No
## Problems/Questions
	I needed to scrape 110.000 reports, I will have 2 more graphs and maybe a map in the near future...
## Checklist
	
- [x] I have included my visuals
- [x] I have added writing about my topic
- [x] I have been updating my DIARY.md with details about my process
- [x] I have uploaded/updated any Jupyter Notebooks or other datasets into my code repository
- [ ] I have received two comments of peer feedback on my project update

**Comment by Ediegram** [comment]
Really fun topic! Your instincts are good to want to illustrate the shapes observed but the images you chose are all so different from each other. One way to make them uniform is by using icons ... try https://thenounproject.com ... a great resource. Also, if you make your chart a horizontal bar chart, the labels will have more space and will have a neater appearance.
You dont need to change the color of the bars to indicate the number is going down ... just make them all the same color.
