### ISSUE TITLE
Minnesota Census [Project]

### ISSUE THREAD

**Issue by mukhtaryare** [jsoma/data-studio-projects#21]
Please complete all of the following sections, or a robot will spookily dance around your issue! A completed version of this template can be found at https://github.com/jsoma/data-studio-projects/issues/1

# Pitch

## Summary
I would like to check how Minnesota's population has changed since 2000 and which group (or race) saw the most increase between 2000 to 2015.

I am hoping to produce a graph that looks like one of these two.

![latinovote1](https://user-images.githubusercontent.com/13924369/28273320-0f24bfbe-6adc-11e7-8284-c604686699c2.jpg)

... or

![la-me-g-irvine-immigrants-web-demographics](https://user-images.githubusercontent.com/13924369/28273671-f65a612c-6adc-11e7-8fbe-822e87a5c431.jpg)

## Details

**Possible headline(s):**  Minnesota's population sees slight decline since 2000
The changing face of Minnesota 

**Data set(s):** [American FactFinder data for Minnesota](https://factfinder.census.gov/faces/tableservices/jsf/pages/productview.xhtml?src=bkmk) and data from the [Minnesota State Demographic Center](https://mn.gov/admin/demography/data-by-topic/age-race-ethnicity/).

**Code repository:** https://github.com/mukhtaryare/data-studio-projects/blob/master/code/project/Minnesota%20Census%20Data.ipynb
	
**Possible problems/fears/questions:** 

## Work so far
My chart looks like this so far:

![chart_draft](https://user-images.githubusercontent.com/13924369/28275908-4c8b6bda-6ae3-11e7-9706-8c7b0b510725.png)

## Checklist

This checklist must be completed before you submit your draft.

- [x] I have already spent time with my data set, opening it, exploring it, etc
- [ ] I have created a "DIARY.md" file to save links and list all of the terrible, no good problems I come across
- [x] My issue issue has `[Project]` in the title
- [x] My issue links to my data set(s)
- [x] My issue links to my code repository
- [x] My issue explains what I'd like to explore in the data set
- [x] My issue includes images - either inspiration or what I've done so far
- [x] I have received two comments of peer feedback on my pitch issue

**Comment by 2109Sot** [comment]
That's really cool! I would love to know more about Minnesota and maybe the distribution of each race on a map.

**Comment by Dgorgs** [comment]
Very interesting! I have learned a lot about Minnesota's population. Very clear visualization.

**Comment by marcelpauly** [comment]
I think demographics is an important topic in the US. Maybe compare it with other data as well, election data for example …

**Comment by edl2118** [comment]
I like the idea of looking at how race is evolving in a predominantly white state. Great that the census data is collected consistently so I can trust the results!

**Comment by mukhtaryare** [comment]
# Update
	I have updated and cleaned my data a bit to make sure it only contains the information I need. 
## Content
	My graph looks like this so far:

![census-graph](https://user-images.githubusercontent.com/13924369/28468659-9d9bc314-6e01-11e7-9762-a75c0acf8fcf.png)

## Any changes in direction or topic?
	Instead of graphing all the races on a chart, I decided to use only minority groups in my data that make up less than 20 percent of the population. Minnesota's population is more than 80 percent white, and including the white group in the data makes the graph ugly. 
## Problems/Questions
	Will readers understand the point that my data is trying to convey?  
## Checklist

	
- [x] I have included my visuals
- [x] I have added writing about my topic
- [x] I have been updating my DIARY.md with details about my process
- [x] I have uploaded/updated any Jupyter Notebooks or other datasets into my code repository
- [ ] I have received two comments of peer feedback on my project update

**Comment by mukhtaryare** [comment]
I think this is closer to what I wanted my graph to look like. I combined all the minority groups into one and brought back the white population. The graph now adds up to 100 percent, with the majority being white.

![census-graph-kstp](https://user-images.githubusercontent.com/13924369/28583941-f1a61bf0-7138-11e7-918f-76bf3ff8428e.png)

**Comment by sarahslo** [comment]
Mukhtar, very interesting. Switch the headlines. The top chart shows a rise and the bottom charts shows that they are only 20%.
On the first chart you don't need to add the numbers with the % at the end, it's sort of like, belt and suspenders. The scale of the chart does the work, you don't need a number as well.

I'd suggest doing the math and calculating the rate of change by each race/ethnicity. (2015 # minus 2000 #) divided by 2000 #.  Then you know which one of these groups is growing faster and you can tell us a more nuanced story. The chart looks like blacks have grown the most, but really, the number of people who are two or more races have doubled....

Nice work!
