### ISSUE TITLE
When DNA is wrong: The champion of forensic science in doubt [Project]

### ISSUE THREAD

**Issue by adaskalopoulou** [jsoma/data-studio-projects#22]
# Pitch

## Summary

DNA forensics first made its way into the US courts in 1986 and, up until now,  has helped exonerate almost 1/4 of the total innocent individuals (2060 in total) listed in the National Registry of Exonerations database. The accuracy of the technology has made DNA evidence virtually indisputable. A 2009 report from the National Research Council, described DNA as the only forensic science worthy of the name. 
    Surveys about the operations of forensic crime laboratories (publicly operated) run by the Bureau of Justice Statistics show that 3/4 of the total DNA samples analyzed by these crime labs belong to convicted offenders. Data from the National Registry of Exonerations will help unroll the evolution of DNA forensics in the exoneration of innocent criminal defendants (i.e. year convicted, year exonerated, type of crime, the contributing factor of wrongful conviction).
    Yet, recently, geneticists start to question the accuracy of DNA forensics. Thanks to advances, such as the use of PCR (polymerase chain reaction, a simple yet elegant technique invented in 1983 by the maverick scientist Kary Mullis, who was awarded the Nobel Prize in chemistry in 1993), it was possible to detect tiny pieces of DNA, up to a thousand times smaller than DNA analysis of the past. However, PCR's exquisite sensitivity is believed to have backfired. The technique that once was the infallible wise man of forensics probably becomes the most dangerous conviction tool. 
    Data from the Innocent Project (a non-profit legal organization whose aim is to exonerate wrongly convicted individuals through the use of DNA techniques) show that in a dozen cases the type of forensic science problem linked to the wrongful conviction was the DNA testing itself. I plan to ask this data set the same questions posed before (to National Registry of Exonerations database) and find differences and similarities. Has the champion of forensic science been caught doping?

## Details

**Possible headline(s):** 
DNA forensics in the era of errors
DNA forensics: trapped in its own success
The champion of forensic science in doubt
DNA forensics under the microscope
When DNA is wrong

**Data set(s):** 
https://www.law.umich.edu/special/exoneration/Pages/mission.aspx
https://www.bjs.gov/index.cfm?ty=pbdetail&iid=1115
https://www.innocenceproject.org/all-cases/#exonerated-by-dna

**Code repository:** 
https://github.com/adaskalopoulou/studio-projects/tree/master/code/project1

**Possible problems/fears/questions:** 
Limited data on cases where the type of forensic science problem linked to the wrongful conviction was the DNA testing itself. 

## Work so far

![screenshot 2017-07-17 10 39 04](https://user-images.githubusercontent.com/28814404/28273421-5f9aec8e-6adc-11e7-8d06-36e3c80eeb52.png)

![screenshot 2017-07-17 10 39 29](https://user-images.githubusercontent.com/28814404/28273424-623fc914-6adc-11e7-84b0-6ca4f3eee375.png)

![screenshot 2017-07-17 10 39 56](https://user-images.githubusercontent.com/28814404/28273438-66eab712-6adc-11e7-960f-fc5a444d0a06.png)

![screenshot 2017-07-17 10 40 07](https://user-images.githubusercontent.com/28814404/28273469-7b089372-6adc-11e7-9a7f-f0c18a96ec0f.png)

![screenshot 2017-07-17 10 43 20](https://user-images.githubusercontent.com/28814404/28273592-c9b0b360-6adc-11e7-9fcd-c267937575ad.png)

![credit bbc](https://user-images.githubusercontent.com/28814404/28273282-ed37ec78-6adb-11e7-84b9-3a9a510d79d9.jpg)

## Checklist

This checklist must be completed before you submit your draft.

- [x] I have already spent time with my data set, opening it, exploring it, etc
- [x] I have created a "DIARY.md" file to save links and list all of the terrible, no good problems I come across
- [x] My issue issue has `[Project]` in the title
- [x] My issue links to my data set(s)
- [x] My issue links to my code repository
- [x] My issue explains what I'd like to explore in the data set
- [x] My issue includes images - either inspiration or what I've done so far
- [x] I have received two comments of peer feedback on my pitch issue

**Comment by simon-pinkmartini** [comment]
I'm sure this is going to be an interesting data to analyze! Can you show how different social groups are affected by false evidence? (eg black people)?

**Comment by JulienAssouline** [comment]
Love this idea. I think FiveThirtyEight did something on this a while back. Maybe you'd to check that out. I would be very interested in seeing how different gender or racial groups were affected by this.

**Comment by demetriospogkas** [comment]
Nice idea. Can you come up with a 'deeper' visualisation than just charts? Maybe a network plotting?

**Comment by adaskalopoulou** [comment]
# Update
  
## Content

Modern forensic science is in the midst of a crisis. One had seen enough of prime-time TV would believe that the power of DNA in pointing to the one and only person that committed a crime is indisputable. However, lately, it seems that this has never been the case. The FBI goes back and reopens thousands of cases and redoes the analysis and the math to determine whether indeed the people that were convicted are a real “match”. 
Many think of a DNA match as a pregnancy test, where the answer is yes or no. Matching a DNA includes a much more complex procedure and a series of judgments. The DNA samples collected are messy; no criminal lays down a blood drop on a petri dish before leaving the crime scene. The DNA found can be degraded, by light or heat, can be mixed with other DNAs or contaminated during collection. So analysts are confronted with results that need some judgment to determine, first if the data match the subject or secondly how often these similarities are present in a population. 
Nevertheless, there is good reason for DNA forensic science to have risen above all other techniques, such as bite-mark analysis, partial fingerprint matching, microscopic-hair-comparison and ballistics testing, which all have been proven far from consistent and trustworthy. There is no doubt that DNA science has helped exonerate hundreds of wrongly convicted individuals, but at the same time felt into some of the sins of its ancestors. 

![graph 1](https://user-images.githubusercontent.com/28814404/28461325-1a084ea4-6de4-11e7-945b-1426f29274d4.png)

In this graph I would also like to include markers to connect the dates with the history of the introduction of DNA in the FBI (Table 1).

![table 1](https://user-images.githubusercontent.com/28814404/28461350-3f78f350-6de4-11e7-8a0e-f545ad3b9d1d.png)

---

When DNA forensic science was introduced there was the promise of being the rational silver bullet of forensics that will eliminate all the biases of the criminal justice system, such as race and class. On the contrary, the system plays out entirely in the DNA context as well. It all starts with the DNA collection policy that mandates that every person arrested or convicted has to provide a DNA sample. It is well known that the US criminal system doesn’t arrest and convict people with total equality. Consequently, when one looks for a DNA match in a pool of samples from people that were caught up in a criminal justice system that has all these biases, the inequality trait is inherited to their judgment. 

![race 1](https://user-images.githubusercontent.com/28814404/28462008-42ab4c96-6de7-11e7-8721-b7d2807baa32.png)
![race 2](https://user-images.githubusercontent.com/28814404/28462011-44e02446-6de7-11e7-9acb-bf6d2d5253ba.png)
![race 3](https://user-images.githubusercontent.com/28814404/28462012-4775c684-6de7-11e7-8ebb-ce9a8274fb7b.png)

---
MORE INFORMATION:

![age](https://user-images.githubusercontent.com/28814404/28462295-995229b0-6de8-11e7-9309-2ee859652544.png)

---

Average years lost (DNA-exonerated cases): 16 years

---

![conviction](https://user-images.githubusercontent.com/28814404/28462301-a1145466-6de8-11e7-9547-7eb2f616c6ff.png)

![conviction dna](https://user-images.githubusercontent.com/28814404/28462372-f65cdace-6de8-11e7-9de6-f9c9be22d2eb.png)

![conviction all](https://user-images.githubusercontent.com/28814404/28462349-dcf1914c-6de8-11e7-89f6-97aa584ccf5d.png)
---
---
![crime dna-ex](https://user-images.githubusercontent.com/28814404/28462386-03acdc7e-6de9-11e7-9a0c-0b549518e0ff.png)

![crime all](https://user-images.githubusercontent.com/28814404/28462389-0583ff0a-6de9-11e7-8497-f6884933df04.png)

## My code and notebooks:
https://github.com/adaskalopoulou/studio-projects/tree/master/code/project1

## Any changes in direction or topic?

Should I explore other science forensic tools, such as hair analysis, that lead to wrongful convictions?

## Problems/Questions
1. The data about exonerated cases in which the forensic science problem was connected to the DNA analysis is still scarce. 

2. I don't like how Graph 1 looks like, can you help me fix it?

## Checklist
  
- [x] I have included my visuals
- [x] I have added writing about my topic
- [x] I have been updating my DIARY.md with details about my process
- [x] I have uploaded/updated any Jupyter Notebooks or other datasets into my code repository
- [x] I have received two comments of peer feedback on my project update

**Comment by adaskalopoulou** [comment]
# Update
Modern forensic science is in the midst of a crisis. One had seen enough of prime-time TV would believe that the power of DNA in pointing to the one and only person that committed a crime is indisputable. However, lately, it seems that this has never been the case. The FBI goes back and reopens thousands of cases and redoes the analysis and the math to determine whether indeed the people that were convicted are a real “match”.

Many think of a DNA match as a pregnancy test, where the answer is yes or no. Matching a DNA includes a much more complex procedure and a series of judgments. The DNA samples collected are messy; no criminal lays down a blood drop on a petri dish before leaving the crime scene. The DNA found can be degraded, by light or heat, can be mixed with other DNAs or contaminated during collection. So analysts are confronted with results that need some judgment to determine, first if the data match the subject or secondly how often these similarities are present in a population.

Nevertheless, there is good reason for DNA forensic science to have risen above all other techniques, such as bite-mark analysis, partial fingerprint matching, microscopic-hair-comparison and ballistics testing, which all have been proven far from consistent and trustworthy. There is no doubt that DNA science has helped exonerate hundreds of wrongly convicted individuals, but at the same time felt into some of the sins of its ancestors.

## Content

![boring-graph 10copy](https://user-images.githubusercontent.com/28814404/28551756-06a8b6ec-70b8-11e7-86ff-4e71f2de0ee5.png)
	
## Checklist
	
- [x] I have included my visuals
- [x] I have added writing about my topic
- [x] I have been updating my DIARY.md with details about my process
- [x] I have uploaded/updated any Jupyter Notebooks or other datasets into my code repository
- [x] I have received two comments of peer feedback on my project update

**Comment by adaskalopoulou** [comment]
# Final

**[Published website version](https://adaskalopoulou.github.io/studio-projects/project-1/)**

## Project visuals/text





![updata_graph_6](https://user-images.githubusercontent.com/28814404/28698983-d356047a-7314-11e7-953e-a09ea91d9b1d.png)





**When DNA is wrong: The champion of forensics science in doubt** 

DNA forensics first made its way into the US courts in 1986 and, up until now, has helped exonerate almost 450 innocent individuals, according to the National Registry of Exonerations. The accuracy of the technology has made DNA evidence virtually indisputable. Yet, recently, geneticists start to question the accuracy of DNA forensics, not in exoneration cases, but in those of convictions based almost entirely on DNA evidence. 

The journey of DNA forensics begins in 1985 at the University of Leicester in Great Britain, where the geneticist Dr. Alex Jeffreys, develops the technique of genetic fingerprinting. The molecular method of genetic analysis that he used, called Restriction fragment length polymorphisms (RFLPs), involves determining differences in DNA at precise regions, which are unique for every individual. 

Thanks to synchronous advances in genetics, such as the use of the PCR (polymerase chain reaction) technique, it was made possible for forensic scientists to detect tiny pieces of DNA, up to a thousand times smaller than DNA analysis of the past. The simple, yet elegant, PCR technique was invented in 1983 by the maverick scientist Kary Mullis, who, for this discovery, was awarded the Nobel Prize in chemistry in 1993.  

A 2009 report from the National Research Council, described DNA as the only forensic science worthy of the name. There is undoubtedly good reason for DNA forensic science to have risen above all other techniques, such as bite-mark analysis, partial fingerprint matching, microscopic-hair-comparison and ballistics testing, which all have been proven far from consistent and trustworthy. 

The Innocent Project, a non-profit legal organization whose aim is to exonerate wrongly convicted individuals through the use of DNA techniques, has done the math. Almost 200 people have been wrongly convicted because of a forensic science problem with the evidence. Nevertheless, in ten of these cases, the problem was the DNA analysis itself, falling into the same sins of its ancestors. 

---

Modern forensic science is in the midst of a crisis. One had seen enough of prime-time TV would believe that the power of DNA in pointing to the one and only person that committed a crime is indisputable. However, lately, it seems that this has never been the case. PCR's exquisite sensitivity in detecting tiny pieces of genetic material is believed to have backfired in its use in DNA forensics. 

Many think of a DNA match as a pregnancy test, where the answer is a yes or a no. Matching a DNA includes a much more complex procedure and a series of judgments. The DNA samples collected are messy; besides no criminal lays down a blood drop on a petri dish before leaving the crime scene. The DNA found at a crime scene can be destroyed in various ways: degraded, by light or heat, mixed with other DNAs or contaminated during collection. Therefore analysts are confronted with results that need some judgment to determine, firstly, if the data match the subject and, secondly, how often these similarities are present in a population.

Additionally, when DNA forensic science was introduced there was the promise of being the rational silver bullet of forensics that will eliminate all the biases of the criminal justice system, such as race and class. On the contrary, the system played out entirely in the DNA context as well. It all starts with the DNA collection policy that mandates that every person arrested or convicted has to provide a DNA sample. It is well known that the US criminal system doesn’t arrest and convict people with total equality. Consequently, when one looks for a DNA match in a pool of samples from people that were caught up in a criminal justice system with all these biases, the inequality trait is inherited to their judgment.

The technique that once was the infallible wise man of forensics has probably become the most dangerous conviction tool. Today the FBI goes back and reopens thousands of cases and redoes the analysis and the math to determine whether the people that were convicted are indeed a real “match”. The champion of forensic science has been caught doping. 



## Details

**Code repository: [https://github.com/adaskalopoulou/studio-projects/tree/master/code/project1](https://github.com/adaskalopoulou/studio-projects/tree/master/code/project1)**

**Final data set(s): [https://github.com/adaskalopoulou/studio-projects/tree/master/code/project1](https://github.com/adaskalopoulou/studio-projects/tree/master/code/project1)**

## What did you find to be the most difficult part of this project?
Finding a dataset (probably from the FBI) with a larger sample of cases where the individual was wrongly convicted based on false DNA evidence. 

## Are you satisfied with what you produced? Is there anything you would like to change or improve?
Because of the lack of the above-mentioned dataset this wasn't probably a good fit for a data story. 

## Checklist

- [x] I have included my visuals
- [x] I have posted my project to my project website
- [x] I have been updating my DIARY.md with details about my process
- [x] I have uploaded/updated any Jupyter Notebooks or other datasets into my code repository

**Comment by qdinhbui2** [comment]
I think this is a very interesting story. But it's confusing on a couple of points: are you saying that the FBI are re-opening DNA cases to check with this new method? Like what is the likely outcome of improved DNA testing.

This is an interesting idea. 
`Many think of a DNA match as a pregnancy test, where the answer is a yes or a no. Matching a DNA includes a much more complex procedure and a series of judgments.` 

In terms of graphics -- is there data to that gives us an indication of how confident each test is? If there is you could focus in on all the tests where the result was not very confident.
