### ISSUE TITLE
[Project]The crimes the police does not tell you about

### ISSUE THREAD

**Issue by pasiegrist** [jsoma/data-studio-projects#226]
# Pitch

## Summary

Everyday, the police is sending out press releases about this and that. Often they tell us, when they successfully catch somebody, a major crime was committed, a case was some sort of weird or they make announcements about road blocks etc. 

What the police report on, journalist report on – often. Of course journalist do investigations, see stuff, get tipps, but most news articles on crime are based on press release by the police. The police acts as a major gatekeepr. And eventhough numbers of press releases are high, crime stats are much higher. This means: A lot of crimes, the police is not telling us about. This shapes public perception of crime. I want to use this pitch to get a larger investigation started, to analyse what the police in the city and in the canton of Zurich is reporting on. 

## Details

There are a lot of different ways to tackle this topic.
- First of all I want to do a descriptive part, showing how often the police is issuing press releases. I would like to to this on a monthly basis for a few years. 
- Using word counts I want to find out, what the big topics where in each month.
- Crimes outside the big cities of Winterthur and Zurich is all reported by the state (cantonal) police departement. I want to look, if there is a bias in regional reporting, comparing the count of press releases in different counties with the actual crime.
- What nationalities do they report on?

**Possible headline(s):** 

The crimes the police does not tell you about

**Data set(s):** 

Press releases of the Kantonspolizei Zürich:
https://ds.zh.ch/internet/sicherheitsdirektion/de/aktuell/medienmitteilungen.html

Press releases of the Stadtpolizei Zürich:
https://www.stadt-zuerich.ch/pd/de/index/stadtpolizei_zuerich/medien/medienmitteilungen.html

**Code repository:** 
https://github.com/pasiegrist/Datastudio/tree/master/Code/03_police_reporting

**Possible problems/fears/questions:** 

- How do I visualize Word Counts? Word Clouds are prohibited – and that's ok :)
- How do I handle german language with the skills we've learned in algorithm?

The topic is huge. I got to focus on part of it and I haven't found the time so far to draw any graphics. So I really appreciate any inputs of you guys.

## Work so far

I coded two scrapers and downloaded all the press releases. 

And because I don't have any graphics for now, here a gif of a cute dog:
![giphy](https://user-images.githubusercontent.com/15381149/43422870-f91ff366-9418-11e8-87c1-2e6585d39002.gif)

## Checklist

This checklist must be completed before you submit your draft.

- [x] I have already spent time with my data set, opening it, exploring it, etc
- [ ] I have created a "DIARY.md" file to save links and list all of the terrible, no good problems I come across
- [x] My issue links to my data set(s)
- [x] My issue links to my code repository
- [x] My issue explains what I'd like to explore in the data set
- [x] My issue includes images - either inspiration or what I've done so far

**Comment by pasiegrist** [comment]
# Update
	
## Your project content: images/words/etc

I am trying to find patterns in the police press releases in Zurich. So far I scraped the press releases for the past two years for the Kantonspolizei, that issues press releases for all the municipalities except of the cities Winterthur and Zurich, and the Stadtpolizei, the city police. 

![output_releases](https://user-images.githubusercontent.com/15381149/43598163-0a58e468-9652-11e8-912b-a8b8dbcd7e84.png)

The graph shows the amount of press releases issued every month.

After that I started struggling with the data, got lost a few times, got then even more lost, and ended up with the following to graphs that show the relation between crimes commited (normalized per citizens) and the amount of press releases mentioning municipalities in thes counties (normalized per number of commited crimes).
##
The first one is for the counties (without the cities Winterthur and Zurich). It shows that the simple formula: the more crime, the more press releases doesn't hold up. 
##
![output_releases_percount_double](https://user-images.githubusercontent.com/15381149/43598858-c626b17e-9653-11e8-86d7-39d967e202f8.png)

##


## Any changes in direction or topic?
  
Not so far. Still trying to find the one focus to end this project with.
	
## Problems/Questions

- Haven't had time to make the graphs nice, these are just matplotlib-outputs.
- Handling text is just miserable.
- How do I visualize Word Counts? Word Clouds are prohibited – and that's ok :)
- How do I handle german language with the skills we've learned in algorithm?
	
## Checklist
	
- [x] I have included my visuals
- [x] I have filled out the sections above
- [ ] I have been updating my DIARY.md with details about my process
- [x] I have uploaded/updated any Jupyter Notebooks or other datasets into my code repository

**Comment by sarahslo** [comment]
Yes, getting lost is part of the process. I am still lost alllll the time, so just so you know. Good thing is you keep trying.

To handle word counts people often do bubble charts. And working with language is really rough because 1 word can have so many meanings. Just having the words doesn't tell me what type of press release it is.  Because of this, I don't think you can safely link crimes to press releases.
But it could be interesting just seeing first what they are talking about and then seeing if there is a different dataset that relates.


![screen shot 2018-08-02 at 8 38 57 pm](https://user-images.githubusercontent.com/659014/43618066-4d00c564-9694-11e8-94bc-32dbc80030fd.png)

**Comment by pasiegrist** [comment]
# Update
	
## Your project content: images/words/etc
	
At the moment I don't have any new graphics to present. I used the time to try out several analysis methods to handle the text. I managed to get all the mentions of nationalities out for example. But I got hardly any sense out of the press releases by using word counts or TF-IDF.
  
## Any changes in direction or topic?
  
I will focus on the comparison between the regional and nationality mentions compared to the actual crime statistics. If I find the time, I would like to try out a manually coded index list, to classify the press releases for crimes.
	
## Problems/Questions
  
- I ran a TF-IDF, but unfortunately I always got the same words weighted high. I thought, doing TF-IDF it looks for differences between so this won't happen?
- Is there any good use for word count?
	
## Checklist
	
- [ ] I have included my visuals
- [ ] I have filled out the sections above
- [ ] I have been updating my DIARY.md with details about my process
- [ ] I have uploaded/updated any Jupyter Notebooks or other datasets into my code repository

**Comment by pasiegrist** [comment]
# Final
Everyday, the police is sending out press releases about this and that. Often they tell us when they successfully catch somebody, a major crime was committed, a case was some sort of weird or they make announcements about road blocks etc.
What the police report on, newspapers report on quite often. Of course journalist investigate, see stuff, get tipps, but a majority of news articles on crime are based on press release by the police. The police acts as a major gatekeepr. And eventhough numbers of press releases are high, crime stats are much higher. This means: A lot of crimes, the police is not telling us about. 
On what and how often the police is reporting on shapes public perception of crime. Are some neighbourhoods really as dangerous as they sound? Or do non Swiss nationals commit that much more crime? 
I have scraped all the press releases issued by the Stadtpolizei Zürich, the city police, since 2016 to see, if there is an obvious distortion. I first analyzed, how many times a certain neighbourhood is mentioned in press releases and compared this to the actual amount of crimes commited there.
## Project visuals/text


<img width="814" alt="screen shot 2018-08-09 at 13 51 11" src="https://user-images.githubusercontent.com/15381149/43916349-54033490-9bdb-11e8-968c-f8898aa596e8.png">

ooking at the map, one can see that the distribution is quite similar. There are some of the neighbourhoods aren't mentioned as often as crimes are commited, but the big picture is very similar. A problem with this graph is, it includes a statistical distortion, which is typical for the city of Zurich. The neighbourhood Kreis 1, just in the middle of the map, is always up with crime or welfare benefits for example. This is because in Kreis 1, people are included that are registered in Zurich but don't have residence, for example prison inmates.

Is there a nationality bias?

Similar to the neighbourhood analysis, I checked, if there is a bias in reporting on crimes commited by foreigners. This is actual a very political topic in Zurich. To prevent misperception and empowerement of stereotypes, the city of Zurich prohibited in 2017 that the police is stating the nationality of offenders and victims. They are still allowed to tell a journalist when they call and ask, but they shall not put it in the press release.
![nationality_size_b](https://user-images.githubusercontent.com/15381149/43916363-625bc750-9bdb-11e8-8631-2a1809029164.png)
Looking at the mentionings, the most obvious thing we can see, is the drop of number of mentionings, caused by the new city law. Comparing the share of the mentionings to the actual commited crimes of the crime statistics on state level, one can see that there actually was no bias against foreigners in the press releases in 2017, as 46 of the mentionings were Swiss – the same holds true for 2016.

**Headline:** 

Does the Police Report Accordingly?

**Published website version:**
https://pasiegrist.github.io/police

**Code repository:**
https://github.com/pasiegrist/Datastudio/tree/master/Code/03_police_reporting

**Final data set(s):** 
https://github.com/pasiegrist/Datastudio/tree/master/Code/03_police_reporting

## What did you find to be the most difficult part of this project?

- Handling text. I think I chose this project in a too early stage of the program, as we are now talking more about machine learning in algorithms class.

## Are you satisfied with what you produced? Is there anything you would like to change or improve?

It is what it is. I like that I was able to find the mentions and see, that these script work. But as I mentioned above several times, I have just started analysing this and I might will get back to this in a later project and where I can use the new skills learned in algorithm, so I might can reaally answer the question I started out with: Which crimes the police is not telling us about.


## Checklist

- [x] I have included my visuals
- [ ] I have posted my project to my project website
- [x] I have been updating my DIARY.md with details about my process
- [x] I have uploaded/updated any Jupyter Notebooks or other datasets into my code repository

**Comment by vpenney** [comment]
The playfair bot just sent me here, and since your project is already finished, I'll keep it brief. I think this is a great topic and a fascinating question. Pulling in the actual crime statistics to support your text scraping was a good call and it's interesting to see how the press releases compare to the actual crimes. I was surprised at how similar the crimes and the mentions are--I wonder if that's true in all cities, or if bigger cities feel more pressure from journalists/ the public to be transparent? 

I'd be interested to see what else you come up with if you keep working on this!
