### ISSUE TITLE
What are Torontonians e-reading habits? [Project]

### ISSUE THREAD

**Issue by edl2118** [jsoma/data-studio-projects#25]
# Pitch

## Summary

According to media releases from the Toronto Public library, our city’s digital lending habits are on the rise. One interesting insight is that we are borrowing more digital books than any other library system worldwide. This led me to wonder if digital lending rates are evenly distributed across the different wards of Toronto.

I would like to create coropleths showing
ebook circulation across the wards
the most popular genre for ebooks across the wards
the most popular authors for ebooks across the wards
A horizontal bar chart showing the top 20 titles for ebooks in Toronto as a whole

Sample aspirational visualization:
![inspiration](https://user-images.githubusercontent.com/28814369/28450381-0e13ff46-6db5-11e7-9243-e7f00cda7671.jpg)

## Details

**Possible headline(s):**

Same but Different: the e-reading habits of Torontonians
TPL’s most popular book of June: The Other Einstein (A Novel)

**Data set(s):**

Shapefile for Toronto’s 44 wards ( https://www1.toronto.ca/wps/portal/contentonly?vgnextoid=b1533f0aacaaa210VgnVCM1000006cd60f89RCRD)

Longitudes and latitudes for TPL branches (BranchBridgeTable.xls )

June 2017 transaction data for eBooks, audio books, and videos (eProduct_CirculationActivityDetail-201706)

**Code repository:**
https://github.com/edl2118/studio-projects.git

**Possible problems/fears/questions:**
Fears - I only have raw data for June 2016 so the findings are just focused on this narrow time period and I'm worried they won't be very actionable

Problems - Currently, I only have data that tells me how many cardholders are checking out eBooks but what I'd like to calculate is the % card holders from the total population of library cardholders in each branch. There is census data from 2011 that I will need to incorporate.

## Work so far

![image](https://user-images.githubusercontent.com/28814369/28450300-747610e0-6db4-11e7-9961-f0a1166f40f5.png)

## Checklist

This checklist must be completed before you submit your draft.

- [x] I have already spent time with my data set, opening it, exploring it, etc
- [ ] I have created a "DIARY.md" file to save links and list all of the terrible, no good problems I come across
- [x] My issue issue has `[Project]` in the title
- [x] My issue links to my data set(s)
- [x] My issue links to my code repository
- [x] My issue explains what I'd like to explore in the data set
- [x] My issue includes images - either inspiration or what I've done so far
- [x] I have received two comments of peer feedback on my pitch issue

**Comment by marcelpauly** [comment]
I'm very interested in the merge with census data: Children, age, income, … maybe election results?

**Comment by mukhtaryare** [comment]
I really love this idea. Looking forward to seeing the final product.

**Comment by Dgorgs** [comment]
A very interesting topic, cool idea!

**Comment by 2109Sot** [comment]
This is so interesting! I'd love to see the most popular e-books by genre and gender.

**Comment by edl2118** [comment]
# Update

	
## Content
This is the final output of the first stage in my project:


![the romantics](https://user-images.githubusercontent.com/28814369/28508131-b1ddd496-7006-11e7-85cf-597b7d96db9c.png)

	
## Any changes in direction or topic?
My original research question was if eBook circulation was higher in certain wards than others. After surveying all the results of my analysis, it became more clear that there was perhaps more interesting findings like the clear preferences in regions for Literature or Romance etc. So, I decided to edit things down and focus primarily on genre preferences and to a lesser extent eBook titles and circulation. I originally wanted to include bar charts to show top ten lists for books but it was easier to tell a story with just three key findings without introducing this sidebar of top ten lists. When I saw Bui's multiple maps, I really felt that using static maps would work for my project as well. Having three maps I felt allowed the reader to look at Toronto through these three different lenses of genre, title, and circulation 
	
## Problems/Questions
There was lots of delay in getting the data in a timely manner. And when the data was available, there were questions that needed to be answered about how the library defined wards versus the city and what measures were actionable for the library. People are busy as you can imagine so it took a while to get my questions answered. 

I also had some issues dropping and resetting indexes but not a big deal. The biggest takeaway for me programatically was to draw out my plan for merging the multiple data sets. It doesn't seem like a lot (shape file, longitude/latitude for branches, and eCirculation data) but it can get confusing if you can't keep straight what you're linking in each data set. I received the datasets from the library in piece meal and multiple versions so I could have better organized my workflow I think. 

Illustrator was interesting to work with. I would continue to use it because it really helps to polish the final visualization but man it's detailed work and so many layers to delete. I'm sure with more practice and figuring out shortcuts, it will be a more fun experience.  

Feedback from data studio-Friday was super helpful! I really appreciated everyone's feedback about how I could make the final draft more "human readable". 

## Next Steps
Look more closely at eBook circulation as a percentage of the total ward population. I had asked the library if they could provide me with number of cardholders in each branch but unfortunately they cannot so I will need to go to census data. I hesitated to do this because the data is a bit old (2011) so I'm not sure how representative it is of the current population. Also, not every person in a ward is necessarily a library cardholder so another concern of mine is overestimating the branch population numbers.

The plan is to bring in census data next to say something more meaningful about the people who live in each of these wards in terms of ages, race, household income, household size, and perhaps primary language.

## Checklist
	
- [x] I have included my visuals
- [x] I have added writing about my topic
- [ ] I have been updating my DIARY.md with details about my process
- [x] I have uploaded/updated any Jupyter Notebooks or other datasets into my code repository
- [ ] I have received two comments of peer feedback on my project update

**Comment by edl2118** [comment]
# Final

## Project visuals/text
![the-romantics](https://user-images.githubusercontent.com/28814369/28747617-9d7609aa-7471-11e7-8df4-dc3d268a9600.gif)

## Details

**Headline:** 
The Romantics In Toronto

**Published website version:**

**Code repository:**
https://github.com/edl2118/studio-projects.git

**Final data set(s):** 

Shapefile for Toronto’s 44 wards ( https://www1.toronto.ca/wps/portal/contentonly?vgnextoid=b1533f0aacaaa210VgnVCM1000006cd60f89RCRD)

Longitudes and latitudes for TPL branches (BranchBridgeTable.xls )

June 2017 transaction data for eBooks, audio books, and videos (eProduct_CirculationActivityDetail-201706)

## What did you find to be the most difficult part of this project?
The most difficult part for me was planning out my workflow in a way that I could go back to and follow easily. The group by function created multiple indexes and reindexing was a bit of a learning curve.  

## Are you satisfied with what you produced? Is there anything you would like to change or improve?
Generally, I'm happy with the visualization. I wish I had more time to research why "The Other Einstein" was such a popular book last month. In the time allotted, I couldn't find the book in any notable reading list. The library did not tweet about it nor was the book recommended in Overdrive. If I had more time, I would probably try to dig a little deeper. Maybe interview some of the librarians for explanations about its popularity. 

## Checklist

- [x] I have included my visuals
- [ ] I have posted my project to my project website
- [ ] I have been updating my DIARY.md with details about my process
- [x] I have uploaded/updated any Jupyter Notebooks or other datasets into my code repository

**Comment by sarahslo** [comment]
Good start and interesting dataset. It didn't lead you where you expected but you continued to see what was there and that is the right instinct.

Let's start with a technical detail. The gradient scale on the ebooks is broken into very odd integers. 0-2193, 219**4**-3077. I can't think this way as a reader, I'm guessing you just divided? With these scales they should be more reader friendly and broken into numbers that have a rational pattern. 0-2000, 2001-4000, 4001-8000. <This is a doubling or 0-2,500, 2,501-5000, 5001-7500. Think of making the buckets of data more like money, divided in a way we can count. That will also change how your map looks.

As to the story telling, I think you could combine the top 2 maps and simply overlay pictures of each books on top of the map. As a matter of fact, you could do that will all the top books so we can see what people are reading. Here is [an example](https://qz.com/494167/the-most-popular-books-in-u-s-public-libraries-mapped-by-city/) of a similar analysis

To me, the most curious thing here is that area that is reading historical fiction most. What is that? Also, what is going on with the top and the bottom, the A-Z of this? The places that read the most and the least. With a little reporting to answer these questions, this is the start of an nice visual story.
