### ISSUE TITLE
[Project] Following Mr. Schmid

### ISSUE THREAD

**Issue by pasiegrist** [jsoma/data-studio-projects#251]
# Pitch

## Summary

In March 2019 are cantonal (county) elections in Zurich. We elect a new state legislature. One of the guys, who is already a member is very active on Twitter (yes, this is something special in Switzerland) and a right wing politician. I want to have closer look at his tweeting behaviour. Especially I want to code a Twitter-Livestream, which would allow me to see, what tweets he regrets and deletes after a certain time.

## Details

**Possible headline(s):** 
17 Tweets Mr. Schmid don't want us to see anymore – and that's for a reason

**Data set(s):** 
None so far, as I first have to build the Twitter-Stream.

**Code repository:** 
https://github.com/pasiegrist/Datastudio/tree/master/Code/04-Twitter

**Possible problems/fears/questions:** 
- How do I make sure, the twitter bot is running on the server all the time?
- Are there limitations from the Twitter API?

## Work so far

I have played around with the Twitter API, managed to connect and managed to keep a stream alive for a while.

I have nothing visualised so far. But this is him:

<img width="586" alt="screen shot 2018-08-06 at 07 36 35" src="https://user-images.githubusercontent.com/15381149/43714588-7c03d3c4-994b-11e8-86b7-ca11242df73c.png">

## Checklist

This checklist must be completed before you submit your draft.

- [x] I have already spent time with my data set, opening it, exploring it, etc
- [ ] I have created a "DIARY.md" file to save links and list all of the terrible, no good problems I come across
- [x] My issue links to my data set(s)
- [x] My issue links to my code repository
- [x] My issue explains what I'd like to explore in the data set
- [ ] My issue includes images - either inspiration or what I've done so far

**Comment by pasiegrist** [comment]
# Update
	
## Your project content: images/words/etc
	
Here is a fun fact: Mr. Schmid is not unique. Playing around with the Twitter-API and the Tweepy-Streamer I realized, that there is not only one Mr. Schmid on Twitter, there is two. And this is not a fake profile, it is curated, looking exactly the same, but the content is slightly different. He actually uses his account to retweet himself. I still don't have any graphics yet, but I was able to download more than a 1000 of his last tweets for each of his account. I will probably do a comparison on the both profiles, how their beahviour differs, do they retweet different accounts? What's their retweeting mean? What Newssites do they share?

## Any changes in direction or topic?

Yes, a little as I found out, that this guy has two profiles that he actually uses.
  	
## Problems/Questions
  
- I am still trying to get a Twitter-Stream on DigitalOcean running. I was able to do it. But it crashed and I didn't get an error message in the inbox. I will keep trying.
	
## Checklist
	
- [ ] I have included my visuals
- [ ] I have filled out the sections above
- [ ] I have been updating my DIARY.md with details about my process
- [ ] I have uploaded/updated any Jupyter Notebooks or other datasets into my code repository

**Comment by mattrehbein** [comment]
I'd definitely like to know whether his two accounts are different in their activity, whether one tends to tweet/retweet more inflammatory content vs the other.

What were you thinking for visualization? If you can find some examples of different tweet behavior in the two accounts, then you could place tweets side by side to demonstrate it.

What are the 17 tweets he doesn't want us to see that you reference in your possible headline?

**Comment by pasiegrist** [comment]
# Update
	
## Your project content: images/words/etc

I have started comparing the two counts to one another. A first draft of my graphic is here:

![cs_twitter_size_c](https://user-images.githubusercontent.com/15381149/44121035-5ba0b032-9fec-11e8-911b-9a602761f879.png)

As well my Twitter-Bot is now up and running (since Monday 3 pm). I know get every day an update via e-mail with the tweets he decided to delete again (for whatever reason). And I hope I will find some of them, that will be news worthy (even though I am pretty sure I will not have 17 by next friday, I hope this answers your question @mattrehbein ).

I try to do an TF-IDF to find out, how similar the accounts are, but I haven't found the time yet.
  
## Any changes in direction or topic?
  
Not since the last update.
	
## Problems/Questions

Not at the moment. There were a lot while building the bot and get it running on the server. But at the moment, I am fine.  
	
## Checklist
	
- [x] I have included my visuals
- [x] I have filled out the sections above
- [ ] I have been updating my DIARY.md with details about my process
- [ ] I have uploaded/updated any Jupyter Notebooks or other datasets into my code repository

**Comment by sarahslo** [comment]
this is craziness! nice. 
for the share of tweets by hour, can you make these hours in the day so the are easier to understand? you could also chart the number of followers, make bubbles. and what is the retweet number? 25-point-7? whats?

**Comment by kevinlitman-navarro** [comment]
- the reflected avatar is pure gold! 

- Could you also tell us how often these accounts are amplifying each other? That is, what percentage of the tweets from the second account are retweets from the first? This is so embarrassing for that guy

**Comment by pasiegrist** [comment]
# Final

## Project visuals/text
The surprise hit me late, but suddenly all was clear. There ist this guy in our state legilsature called the Zürcher Kantonsrat, Mr. Schmid. He is an elected representative for the SVP, the Schweizerische Volkspartei, which some call right-wing populists, some just right-wing and others conservative. We could fight over the label for ours, but they still would be the party that got the highest number of votes in the last few election cicles – on a national and on state level. But back to Mr. Schmid. Mr. Schimd likes twitter. And he tweets a lot and he deletes a lot of is tweets later on again. What I didn't realize for a long time, that Mr. Schmid like twitter so much, that he actually has two accounts which one can hardly tell the difference. So I had a closer look.
![cs_twitter1_size_c](https://user-images.githubusercontent.com/15381149/44284740-c4e0d900-a230-11e8-86d9-a092e3c56405.png)


![cs_twitter2_size_c](https://user-images.githubusercontent.com/15381149/44284739-c4e0d900-a230-11e8-9230-5114821963de.png)

## Details

The analysis of his tweeting behaviour was actually secondary for my project. I used it to get more familiar with the method of TF-IDF and cosine-similarity. The main reason for doing this project was, I wanted to set up a template for a twitter-bot that allows me to track certain people and save all their tweets, so I still have them, when they delete one. As an additional feature, I wrote a few lines of code, so that every morning on 8am I get a morning briefing that shows me the deleted tweets and returns a link to the wayback machine, where the tweet was stored. 

**Headline:** 
Following Mr. Schmid

**Published website version:**
https://pasiegrist.github.io/twitter/

**Code repository:**
https://github.com/pasiegrist/Datastudio/tree/master/Code/04-Twitter

**Final data set(s):** 
https://github.com/pasiegrist/Datastudio/tree/master/Code/04-Twitter

## What did you find to be the most difficult part of this project?
- Setting up the Bot. It was hard to get the actual information I want into the newsletter and to get it up and running on the server.
- The TF-IDF was kind of demanding, but it helped me to understand more the concept of this tool now.

## Are you satisfied with what you produced? Is there anything you would like to change or improve?

The twitter bot is up and running since 13th of August, 3pm and does a good job until now. It needs still some re-adjustments, as I get also deleted tweets by useres, who replied on Mr. Schmids tweets. But ignoring this fact, it works pretty well. In addition I managed to pull through a TF-IDF-Cosine-Similarity-Analysis which I like to be able to. But on the other hand: It's a twitter analysis. And Twitter is… Twitter. 

## Checklist

- [x] I have included my visuals
- [x] I have posted my project to my project website
- [ ] I have been updating my DIARY.md with details about my process
- [x] I have uploaded/updated any Jupyter Notebooks or other datasets into my code repository

**Comment by maxarvid** [comment]
Politicians use of twitter is always fascinating, they are so weird! 

I realise this is closed and rightly so, I have nothing to contribute, just obeying the bot 🙇 .

Good job resisting putting a bizarro mustache and instead flipping the profile pic:
![tumblr_ml7kfycfq01r05o4uo1_500](https://user-images.githubusercontent.com/31871856/44423107-2c5d9800-a553-11e8-8ed1-d3683eab582e.gif)
