### ISSUE TITLE
[Project]And there is this funny politician

### ISSUE THREAD

**Issue by pasiegrist** [jsoma/data-studio-projects#284]
# Pitch

## Summary

And here we go again. PDFs. Text. Regex. Getting lost. I want to analyse the transcripts of the state legislation of the canton of Zurich called the Kantonsrat and find the funniest politician. How? In the transcripts there is the note "(Heiterkeit)" which is a really not often used word for amusement, when several politicians are laughing.  

## Details

I will use a lot of regex and  try to find the woman or man who gets the most laughs. Additionally I want to see if there are certain sessions of the parliament that where particularly funny. 

As an extra I would like to practice new techniques from the algorithms sessions. Will I be able to predict the party of a politician by just looking at the text? 

**Possible headline(s):** 
He/She gets the laughs from poltiicians – but why?

**Data set(s):** 
https://github.com/pasiegrist/Datastudio/tree/master/Code/05-funny_politician
**Code repository:** 
https://github.com/pasiegrist/Datastudio/tree/master/Code/05-funny_politician
**Possible problems/fears/questions:** 

- Regex limitations.
- Does anybody have a good idea how to graph it?

## Work so far

I have scraped the transcripts and tried to figure out how I can get the info out with regex. And as I don't have any graphs I share my core regex command I have so far with you:

politicians = re.split(r"([\w-]* \w* [(]\w*, [\w\. -]*[)])[:,]*[\w\(\)\s]*:|(Ratsv*i*z*e*präsident[in]* \w* \w*):|(Regierungsr[aä]*t[in]* \w* \w*):",text.replace("-", ""))

## Checklist

This checklist must be completed before you submit your draft.

- [x] I have already spent time with my data set, opening it, exploring it, etc
- [ ] I have created a "DIARY.md" file to save links and list all of the terrible, no good problems I come across
- [x] My issue links to my data set(s)
- [x] My issue links to my code repository
- [x] My issue explains what I'd like to explore in the data set
- [ ] My issue includes images - either inspiration or what I've done so far

**Comment by sarahslo** [comment]
as you are doing the analysis, can you figure out if there is a certain topic or legislation that they are discussing? wondering if you can categorize it one step further so those of us who are not familiar with the politicians will be able to relate to what they are talking about.

or are there more laughs at certain times of day..?

**Comment by pasiegrist** [comment]
# Final

Sure, laughter is no prove for humour. But then again, it is one way of measuring it. In transcripts of the state legislation of the canton of Zurich called the Kantonsrat there is the note «(Heiterkeit)», which is rarely used word for amusement, when several politicians are laughing. I have analyzed all the transripts for the last term and found Hans-Peter Amrein of the right-wing SVP to be the guy that was connected the most to «Heiterkeit» followed by the left-wing unionist Markus Bischoff. But see for yourself: https://pasiegrist.github.io/funny

**Headline:** 

When Politicians Laugh

**Published website version:**
https://pasiegrist.github.io/funny

**Code repository:**
https://github.com/pasiegrist/Datastudio/tree/master/Code/05-funny_politician

**Final data set(s):** 
https://github.com/pasiegrist/Datastudio/tree/master/Code/05-funny_politician

## What did you find to be the most difficult part of this project?

I had a hard time figuring out, how I can make an interactive chart that shows the text.
Additionally, it was really hard to work with the PDFs and the text. But I regexed my way through.

## Are you satisfied with what you produced? Is there anything you would like to change or improve?

I wouldn't say I am satisfied. But I have the project at a level, where my serious reporting could start.

## Checklist

- [x] I have included my visuals
- [ ] I have posted my project to my project website
- [x] I have been updating my DIARY.md with details about my process
- [x] I have uploaded/updated any Jupyter Notebooks or other datasets into my code repository
