### ISSUE TITLE
The fat cats of Brooklyn [project]

### ISSUE THREAD

**Issue by ElisaHarlan** [jsoma/data-studio-projects#29]
Please complete all of the following sections, or a robot will spookily dance around your issue! A completed version of this template can be found at https://github.com/jsoma/data-studio-projects/issues/1

# Update

## Summary
In only 10 months in 2015, there were over 1500 consumer complaints out of 3688 cases made to the Food Safety and Inspection division that contain the words "cat" or "cats." In those cases, cats were seen in food shops, delis and restaurants making their business or just straying around. Most of the times cats were seen in the basement or the mainfloor of the buildings. Interestingly, in around 150 cases, even dogs AND cats were in the food location. 

## Details

**Possible headline(s):** 
Brooklyn's restaurants have a cat problem

**Data set(s):** 
files from inspection: https://www.muckrock.com/foi/new-york-16/bodega-cat-complaints-29199/#file-110233
--> Consumer Complaints to the Food Safety and Inspection division made from Jan. 1, 2015, to Oct. 26, 2016, that contain the words "cat" or "cats."

**Code repository:** 
https://elisaharlan.github.io/studio-projects/cats/
	
**Possible problems/fears/questions:** 

## Work so far
Created a map with the food inspections that included cats.

![cats](https://user-images.githubusercontent.com/28815568/28440325-c50259f6-6d73-11e7-960b-de61d4164ede.png)

## Checklist

This checklist must be completed before you submit your draft.

- [x] I have already spent time with my data set, opening it, exploring it, etc
- [x] I have created a "DIARY.md" file to save links and list all of the terrible, no good problems I come across
- [x] My issue issue has `[Project]` in the title
- [x] My issue links to my data set(s)
- [x] My issue links to my code repository
- [x] My issue explains what I'd like to explore in the data set
- [x] My issue includes images - either inspiration or what I've done so far
- [ ] I have received two comments of peer feedback on my pitch issue

**Comment by edl2118** [comment]
Wow, I had no idea NYC had a cat problem. Rats I imagined but cats, who would have thought that? I'm curious about the nature of the consumer complaints. What kinds of complaints were most popular and why is there such a big cat problem? Interesting data set!

**Comment by deniseajiri83** [comment]
Very interesting! I think it would be interesting to see: what the most common complaints are, where most of the complaints are happening, and if for example the issue is seasonal.

**Comment by sarahslo** [comment]
This is lovely but I have to tell you something. Cats are a thing in NYC corner groceries aka Bodegas. They are called Bodega cats and they are much revered. http://www.nydailynews.com/new-york/manhattan/claws-don-mess-new-york-bodega-cats-article-1.2845831

:)

I wonder if there is a way for you to have grouped these into different types of complaints and used colors to separate them. Could you have shown us places where there are cat hair, cats & dogs, cats & vermin, cats in basements....etc. Or, is there a way to separate out the type of stores? Delis vs...?

Part of what we are seeing here is a map of where population is. With some simple math you could have made a chart that showed us, how many cat complaints per Manhattan, Queens & Brooklyn. 

Extra points for getting Smushface in a headline.
