### ISSUE TITLE
Worldwide Nuclear Testing, 1945-2006 [Project]

### ISSUE THREAD

**Issue by kcough** [jsoma/data-studio-projects#31]
# Pitch
Using data from the Stockholm International Peace Research Institute’s “Nuclear Explosions, 1945–1998” (PDF) report I've explored nuclear explosions between 1945 and 2006. There are a number of threads to follow in the dataset (looking for help determining which one might interest people most) but I'm thinking of creating a chart looking at

a. how the type of bomb tested has changed over the years, by country
b. how the size of the bomb has changed over the years, by country. 
c. how many tests occurred below/above ground.
d. the ultimate tonnage per nation, grouped by purpose.

## Details

The dataset includes a ton of info: the purpose of the explosion (weapons related, safety, etc), the explosive yield, the type, who did the testing. There are certainly other things that could be done with it.

**Possible headline(s):** 
Still working on this.

**Data set(s):** 
Cleaned files from Jeremy Singer Vine: https://github.com/data-is-plural/nuclear-explosions

Original terrible PDFs: http://www.iaea.org/inis/collection/NCLCollectionStore/_Public/31/060/31060372.pdf

**Code repository:** 
https://github.com/kcough/data-studio-projects/tree/master/code/oklahoma_nuclear
	
**Possible problems/fears/questions:** 
Nailing down the idea and creating a visualization that's clear and doesn't overcomplicate things. Also doing it without mapping (I think this one lends itself to mapping).

## Work so far
![number_test_by_country](https://user-images.githubusercontent.com/22796338/28568674-9e2ce280-7104-11e7-85cc-b01ebebebeac.png)
![sum_explosive_yield](https://user-images.githubusercontent.com/22796338/28568398-9f66452a-7103-11e7-8874-349006cb0876.png)
![yield_change_over_years](https://user-images.githubusercontent.com/22796338/28568404-a2a59344-7103-11e7-941d-68192fa66186.png)
![nuclear](https://user-images.githubusercontent.com/22796338/28523253-872797da-7049-11e7-9997-4caf155b404c.png)
![avg_explosive_yield](https://user-images.githubusercontent.com/22796338/28568381-98f55a32-7103-11e7-9f34-13e21508416f.png)
![avg_yield_explosion_type](https://user-images.githubusercontent.com/22796338/28568386-9a528e9a-7103-11e7-94ef-0c0e21524433.png)
![type_nuclear_test](https://user-images.githubusercontent.com/22796338/28568662-976e880e-7104-11e7-802b-b4c9202ec16e.png)

## Checklist

This checklist must be completed before you submit your draft.

- [x] I have already spent time with my data set, opening it, exploring it, etc
- [x] I have created a "DIARY.md" file to save links and list all of the terrible, no good problems I come across
- [x] My issue issue has `[Project]` in the title
- [x] My issue links to my data set(s)
- [x] My issue links to my code repository
- [x] My issue explains what I'd like to explore in the data set
- [x] My issue includes images - either inspiration or what I've done so far
- [ ] I have received two comments of peer feedback on my pitch issue

**Comment by demetriospogkas** [comment]
That is an interesting project to follow. You'll be certainly having tons of data to analyse, so in terms of visualisation it'd be interesting to see how you choose to present them. Maybe a cool graphic that show how deep underground each explosion was???

**Comment by kcough** [comment]
![yield_change_over_years_edited](https://user-images.githubusercontent.com/22796338/28721882-bd7f0ca8-737f-11e7-832a-b7de048a9482.png)

![number_test_by_country](https://user-images.githubusercontent.com/22796338/28724495-2c134c58-7388-11e7-9c9c-460ad208c0c4.png)

![avg_explosive_yield_edited](https://user-images.githubusercontent.com/22796338/28726381-097c9530-738f-11e7-8265-5c589367739d.png)



![sum_explosive_yield_edited](https://user-images.githubusercontent.com/22796338/28725961-36705f1a-738d-11e7-909e-d99213472ee5.png)


## Headline: Nuclear Weapons Testing Worldwide 1945-2006  


## Published website version: 
https://kcough.github.io/data-studio-projects/nuclear/

## Code repository: 
https://github.com/kcough/data-studio-projects/tree/master/code/oklahoma_nuclear

## Data set(s):
Cleaned files from Jeremy Singer Vine: https://github.com/data-is-plural/nuclear-explosions

## What did you find to be the most difficult part of this project?
Clear and concise headlines. Not being allowed to map things because I had been planning on a map, and I think this data actually does lend itself to one.

## Are you satisfied with what you produced? Is there anything you would like to change or improve?
I think it's eye-catching and am happy with the fonts/color choices, placement of text, etc. which was where I focused my energy this week.

## Any changes in direction or topic?
No, decided to stick with dataset and focus on design-fonts, colors, simplification of information

## Problems/Questions
Headlines! I am terrible at them. Scale-particularly with the "Avg. Explosive Yield in Kilotons" graph. Most average around 200 kilotons, but I want to convey the change over time, so I'm not sure that's important to focus on--but the graph makes it appear as though they're negligible, which isn't the case. Also on the same graph--missing values. I left them in because it seems disingenuous to imply that the data is there when it isn't, but I know that it breaks up the visual and is confusing. Would a text box explaining this be appropriate?

## Checklist
	
- [x] I have included my visuals
- [x] I have added writing about my topic
- [x] I have been updating my DIARY.md with details about my process
- [x] I have uploaded/updated any Jupyter Notebooks or other datasets into my code repository
- [ ] I have received two comments of peer feedback on my project update

**Comment by sarahslo** [comment]
Interesting dataset. There is something very compelling about the smaller bombs chart. I like the way you have presented it. I think what would be useful is to play with the charting forms for the other charts. They are all bar charts, but they express different measures. So change the chart form to reflect that.

You could count the number for each countries using pictographs. Here is a silly example, but you get the idea.
![pictograph-1](https://user-images.githubusercontent.com/659014/29151344-9b2de722-7d4e-11e7-91b8-6eb271ef1f53.png)

You could use graduated circles for the explosive power.

One thing to watch out for, I'm not crazy about the country labels overlapping the data. Find a place to put them that doesn't get in the way of the charts and is consistent. Either at the top of all the bars
<img width="280" alt="screen shot 2017-08-09 at 22 07 50" src="https://user-images.githubusercontent.com/659014/29151460-507444e6-7d4f-11e7-821a-122a902a5361.png">
Or at the bottom, where they are all lined up and easy to see. 
<img width="269" alt="screen shot 2017-08-09 at 22 08 05" src="https://user-images.githubusercontent.com/659014/29151470-6029a160-7d4f-11e7-9139-c6804f345a2b.png">

Nice work, good slicing and dicing of data.
