### ISSUE TITLE
Polling biases [Project]

### ISSUE THREAD

**Issue by marcelpauly** [jsoma/data-studio-projects#32]
# Pitch

## Summary

Four years ago Gregor Aisch (NYT) did a great [analysis of biases in opinion polls](https://www.vis4.net/blog/posts/analyzing-bias-in-election-polls-with-r/) in Germany. He showed how the poll ratings for certain parties differ systematically at some institutes. With the upcoming elections in mind I would like to adopt his basic idea, bring it to Python and use it first of all for analysing the ratings by two young polling institutes. One of them is rumored to back a right-wing populist party. The other one is using a complete new method why I'd like to look into its possible deviation from the other institutes.

In the following chart Gregor plotted all polling ratings for the party CDU by all institutes. He draw a median line and highlighted the ratings by the institute Forschungsgruppe Wahlen to show how they were "overrating" the party most of the times:

![cdu-fgw1](https://user-images.githubusercontent.com/7937281/28532652-705b7a3e-7068-11e7-9fed-0839891f5481.png)

## Details

**Possible headline(s):** This is how biased polling institutes are

**Data set(s):** [poll ratings via _Wahlrecht.de_](http://www.wahlrecht.de/umfragen/index.htm)

**Code repository:** https://github.com/marcelpauly/data-studio-projects/tree/master/code/polling_bias
  
**Possible problems/fears/questions:** -

## Work so far

I gathered the data and unpivoted it in Python. I created **first** for each institute the monthly mean for each party and **second** for each party the monthly median (of all institutes). Next step is to compare them.

I also plotted all the polling data (dots) vs. the party's medians (lines) to get a first overview:

![overview](https://user-images.githubusercontent.com/7937281/28532664-784eae14-7068-11e7-92d4-c9c5eb30a287.png)

## Checklist

This checklist must be completed before you submit your draft.

- [x] I have already spent time with my data set, opening it, exploring it, etc
- [x] I have created a "DIARY.md" file to save links and list all of the terrible, no good problems I come across
- [x] My issue issue has `[Project]` in the title
- [x] My issue links to my data set(s)
- [x] My issue links to my code repository
- [x] My issue explains what I'd like to explore in the data set
- [x] My issue includes images - either inspiration or what I've done so far
- [ ] I have received two comments of peer feedback on my pitch issue

**Comment by marcelpauly** [comment]
# Update

## Content

I explored the polling data by all institutes and found out that the deviations between them decreased over the past years. And I researched into one specific case:

![insa](https://user-images.githubusercontent.com/7937281/28646032-a65d8656-722d-11e7-9758-aaedef5af60d.png)

I wrote an [article about that](https://marcelpauly.github.io/data-studio-projects/polling_bias/) and updated my [Jupyter Notebook](https://github.com/marcelpauly/data-studio-projects/blob/master/code/polling_bias/Polling%20Bias.ipynb).

## Any changes in direction or topic?

Yes, I'm not longer looking for polling biases in generell but I'm focusing on only one institute and it's bias in favor of a right-wing populist party and to the disadvantage of one of the ruling parties.

## Problems/Questions

–

## Checklist

- [x] I have included my visuals
- [x] I have added writing about my topic
- [x] I have been updating my DIARY.md with details about my process
- [x] I have uploaded/updated any Jupyter Notebooks or other datasets into my code repository
- [ ] I have received two comments of peer feedback on my project update

**Comment by marcelpauly** [comment]
# Update

## Content

I updated the data (it now includes all the data for July 2017) and did some small refinements in the code and at the graph.

![insa](https://user-images.githubusercontent.com/7937281/28795375-aabd8f4c-7607-11e7-9ce9-89cd9db16ac0.png)

## Any changes in direction or topic?

Nope.

## Problems/Questions

–

## Checklist
	
- [x] I have included my visuals
- [x] I have added writing about my topic
- [x] I have been updating my DIARY.md with details about my process
- [x] I have uploaded/updated any Jupyter Notebooks or other datasets into my code repository
- [ ] I have received two comments of peer feedback on my project update

**Comment by Ediegram** [comment]
This is interesting but the chart feels busy with all of the annotations, which are difficult to follow without any introduction. Even when a chart runs with a story it is important that it can be understood on its own. 
How much do these deviations matter? they seem like they would be swallowed up by a typical margin of error ..?

**Comment by marcelpauly** [comment]
Thank you very much for your feedback! The chart is supposed to tell both sides of the story how the ratings developed and what happened in Germany and at the INSA institute. Only by showing both these aspects you can see that there might be a connection. I had some terrible drafts with even more "business" and "noise". ;) The thing above is the best I came up with, I'm really looking forward to suggestions how to improve it.

About the deviations: This is a very important point I was going to make in the [article](https://marcelpauly.github.io/data-studio-projects/polling_bias/) because INSA's margin of error is ±2.5 ppt (which means that the margin for small parties like the AfD is even smaller). So the deviations for CDU/CSU and AfD (especially since mid 2015) are extremly unusual and INSA is the only German institute with such high deviations. I guess I have to make this clearer. I'll work on a seconds chart to clarify that and put it into perspective.

**Comment by marcelpauly** [comment]
# Final

## Project visuals/text

![insa](https://user-images.githubusercontent.com/7937281/28948211-3994fc06-7882-11e7-9f37-d525a7cd16c3.png)

I added another visual to show that INSA deviates from the median more often than statistically expectable:

![moe](https://user-images.githubusercontent.com/7937281/28948381-54fda514-7883-11e7-88b5-4eff07598763.png)

## Details

**Headline:** Are INSA's polling numbers politically intended?

**Published website version:** https://marcelpauly.github.io/data-studio-projects/polling_bias/

**Code repository:** https://github.com/marcelpauly/data-studio-projects/tree/master/code/polling_bias

**Final data set(s):**  [poll ratings via _Wahlrecht.de_](http://www.wahlrecht.de/umfragen/index.htm) ([CSV](https://github.com/marcelpauly/data-studio-projects/blob/master/code/polling_bias/polling_data.csv))

## What did you find to be the most difficult part of this project?

This visuals.

## Are you satisfied with what you produced? Is there anything you would like to change or improve?

It's a complex topic and I'm not sure if I managed to make the charts comprehensible enough.

## Checklist

- [x] I have included my visuals
- [x] I have posted my project to my project website
- [x] I have been updating my DIARY.md with details about my process
- [x] I have uploaded/updated any Jupyter Notebooks or other datasets into my code repository
