### ISSUE TITLE
Higher earthquake risk for eastern US[Project]

### ISSUE THREAD

**Issue by chrgavalas** [jsoma/data-studio-projects#33]
Please complete all of the following sections, or a robot will spookily dance around your issue! A completed version of this template can be found at https://github.com/jsoma/data-studio-projects/issues/1

# Pitch
According to the US Geological Survey, earthquakes are more likely to occur now in the central and eastern part of the US compared with a few years back. As recently as late June of this year, an earthquake in Augusta, Georgia was "widely felt" which went against my notion that earthquakes in the east side of the US rarely happen. If the data confirms this, I'd like to show to evolution of the phenomenon over the years and even maybe define the areas that are most likely to get hit. Also, I'd need to include scientific explanation as to why this has only recently started happening. 

## Summary
Are earthquakes in central and eastern US more likely to happen now than in the past? The answer is likely yes and that’s why: According to the USGS, it comes as a result of **induced seismicity** caused by deep underground disposal of waste water resulting from oil and gas recovery. The findings from the US Geological Survey analyzing the current status, development opportunities and priorities for the next decade (2017-2027) show that since 2009 there has been a sharp increase in the earthquakes of a magnitude of 3.0 or greater in the eastern part of the US. The number reached a peak in 2015. 

## Details
The probability of induced seismicity getting injected in the ground has led the ANSS to ask for additional resources of at least $1.5 million per year (on top of already allocated $2.5 million) that will be used to support operations of the existing stations, to integrate data from these stations into existing data analysis procedures and to further improve strong-motion station average. The goal is to increase understanding of seismic danger and societal risk in the eastern half of the US.  In 2014, the US Geological Survey had released a report saying "the eastern US has the potential for larger and more damaging earthquakes than considered in previous maps and assessments". It seems as if scientists had already learned a lot from a 5.8 magnitude quake that rattled the Mid-Atlantic and Northeast in 2011, as it was felt by tens of thousands of people. 

**Possible headline(s):** 
Did you feel it? Vibrations travel increasingly eastward lately 

**Data set(s):** 
[Earthquakes-US.pdf](https://github.com/jsoma/data-studio-projects/files/1170742/Earthquakes-US.pdf)

**Code repository:** 
https://github.com/chrgavalas/data-projects/tree/master/code/project4

**Possible problems/fears/questions:** 
I just hope I will be given the data from the US Geological Survey that will confirm their own findings! It's not like I expect something else to happen but I definitely need to get my hands on the actual database. A large portion of the report they put together is describing exactly the reasons why this phenomenon has taken place while providing numbers that are showing this. My plan B just in case the data is not quite what I expect, is to create my own datasets based on the very numbers these infographics present. 

## Work so far
Created a list with the top ten earthquakes in the east coast over the years and plotted it. 
![firstpic](https://user-images.githubusercontent.com/30135399/28538276-aff068fe-707b-11e7-872f-7e8bbc47c72b.png)

Imported the shape file of the US states we use for exercise in class with a view of possibly just plotting the earthquakes when I find a proper dataset. I have e-mailed USGS asking for access to their documents. If I get this access I am pretty confident the story will be valid because the survey I read as well as numerous reports confirm that in the last 2-3 years there have been more earthquakes in the eastern part of the US. 

## Checklist

This checklist must be completed before you submit your draft.

- [x] I have already spent time with my data set, opening it, exploring it, etc
- [x] I have created a "DIARY.md" file to save links and list all of the terrible, no good problems I come across
- [x] My issue issue has `[Project]` in the title
- [x] My issue links to my data set(s)
- [x] My issue links to my code repository
- [x] My issue explains what I'd like to explore in the data set
- [x] My issue includes images - either inspiration or what I've done so far
- [ ] I have received two comments of peer feedback on my pitch issue

**Comment by demetriospogkas** [comment]
Interesting topic Christos. It would be really interesting to see like a timeline of the seismic activity, if not on a map, maybe on a graph that show the amount of earthquakes per year or decade, so we see which areas are being affected more.

**Comment by chrgavalas** [comment]
# Update
	
## Content

Have been analyzing some of the earthquakes data I collected from USGS. Saw the trend in the data that proves earthquakes are more likely now in the eastern and central states. 
Earthquakes-US.pdf
https://earthquake.usgs.gov/earthquakes/search/#%7B
https://github.com/chrgavalas/data-projects/tree/master/code/project4


## Any changes in direction or topic?

I think Oklahoma is the reason why earthquakes in central/eastern US are significantly up. Have been trying to find out why and for this I have been doing a lot of reading. Most reports say it's because of wastewater injection from oil and gas production! But there are also some other reports contesting that. It'd be a good spin/chapter in my story, though. 
https://www.seismosoc.org/news/ssa-press-releases/srl-2017-model-predicts-significant-chance-earthquake-damage-central-eastern-u-s/

## Problems/Questions
I don't really know how to programmatically/graphically define what states will be central, what will be west or midwest. And the USGS system doesn't let me manually type which states I want. So I have been inserting my own lan/lot calculations hoping that my picks are truthful to the story I am trying to form. In terms of the findings, it looks as if my guess is right. 

## Checklist
	
- [ ] I have included my visuals
- [x] I have added writing about my topic
- [x] I have been updating my DIARY.md with details about my process
- [x] I have uploaded/updated any Jupyter Notebooks or other datasets into my code repository
- [ ] I have received two comments of peer feedback on my project update

**Comment by chrgavalas** [comment]
# Final

## Project visuals/text

Why are earthquakes of a magnitude 3.0 and above in the central and eastern US more frequent now than they have ever been?
On the morning of June 20, 2017 an earthquake hit the City of Augusta in Georgia. According to the U.S. Geological Survey, it was centered 3.27 miles (5.26 km) southwest of Augusta with a 3.2 magnitude. Local residents reported the earthquake displaced furniture in homes and triggered security alarms at homes and businesses while Mayor Hardie Davis issued a statement urging residents to be mindful of falling debris and to take refuge under a strong structure if the ground begins to shake. It has so far been Georgia’s largest earthquake this year.
<img width="250" alt="earth-georgia" src="https://user-images.githubusercontent.com/30135399/28950778-a8aefdbe-7894-11e7-8de0-436dfe36bc1f.png">
And for anyone who thought earthquakes were a West Coast thing, the 2011 5.8 magnitude quake centered in rural Virginia was an eye opener. The tremors were felt as far away as Toronto, led to the evacuation of government buildings in Washington, D.C., suspension of takeoffs and landings at airports across the Northeast; and the automatic shutdown of two nuclear reactors in Virginia near the epicenter, according to reports.
<img width="300" alt="virginia" src="https://user-images.githubusercontent.com/30135399/28950791-bd667b38-7894-11e7-94dc-3309320fdc2b.png">
It was among the major earthquakes on the East Coast of all times, with the second largest being an estimated 7.3 magnitude temblor that struck Charleston, S.C., in 1886.
![large-quakes](https://user-images.githubusercontent.com/30135399/28950804-cf559e5a-7894-11e7-9029-75375a046909.png)
But according to USGS, the number of earthquakes in the central and eastern United States has dramatically increased over the past decade. For that reason it has asked for additional federal resources of at least $1.5 million per year (on top of already allocated $2.5 million) that will be used to support operations of the existing stations, to integrate data from these stations into existing data analysis procedures and to further improve strong-motion station average. The goal is to increase understanding of seismic danger and societal risk in the eastern half of the US. It is indicative that the number of earthquakes has increased by 967% during the current decade so far compared with the previous one.
![increase-quakes](https://user-images.githubusercontent.com/30135399/28950813-e66f6dd2-7894-11e7-8208-db6e4c5c82cd.png)
However when the US map showing the total number of earthquakes in the central and eastern part from 1970 to 2009 is placed side by side with the very same map when it only shows the earthquakes in the current decade, this increase can only be considered as a very well hidden mystery.
![red-dots](https://user-images.githubusercontent.com/30135399/28950823-f6d7cb10-7894-11e7-8c2a-9cfeb54a8ef2.png)
![green-dots](https://user-images.githubusercontent.com/30135399/28950824-fb381034-7894-11e7-9736-d67c3045e39e.png)
What is missing in the larger scaled map in the decisive influence of Oklahoma in the dramatic surge. But the more we zoom the clearer the picture gets.
![oklahoma-dots](https://user-images.githubusercontent.com/30135399/28950830-10fc5b1e-7895-11e7-8b76-9ef286eb414f.png)
Oklahoma tops the list of US central states with the most earthquakes in recent years. It is indicative that before 2009, there were, on average, two earthquakes a year in Oklahoma that were magnitude 3 or greater. Last year, there were 907.
![oklahoma-first](https://user-images.githubusercontent.com/30135399/28950844-227c0aec-7895-11e7-94aa-601064740d13.png)
What’s more astonishing is that most of them are man-made, being triggered by the biggest and most important industry in the state: oil and gas production, not from fracking though. And additionally, despite the recent drop in earthquake rates (in 2016), Oklahoma and southern Kansas still face a significant risk of induced earthquake damage in 2017, according to the USGS report published on March 1st in the journal Seismological Research Letters.
So why do humans cause this? According to USGS, wastewater disposal is the primary reason. Most wastewater currently disposed of across the nation is generated and produced in the process of oil and gas extraction. But while gas and oil are collected in tanks for sale, the water is too salty to be recycled or used and that’s why it’s considered waste and has to go back in the ground.
However, getting rid of the water means sending it down a disposal well that’s drilled deep below the freshwater aquifers -- to prevent their contamination -- and the zone where it came from.
And while the vast majority of earthquakes cause little or no damage, the large volume which is being produced means more of the bigger ones are now likely to happen. However, national news outlets have recently reported that the frequency of such earthquakes in Oklahoma has dropped as the state imposed new restrictions on the injection of wastewater into underground disposal wells.
![oklahoma-disposal-well](https://user-images.githubusercontent.com/30135399/28950865-41279470-7895-11e7-990b-4660c871b753.jpg)
That's not to say that residents in the eastern part of the country should be rest assured. Although earthquakes are less frequent in their turf than they are in the west, they're typically felt over a broader area, according to the U.S. Geological Survey. Since 1970, the most often counted <b>depth</b> for vibrations of 3.0 magnitude or above is 5.0 km which makes sure they are more intensely felt. 
![earthquake-depth](https://user-images.githubusercontent.com/30135399/28950874-511aec60-7895-11e7-82cf-31d0355ecbcb.png)

## Details

**Headline:** 
Did you feel it? Vibrations travel a lot eastward lately

**Published website version:**
https://chrgavalas.github.io/data-projects/US-Earthquakes/

**Code repository:**
https://github.com/chrgavalas/data-projects/tree/master/code/project4

**Final data set(s):** 
https://earthquake.usgs.gov/earthquakes/search/

## What did you find to be the most difficult part of this project?
Finding the next crop of data --for example damages caused by earthquakes-- to take my story one step further. 

## Are you satisfied with what you produced? Is there anything you would like to change or improve?
Maybe I would just like my visuals to also be a bit better. They are certainly more compelling than those of my first project but still not at the level I would have wanted. 

## Checklist

- [x] I have included my visuals
- [ ] I have posted my project to my project website
- [x] I have been updating my DIARY.md with details about my process
- [x] I have uploaded/updated any Jupyter Notebooks or other datasets into my code repository

**Comment by sarahslo** [comment]
Hi there. So, I want to be able to look at these data and figure out the story that you are telling. I find myself reading the text to understand it. You have put a lot of care into the style of these charts, and that shows. But I would shift you efforts into the substance, and keep style very simple to start with. We'll talk about this in class, but often you need to 'remove to improve.'

With earthquakes, it's definitely a 'where' story so I think it was good you tried the maps and worked to figure out what the pattern was. It's helpful first to understand where and why they happen, earthquakes occur along geological fault lines. More than just plotting the dots, you can scale the circles to represent the magnitude.

Here are a few examples to consider, if you ever decide to map earthquakes.
![maps_symbol6](https://user-images.githubusercontent.com/659014/29148211-f7055a04-7d39-11e7-870d-b7e3a7da33c8.png)
![graduated-symbols-map](https://user-images.githubusercontent.com/659014/29148210-f700c7d2-7d39-11e7-9335-8f0a08387d8e.jpg)
![article-2696421-6r93nh1pa-hsk1-296_964x782](https://user-images.githubusercontent.com/659014/29148209-f6fcfaf8-7d39-11e7-9f2e-ff79508ca3a9.jpg)

This is a good start. It's very hard to find a story in data when you are just beginning to work with it, so you have done some excellent reaching.
