### ISSUE TITLE
Facts about Plane Crashes [Project]

### ISSUE THREAD

**Issue by shellyscheng** [jsoma/data-studio-projects#35]
Please complete all of the following sections, or a robot will spookily dance around your issue! A completed version of this template can be found at https://github.com/jsoma/data-studio-projects/issues/1

# Pitch

## Summary
I found an interesting dataset about plane crashes since 1993. 

Potential topics for exploration:
1. What are most common causes of crashes?
2. Which stage did it happen most often?
3. Which airline/country is most dangers?

## Details

**Possible headline(s):** 
Half of plane crashes were caused by human errors.

**Data set(s):** 
https://docs.google.com/spreadsheets/d/1OvDq4_BtbR6nSnnHnjD5hVC3HQ-ulZPGbo0RDGbzM3Q/edit#gid=1

**Code repository:** 
	
**Possible problems/fears/questions:** 

## Checklist

This checklist must be completed before you submit your draft.

- [x] I have already spent time with my data set, opening it, exploring it, etc
- [ ] I have created a "DIARY.md" file to save links and list all of the terrible, no good problems I come across
- [x] My issue has `[Project]` in the title
- [x] My issue links to my data set(s)
- [ ] My issue links to my code repository
- [ ] My issue explains what I'd like to explore in the data set
- [ ] My issue includes images - either inspiration or what I've done so far
- [ ] I have received two comments of peer feedback on my pitch issue

**Comment by chrgavalas** [comment]
Great idea and will touch a lot of people. Would like to see a not so generic headline though! My hunch is plane crashes have decreased is the last decade and they keep becoming fewer. Does technology advances help towards this direction?

**Comment by qdinhbui2** [comment]
I think the question you posed are ok. But something you said seems before seems more interesting to me: 
`Which stage did it happen most often?`

**Comment by qdinhbui2** [comment]
Which got me thinking -- which part of the flight is the most dangerous? As in, take off? landing? or general flying? That seems interesting to me.
