### ISSUE TITLE
The World's most Important 6-sec Drum Loop [Project]

### ISSUE THREAD

**Issue by 2109Sot** [jsoma/data-studio-projects#36]
Please complete all of the following sections, or a robot will spookily dance around your issue! A completed version of this template can be found at https://github.com/jsoma/data-studio-projects/issues/1

# Pitch

## Summary

https://www.youtube.com/watch?v=5SaFTm2bcac&t=754s 

The video above explains the story behind the most sampled song in modern music. Following the video's narrative and scraping the _Amen Break's_  [whosampled.com page](http://www.whosampled.com/The-Winstons/Amen,-Brother/sampled/) I want to find the artists who used the song, when they did, and what kind of music they make. 

## Details

**Possible headline(s):** 

Amen Brother: Breaking down the world's most important drum-break. 

**Data set(s):** 

http://www.whosampled.com/The-Winstons/Amen,-Brother/sampled/

**Code repository:** 

https://github.com/2109Sot/studio-projects/tree/master/code/who_sampled
	
**Possible problems/fears/questions:** 

Finding the base of each artist would be a good addition to my story, especially
when considering the birthplaces of the two major sub-cultures the Amen Break gave
birth to, that is hip-hop in the States and drum-n-base in Europe (The UK). 

## Work so far

<img width="717" alt="screen shot 2017-07-24 at 17 31 07" src="https://user-images.githubusercontent.com/28814400/28545708-0f3875ee-7096-11e7-8e0b-694133b4dffa.png">

<img width="519" alt="screen shot 2017-07-24 at 17 32 36" src="https://user-images.githubusercontent.com/28814400/28545751-2ea7f8e6-7096-11e7-92cb-0c9f98dd9cfa.png">

<img width="818" alt="screen shot 2017-07-24 at 17 33 43" src="https://user-images.githubusercontent.com/28814400/28545788-51fd84f0-7096-11e7-9b23-57bc68fe654a.png">

## Checklist

This checklist must be completed before you submit your draft.

- [x] I have already spent time with my data set, opening it, exploring it, etc
- [x] I have created a "DIARY.md" file to save links and list all of the terrible, no good problems I come across
- [x] My issue issue has `[Project]` in the title
- [x] My issue links to my data set(s)
- [x] My issue links to my code repository
- [x] My issue explains what I'd like to explore in the data set
- [x] My issue includes images - either inspiration or what I've done so far
- [ ] I have received two comments of peer feedback on my pitch issue

**Comment by 2109Sot** [comment]
# Update
	
## Content

Spent some time working on my visualizations:

**Genres**:
![who_sampled_genres](https://user-images.githubusercontent.com/28814400/28761665-4cbb51ec-757e-11e7-9458-043879798a11.png)

**Years**:
![who_sampled_years](https://user-images.githubusercontent.com/28814400/28761675-616527da-757e-11e7-8b4d-74b8f35d7ba3.png)

**Artists (hip-hop / electronic)**:

![who_sampled_graph_zoom_1-01](https://user-images.githubusercontent.com/28814400/28761690-77ce75da-757e-11e7-9530-5a9096fd6017.png)

![who_sampled_graph_zoom_2-02](https://user-images.githubusercontent.com/28814400/28761692-7c753fba-757e-11e7-8d2f-a950c61b65e9.png)

^ I am uploading two different versions of the same graph here, because I would like to know what my peers and instructors think of both. Which one do you like better?

## Any changes in direction or topic?

Not really, apart from the fact that I will be focusing more on the juxtaposition between electronic and hip-hop music, and  not on all the genres that used the sample. The results are pretty interesting already as they contradict my initial assumption that hip-hop artists would have used the sample more that any other.
	
## Problems/Questions

Visualising the 'top users' of the sample is quite problematic due to the lack of space mainly. Apart from that I would like to somehow illustrate the popularity of each track (according to the ranking of whosampled.com). However, whosampled.com counts the popularity of the track and not the artsit. So how popular is an artists who has used the sample more than x times? Any suggestions on that matter?
	
## Checklist
	
- [x] I have included my visuals
- [ ] I have added writing about my topic
- [x] I have been updating my DIARY.md with details about my process
- [x] I have uploaded/updated any Jupyter Notebooks or other datasets into my code repository
- [ ] I have received two comments of peer feedback on my project update

**Comment by chrgavalas** [comment]
Hey Sotiris! This is a very thoughtful analysis of a topic few people know about, so it should be directed to a very targeted/specific audience. I believe it would be quite interesting for hip-hop lovers as it implies that it is the electronic genre that mostly samples Amen Brother as opposed to the general belief that hip-hop musicians are doing so. How about a headline like: "You think mostly hip-hop artists use the Amen Brother? You are wrong. Electronic artists do". As for the rest of the analysis (year when the piece was used)  I think it serves as a great supporting squad info and should be placed further down in your story.

**Comment by Ediegram** [comment]
As we discussed Friday, I think you are off to a good start. Feel free to slack a new draft if you want feedback before Friday.

**Comment by 2109Sot** [comment]
# Final

## Project visuals/text

![who_sampled_years](https://user-images.githubusercontent.com/28814400/28954986-e1b24d3e-78b0-11e7-8fc9-961bdbd7e827.png)

![who_sampled_graph_zoom-02](https://user-images.githubusercontent.com/28814400/28954988-eacd9d60-78b0-11e7-83ad-b7fec2b7fb35.png)

![who_sampled_genres](https://user-images.githubusercontent.com/28814400/28954991-effc69f6-78b0-11e7-866e-13d4b7de17c6.png)

## Details

**Headline:** 

BREAKING DOWN THE WORLD'S MOST SAMPLED DRUM LOOP: You are wrong if you think that hip-hop artists have used it the most

**Published website version:**

https://2109sot.github.io/studio-projects/who_sampled/

**Code repository:**

https://github.com/2109Sot/studio-projects/tree/master/code/who_sampled

**Final data set(s):** 

http://www.whosampled.com/The-Winstons/Amen,-Brother/sampled/

## What did you find to be the most difficult part of this project?

The scraping of the site was quite easy. Visualising my results was rather a challenge for me.

## Are you satisfied with what you produced? Is there anything you would like to change or improve?

Sure, I like the final outcome. However, I would like to do a more in-depth analysis of the - at least top - artists. Answering the question "what makes the Amen Break so appealing,"  would be great too, even though data cannot(?) answer such questions.

## Checklist

- [x] I have included my visuals
- [x] I have posted my project to my project website
- [x] I have been updating my DIARY.md with details about my process
- [x] I have uploaded/updated any Jupyter Notebooks or other datasets into my code repository
