### ISSUE TITLE
Africans are running away [Project]

### ISSUE THREAD

**Issue by MarinaBraem** [jsoma/data-studio-projects#37]
Please complete all of the following sections, or a robot will spookily dance around your issue! A completed version of this template can be found at https://github.com/jsoma/data-studio-projects/issues/1

# Pitch
## Summary
As a next step I want to extend my dataset and to visualize the popularity of the largest marathons of the world (**WMM** | World Major Marathons) according to their development history. This includes these marathons: **Boston** (since 1897), **New York** (since 1970), **Berlin** (since 1974), **Chicago** (since 1977), **London** (since 1981), **Tokio** (since 2007). 

I would like to tell the story of the growing popularity of marathons in a worldwide context (based on growing timelines – without mapping). An extended database would complete as well my first approach/pitch about the women (s. my draft below). I checked my data quickly with these simple drafts to proof, if the message will fits with the data/approach together. 

**My first drafts | idea check**
![running_nations marathon_p2_mbraem](https://user-images.githubusercontent.com/28846818/28555990-3ae26034-70d1-11e7-899c-1d79e785efca.png)

## Details

**Possible headline(s):** 
– Running Nations
– The Popularity of Marathons
– The Evolution of Marathons

**Data set(s):** 
First checks and orientation based on Wikipedia 
(incomplete tables and datasets, only NY Marathon is complete right now): 
**Boston:** https://de.wikipedia.org/wiki/Boston-Marathon
**New York:** https://de.wikipedia.org/wiki/New-York-City-Marathon
**Berlin:** https://de.wikipedia.org/wiki/Berlin-Marathon
**Chicago:** https://de.wikipedia.org/wiki/Chicago-Marathon
**Tokio:** https://de.wikipedia.org/wiki/Tokio-Marathon

**Marathonstatistics** (Data overview only for Boston, New York, Berlin, Chicago):
https://marathonstatistik.com/home.html

**Code repository:** 
https://github.com/MarinaBraem/New-Data-Studio/tree/master/Code/Project2_Marathon_Evolutions
	
**Possible problems/fears/questions:** 
How will be the best proceed to complete my dataset? 
How can I scrape all these results-pages?

## Work so far
First checks and an overview. 
Research for the database and first drafts. 

## Checklist

This checklist must be completed before you submit your draft.

- [X] I have already spent time with my data set, opening it, exploring it, etc
- [X] I have created a "DIARY.md" file to save links and list all of the terrible, no good problems I come across
- [X] My issue issue has `[Project]` in the title
- [X] My issue links to my data set(s)
- [X] My issue links to my code repository
- [X] My issue explains what I'd like to explore in the data set
- [X] My issue includes images - either inspiration or what I've done so far
- [ ] I have received two comments of peer feedback on my pitch issue

**Comment by MarinaBraem** [comment]
# Update
> I changed my point of research to the top runners, because it told me a very interesting story about how the marathon culture changed by years in US and Europe and  became dominated by Africa.  Even if the most important marathons for sponsors, top runners and running enthusiasts are still taken their place in these classic marathon continents.

## Content – first results
> Visual analysis about the winner DNA. 
Recognizing the key in which point the diversity get lost.  

![white men can t jump](https://user-images.githubusercontent.com/28846818/28992778-b3b83dda-7973-11e7-87fa-b8c5e91109f5.png)

## Proceed & method | 1 | Dataset-overview
> After expanding my dataset with all 6 marathons: 
Short overview with all countries and winner per each marathon (men & women) as a sum. 
<img width="1242" alt="white men can t jump2-04" src="https://user-images.githubusercontent.com/28846818/28992936-bdeb6b84-7977-11e7-9928-8ab7db00cdba.png">

## Proceed & method | 2 | Sketch, Message, sort data, visualization
> Thinking about in which way would it be possible to show the changing transition from the diversity part to monoculture
 
![sketch_idea_2](https://user-images.githubusercontent.com/28846818/28993019-aa581250-7979-11e7-8a2c-9c62fdeb1415.jpg)
![sketch_idea_1](https://user-images.githubusercontent.com/28846818/28993020-abbb522e-7979-11e7-9616-3c23b9524637.jpg)

## Proceed & method | 3 | Code example
> Thinking about a simple protoype to sort the data

<img width="1089" alt="chart_example_1" src="https://user-images.githubusercontent.com/28846818/28993041-139dc7c8-797a-11e7-95d2-91c8ecbeaafd.png">
<img width="1096" alt="chart_example_3" src="https://user-images.githubusercontent.com/28846818/28993043-16543754-797a-11e7-8c3c-0b9befb0e744.png">

## Proceed & method | 4 | Reduction
> Thinking about the reduction to show a clear message. 
I decided to organize all countries by continents. With the new color codes I could prepare every marathon:

<img width="403" alt="farbcodierung_kontinente" src="https://user-images.githubusercontent.com/28846818/28993051-49f00c78-797a-11e7-88b3-3e5246f56011.png">

As an example "CHICAGO": 
<img width="1108" alt="notebook_code_1" src="https://user-images.githubusercontent.com/28846818/28993052-4d70b99c-797a-11e7-911b-02963438ab39.png">

Or "BERLIN"
<img width="1107" alt="notebook_code_2" src="https://user-images.githubusercontent.com/28846818/28993150-3ecb07dc-797d-11e7-85f2-f108a0334000.png">


## Proceed & method | 5 | Exploring in Illustrator
> Thinking about a way how support the message:
![white men can t jump_analsis_2_finish](https://user-images.githubusercontent.com/28846818/28993068-87c638ec-797a-11e7-8e31-5f7d653ad84b.png)
<img width="917" alt="illustrator_all_marathons_4" src="https://user-images.githubusercontent.com/28846818/28993158-7f53b16e-797d-11e7-9410-3130568286fd.png">

	
## Proceed further
> I wanna prepare this analysis for an article and collecting the mean graphic with other important facts I researched in the meantime about this changing paradigma in the marathon culture, based on this article, where I was involved. I would like to think about, how to tell this story in an other storytelling way: **There are no more pioneers in marathon & no more identification** | Tages-Anzeiger
http://www.tagesanzeiger.ch/sport/leichtathletik/Die-Pioniere-im-Marathon-sterben-aus/story/11554464

**Git Repository**
https://github.com/MarinaBraem/New-Data-Studio/tree/master/Code/Project2_Marathon_Nations

	
## Checklist
	
- [X] I have included my visuals
- [X] I have added writing about my topic
- [X] I have been updating my DIARY.md with details about my process
- [X] I have uploaded/updated any Jupyter Notebooks or other datasets into my code repository
- [X] I have received two comments of peer feedback on my project update

**Comment by sarahslo** [comment]
i love that you have documented your process here. this is close to being really excellent, except -- you threw me off by making africa the same black as the background. the data literally disappear and if i had not looked closer at the headline and then the key i would not have understood.

make africa another color! and make your color key bigger and more legible so we can see it better.
two small things.
nice work

**Comment by MarinaBraem** [comment]
Thank you so much for this feedback, sarah! I agree absolutely! This was a way to much in experimenting around with my draft... now I have to clarify my idea, like you say. I will do this in my next step! Thank you a lot.
