### ISSUE TITLE
[Project] FBI's Supplementary Homicide Report

### ISSUE THREAD

**Issue by cathrinesot** [jsoma/data-studio-projects#38]
# Pitch

## Summary

I want to write an article about homicides in the US, bases on ndividual cases or groups of cases that have been reported to the FBI through the Supplemental Homicide Report. My focus will be on the relationship to the victim, the age of the offender and the weapon used.

## Details

**Possible headline(s):** 

Who is more likely to kill you and with what weapon according to your relationship. 

**Data set(s):** 

The Murder Accountability Project is a database of homicides in the United States. 
http://www.murderdata.org/p/data-docs.html
![screen shot 2017-07-24 at 5 56 21 pm](https://user-images.githubusercontent.com/28814380/28546639-732afca4-7099-11e7-9fff-a0b722d4d10b.png)

This dataset includes murders from the FBI's Supplementary Homicide Report from 1976 - 2015 and Freedom of Information Act data that were not reported to the Justice Department.

More info: https://www.dropbox.com/s/uxg5wouyaaq68sx/HowToForMAP2016.pdf?dl=0
Data:

- age
- race
- sex
- ethnicity
- relationship between the victim and perpetrator
- weapon

**Code repository:** 

https://github.com/cathrinesot/studioprojects/blob/master/code/fbi/FBI.ipynb

The csv file is over 100 MB, you can download it from : 

https://www.dropbox.com/s/b3tdb6gkgh4fb66/SHR1976_2015.csv.zip?dl=1
	
**Possible problems/fears/questions:** 

The dataset is huge and I am afraid I will need to learn sqlite for this analysis....

## Work so far
I've cleaned the data and made the correlation I wanted. Now I am searching for a way to visualize this:

![screen shot 2017-07-25 at 5 42 06 pm](https://user-images.githubusercontent.com/28814380/28596061-ced5197e-7164-11e7-84fd-a5c4325e4f92.png)

## Checklist

This checklist must be completed before you submit your draft.

- [x] I have already spent time with my data set, opening it, exploring it, etc
- [x] I have created a "DIARY.md" file to save links and list all of the terrible, no good problems I come across
- [x] My issue issue has `[Project]` in the title
- [x] My issue links to my data set(s)
- [x] My issue links to my code repository
- [x] My issue explains what I'd like to explore in the data set
- [x] My issue includes images - either inspiration or what I've done so far
- [ ] I have received two comments of peer feedback on my pitch issue

**Comment by cathrinesot** [comment]
# Update
	
1 notebook

https://github.com/cathrinesot/studioprojects/blob/master/code/fbi/FBI.ipynb


## Content

![relationship](https://user-images.githubusercontent.com/28814380/28739017-3b9d87d2-73c5-11e7-8415-54fe672555a8.png)

	
## Any changes in direction or topic?
	No
## Problems/Questions
	I have to change my graph so I would have fewer values. 
## Checklist
	
- [x] I have included my visuals
- [x] I have added writing about my topic
- [x] I have been updating my DIARY.md with details about my process
- [x] I have uploaded/updated any Jupyter Notebooks or other datasets into my code repository
- [ ] I have received two comments of peer feedback on my project update

**Comment by Ediegram** [comment]
As discussed on Friday you were going to try a new approach. I suggest a loose sketch by hand and I would be happy to take a look before you dive into the illustrator work.
