### ISSUE TITLE
Visualizing the Rise and Fall of Korean Kingdoms

### ISSUE THREAD

**Issue by SYChJung** [jsoma/data-studio-projects#39]
Please complete all of the following sections, or a robot will spookily dance around your issue! A completed version of this template can be found at https://github.com/jsoma/data-studio-projects/issues/37

# Pitch
Visualizing the Rise and Fall of Korean Kingdoms

## Summary
For my next project, I want to visualize a timeline of history of Korea. 

## Details
There were many countries in the Korean Peninsula. Many kingdoms competed with each other and conquered or were conquered by their rivals. I want to visualize the Korean kingdoms’ histories: when they were founded, how long they prospered, when their history ended, and most importantly, which countries succeeded them.

**Possible headline(s):** 
- Rise and Fall of Korean Kingdoms
- The Wild Wild East:  Crazy Korean History

**Data set(s):** 
“History of Korea” page in Wikipedia (https://en.wikipedia.org/wiki/History_of_Korea)

**Code repository:** 
	
**Possible problems/fears/questions:** 

## Checklist

This checklist must be completed before you submit your draft.

- [x] I have already spent time with my data set, opening it, exploring it, etc
- [ ] I have created a "DIARY.md" file to save links and list all of the terrible, no good problems I come across
- [x] My issue issue has `[Project]` in the title
- [ ] My issue links to my data set(s)
- [ ] My issue links to my code repository
- [ ] My issue explains what I'd like to explore in the data set
- [ ] My issue includes images - either inspiration or what I've done so far
- [ ] I have received two comments of peer feedback on my pitch issue

**Comment by wonderfulexperience** [comment]
Would be interesting to have a nice, easy-to-understand visualization for that. Many people don't want to read long text on different kingdoms. If it could be presented nicely, it would be great for teaching people on Korea's history. What is your personal goal in doing this project?

**Comment by deniseajiri83** [comment]
Very exciting! I like timelines, they are explanatory and brief. It'd be great if you could involve the key moments and not everything. Some overloaded timelines are difficult to read.

**Comment by SYChJung** [comment]
# Draft
I have organized a dataset about Korean kingdoms, and I’m using D3.js to plot the relationships between these kingdoms


## Content
First, I collected data from the Wikipedia and Namuwiki entries on the history of Korea and individual Korean kingdoms. 

I organized the data into a data frame of eight columns: Name, Description (short description about the kingdom), Preceded by, Year of foundation, Year of fall, Succeeded by, Fall (the reason of the kingdom’s fall), Age (historical periods).

This is the link to the data frame I made.
- https://github.com/SYChJung/studio-projects/tree/master/code/project2

This is a screenshot of my visualization (in progress)
![d3_korean_history-html](https://user-images.githubusercontent.com/28815149/28697960-d8b0a1ca-730d-11e7-8dca-390543000e2c.png)
- This is just an exploratory visualization. What I really want to show is the succession of the kingdoms. I am still working on it.

## Any changes in direction or topic?
As the webpages of Wikipedia and Namuwiki are not very organized and have different formats, it was hard to scrape them. So I just wrote out the whole data and organized them through Jupiter notebook.

## Problems/Questions
Having trouble finding the proper D3.js structure that I want.

## Checklist
	
- [x] I have included my visuals
- [x] I have added writing about my topic
- [ ] I have been updating my DIARY.md with details about my process
- [x] I have uploaded/updated any Jupyter Notebooks or other datasets into my code repository
- [ ] I have received two comments of peer feedback on my project update
