### ISSUE TITLE
Tracing defeat devices [Project]

### ISSUE THREAD

**Issue by marcelpauly** [jsoma/data-studio-projects#4]
# Pitch

## Summary

In the course of the Dieselgate scandal it emerged that multiple car manufacturers programmed their diesel engines to deactivate nitrogen oxide emission controls when the outside temperature drops under a specific numerical value. They claim the reason for that is protecting the engines from damages. On some models the emission controls only work between 68 and 86 degrees Fahrenheit. But the mean annual temperature in Germany is around 49 degrees.

Are the effects of these so called thermal window defeat devices measurable? I want to use NO2 air pollution data provided by the German Environment Agency and temperature data from the German Meteorological Office to find out if there is a correlation between temperature and NO2 content: Does the content increase when it gets colder? If so, it would be the very first time that the defeat devices’ direct effects become traceable. If not that would raise the question if the manipulations had any measurable effect at all.

I have hourly data for 2014, 2015 and 2016. My goal is a set of small multiples with data from different cities: either scatter plots (x = temperature, y = NO2 content, each dot represents one day, maybe I’d only use data from one year for that) or line charts (two lines, x = time, y1 = temperature, y2 = NO2 content). Like that:

![mlbstats2012](https://user-images.githubusercontent.com/7937281/28273181-9e4af146-6adb-11e7-96c0-09812bb03586.png)

![1458681814_thumb](https://user-images.githubusercontent.com/7937281/28273188-a1d12178-6adb-11e7-8e4d-7157ab920856.png)

## Details

**Possible headline(s):** This is when diesel engines stop filtering emissions; Diesel engines stop filtering emissions but it has no effect

**Data set(s):** [NO2 stations](http://www.env-it.de/stationen/public/downloadRequest.do), [NO2 data](https://github.com/marcelpauly/data-studio-projects/tree/master/code/NOx_air_pollution/NO2_2014_-_2016), [weather stations](http://bit.ly/2u1om2F), [weather data](http://bit.ly/2u1dvFO)

**Code repository:** https://github.com/marcelpauly/data-studio-projects/tree/master/code/NOx_air_pollution
	
**Possible problems/fears/questions:** For merging the data I have to find the closest weather station for each NO2 station and handle standard vs. daylight saving time. I have to decide what data points to compare (maybe Mo-Fr 9 a.m.). And how do I do small multiples?

## Work so far

I let Python download and unzip the weather data from ~500 weather stations and the German Meteorological Office sent me the NO2 data from their ~150 traffic-orientated measuring stations. I cleaned the data and mapped the stations to get a first overview (orange = NO2 station, purple = weather station).

![index](https://user-images.githubusercontent.com/7937281/28273275-ea3da616-6adb-11e7-8e51-77ee6b1925fd.png)

## Checklist

This checklist must be completed before you submit your draft.

- [x] I have already spent time with my data set, opening it, exploring it, etc
- [x] I have created a "DIARY.md" file to save links and list all of the terrible, no good problems I come across
- [x] My issue issue has `[Project]` in the title
- [x] My issue links to my data set(s)
- [x] My issue links to my code repository
- [x] My issue explains what I'd like to explore in the data set
- [x] My issue includes images - either inspiration or what I've done so far
- [x] I have received two comments of peer feedback on my pitch issue

**Comment by edl2118** [comment]
Great story idea Marcel. I think the small multiples will work and it's not difficult to understand. For correlation, it may actually be easier to understand.

**Comment by Dgorgs** [comment]
This is an amazing piece of data. Proper data!

**Comment by mukhtaryare** [comment]
This is an amazing data set. I think your challenge would be making this data easily understandable to the readers.

**Comment by 2109Sot** [comment]
Great idea! Love the map already. Do you have data about the manufacturers?

**Comment by marcelpauly** [comment]
# Update

## Content

My final dataset can be found in the [updated repository](https://github.com/marcelpauly/data-studio-projects/tree/master/code/NOx_air_pollution). In some cases I've found a correlation between temperature and NO2 content:

![scatter_borna](https://user-images.githubusercontent.com/7937281/28445975-d3039c32-6d95-11e7-90d0-da0c11375dd7.png)

But most cases are not that clear. You can see that in the small multiples I published in the article: https://marcelpauly.github.io/data-studio-projects/NOx_air_pollution/

## Any changes in direction or topic?

Not yet. Until next week I'm going to check if I get more significant results by changing some settings: include humidity, check 2014/2015 (now only 2016). But right now it seems like the story ist that there are not as strong correlations as you would expect. This raises the question if the so called thermal window defeat devices had any measurable effect at all.

## Problems/Questions

To dos:
* use city names instead of station IDs in the small multiples
* calculate correlation (**how?**)
* draw regression lines (**how?**)

## Checklist
	
- [x] I have included my visuals
- [x] I have added writing about my topic
- [x] I have been updating my DIARY.md with details about my process
- [x] I have uploaded/updated any Jupyter Notebooks or other datasets into my code repository
- [ ] I have received two comments of peer feedback on my project update

**Comment by marcelpauly** [comment]
# Update
	
## Content

I did a lot of additional analysis and found a new factor that influences the correlation between temperature and NO2 content in the air: speed. I updated my [repository](https://github.com/marcelpauly/data-studio-projects/tree/master/code/NOx_air_pollution) and my [story](https://marcelpauly.github.io/data-studio-projects/NOx_air_pollution/).

![scatter_cologne](https://user-images.githubusercontent.com/7937281/28557039-3c761efc-70d8-11e7-8613-01b1565562f4.png)

## Any changes in direction or topic?

A little. The first draft wasn't very promising because only a few of ~150 air measurement stations had a correlation between temperature and NO2 content. Then I read that defeat devices often follow multiple rules: they deactivate the NO2 filter when it gets colder **and** [the car is driving faster than a specific speed](https://www.bundestag.de/blob/461984/f23e5f41d8668625ec3fa74d74cf50bc/stellungnahme_mock-data.pdf#page=3). That's why I used OpenStreetMap data to find those stations near roads with a speed limit of at least 100 km/h. Now there are 35 stations left and multiple of them have correlations.

## Problems/Questions

still to do:
* calculate correlations (**how?**)
* draw regression lines/curves (**how?**)

## Checklist
	
- [x] I have included my visuals
- [x] I have added writing about my topic
- [x] I have been updating my DIARY.md with details about my process
- [x] I have uploaded/updated any Jupyter Notebooks or other datasets into my code repository
- [ ] I have received two comments of peer feedback on my project update

**Comment by marcelpauly** [comment]
# Final

## Project visuals/text

![scatter_bonn](https://user-images.githubusercontent.com/7937281/28700194-3cf3bda8-731c-11e7-909a-a21c36040c55.png)

Car manufacturers programmed their diesel engines to deactivate nitrogen dioxide (NO2) emission controls when the outside temperature drops. My analysis shows that these "thermal window defeat devices" cause a measurable effect.

After my meager results from the first week i cross-checked the air measuring stations with roads with high speedlimits. That analysis was very extensive but it saved the project and gave me much better results.

(Background: defeat devices often follow multiple rules: they deactivate the NO2 filter when it gets colder **and** the car is driving faster than a specific speed)

## Details

**Headline:** How air pollution increases when diesel engines stop their exhaust filter

**Published website version:** https://marcelpauly.github.io/data-studio-projects/NOx_air_pollution/

**Code repository:** https://github.com/marcelpauly/data-studio-projects/tree/master/code/NOx_air_pollution

**Final data set(s):**  [NO2 stations](http://www.env-it.de/stationen/public/downloadRequest.do), [NO2 data](https://github.com/marcelpauly/data-studio-projects/tree/master/code/NOx_air_pollution/NO2_2014_-_2016), [weather stations](http://bit.ly/2u1om2F), [weather data](http://bit.ly/2u1dvFO), [roads and speed limits](http://download.geofabrik.de/europe/germany.html)

## What did you find to be the most difficult part of this project?

Not giving up after the first results had many unclear cases.

## Are you satisfied with what you produced? Is there anything you would like to change or improve?

In the end I was satisfied, yes. But I have to work on my capability to estimate the effort. And my infographic annotations could look nicer.

## Checklist

- [x] I have included my visuals
- [x] I have posted my project to my project website
- [x] I have been updating my DIARY.md with details about my process
- [x] I have uploaded/updated any Jupyter Notebooks or other datasets into my code repository

**Comment by Ediegram** [comment]
Very nice work! One thing I think you could include would be some context/explanation of NO2 (consequences ... what is considered a safe amount, etc.) for readers unfamiliar with the issue. But I admire your persistence with the project and I think the chart you ended up with is stronger than the original idea pitched.

**Comment by marcelpauly** [comment]
Yes, you're absolutely right, the NO2 context is missing, I'll add that. Thank you very much!
