### ISSUE TITLE
relationship mapping of Iran's stock exchange market[Project]

### ISSUE THREAD

**Issue by deniseajiri83** [jsoma/data-studio-projects#40]
# Pitch
I want to visualize the stock exchange market in Iran.

## Summary
the idea is to figure out who the shareholders of the companies on the stock exchange market are to show the biggest shareholders, common shareholders and etc.  

![160404-rotenberg-icij-map](https://user-images.githubusercontent.com/5720774/28551998-8d942b5e-70b9-11e7-95ec-4ad9c602a776.png)

## Details

I would like to do something similar to Panama papers, but on a way smaller scale. I have access to the name of the companies on the exchange market and their info (including address, registration number, postal code, shareholders, etc.)

besides mapping the whole market (using something similar to google fusion table), I want to specifically focus on Mostazafan Foundation (one of the entities connected to the sanctioned Revolutionary Guards) to see how much they are active in the stick exchange market. 

**Possible headline(s):** 
[Mostazafan] controls ...% of the market
Iran's Stock Exchange Market is controlled by a few key players 

**Data set(s):** 
I have compiled the whole dataset already. It's in an excel format.

**Code repository:** 
https://github.com/deniseajiri83/studio-projects

**Possible problems/fears/questions:** 
I might not be able to identify all the Mostazafan-related shareholders as in Iran they usually hide behind front companies. 

## Work so far
I have spent some time cleaning and analyzing the data.

## Checklist

This checklist must be completed before you submit your draft.

- [x] I have already spent time with my data set, opening it, exploring it, etc
- [x] I have created a "DIARY.md" file to save links and list all of the terrible, no good problems I come across
- [x] My issue issue has `[Project]` in the title
- [x] My issue links to my data set(s)
- [x] My issue links to my code repository
- [x] My issue explains what I'd like to explore in the data set
- [x] My issue includes images - either inspiration or what I've done so far
- [ ] I have received two comments of peer feedback on my pitch issue

**Comment by wonderfulexperience** [comment]
I like network charts! The more "hidden" shareholder data you find, the more interesting it will be. Can you give information what kind of industries the foundation is involved in? And why?

**Comment by SYChJung** [comment]
I also like the network chart. I can see the relationships in one sight.

**Comment by sarahslo** [comment]
Here's what I would suggest. This is a difficult dataset because you can't definitely link companies together but if you start with who sits on Mostazafan Foundation's board, you can then go one by one thru the board and find out where else they sit. 

Is there a way as well to get at the size of these companies? Do you know anything about their value? That would help us know who is the biggest and who is the smallest. 

As to addresses, not sure what that will get you. Companies may be registered in one place but does that mean they are operating from there? Is there 'where' part of this important?
