### ISSUE TITLE
What makes a funny joke, Part 1 [Project]

### ISSUE THREAD

**Issue by adaskalopoulou** [jsoma/data-studio-projects#41]
# Pitch

## Summary
Since 1999, [Jester](http://eigentaste.berkeley.edu/) has been telling jokes. The website, built by UC Berkeley’s Laboratory for Automation Science and Engineering, asks users to rate its sometimes-humorous offerings, and then uses those answers to guess which of the remaining 100+ jokes you’ll like best. The UC Berkeley team has released databases that contain around 6 million ratings of 150 jokes from more than 100,000 anonymous users. 

What are the most popular jokes between the dates 1999 - 2003 and 2006 - 2009?
What kind of wording do those popular jokes include? 
Are the shorter or the longer jokes more popular?

## Details

**Possible headline(s):** 
Predicting the jokes of the next decade. 

**Data set(s):** 
http://eigentaste.berkeley.edu/dataset/

**Code repository:** 
https://github.com/adaskalopoulou/studio-projects/tree/master/code/project2

**Possible problems/fears/questions:** 

After reading the most popular jokes, I am afraid that it is not going to be very interesting.

However, the data analysis that this dataset will involve could be very educational (.dat files, 100 html files, na values, 150 columns).

## Work so far

**Most popular joke (April 1999 - May 2003):** 
A guy goes into confession and says to the priest, "Father, I'm 80 years old, widower, with 11 grandchildren. Last night I met two beautiful flight attendants. They took me home and I made love to both of them. Twice."
The priest said: "Well, my son, when was the last time you were in confession?"
"Never Father, I'm Jewish."
"So then, why are you telling me?"
"I'm telling everybody."

**Most popular joke (November 2006 - May 2009):** 
One Sunday morning William burst into the living room and said, "Dad! Mom! I have some great news for you! I am getting married to the most beautiful girl in town. She lives a block away and her name is Susan."
After dinner, William's dad took him aside. "Son, I have to talk with you. Your mother and I have been married 30 years. She's a wonderful wife but she has never offered much excitement in the bedroom, so I used to fool around with women a lot. Susan is actually your half-sister, and I'm afraid you can't marry her."
William was heart-broken. After eight months he eventually started dating girls again. A year later he came home and very proudly announced, "Dianne said yes! We're getting married in June."
Again his father insisted on another private conversation and broke the sad news. "Dianne is your half-sister too, William. I'm awfully sorry about this. William was furious! He finally decided to go to his mother with the news.
"Dad has done so much harm. I guess I'm never going to get married," he complained. "Every time I fall in love, Dad tells me the girl is my half-sister."
His mother just shook her head. "Don't pay any attention to what he says, dear. He's not really your father."

## Checklist

This checklist must be completed before you submit your draft.

- [x] I have already spent time with my data set, opening it, exploring it, etc
- [x] I have created a "DIARY.md" file to save links and list all of the terrible, no good problems I come across
- [x] My issue issue has `[Project]` in the title
- [x] My issue links to my data set(s)
- [x] My issue links to my code repository
- [x] My issue explains what I'd like to explore in the data set
- [x] My issue includes images - either inspiration or what I've done so far
- [ ] I have received two comments of peer feedback on my pitch issue

![a23cdb849c2f0b25f9798cfd1f6fddda](https://user-images.githubusercontent.com/28814404/28652883-666d4f9c-7258-11e7-9d0f-6efa3d533b56.png)

**Comment by simon-pinkmartini** [comment]
I read the most popular jokes you posted. They are kind of funny, but not really funny. Maybe your piece should be all about how different people find different things funny (i.e. you can analyze the variation of the joke ratings). I imagine some jokes have ratings of something like 7/10 but little variation (i.e. almost everyone gives 6, 7 or 8), but other jokes have ratings of 5/10 with big variation (i.e. some ratings 0s, some 10s)...

**Comment by adaskalopoulou** [comment]
# Update
	
## Description

**Jokes texts:**
	I worked on creating a dataframe with the texts of the 150 jokes. 
This involved:
- merging 100 html documents into one giant html file
- cleaning the merged html using regex in sublime text
- creating a csv file where all the joke texts are saved

I did some preliminary regex to test for repeating words, i.e.:

![screenshot 2017-07-26 16 50 00](https://user-images.githubusercontent.com/28814404/28643050-8416239c-7222-11e7-8373-b13ed1a2bea3.png)

**Next steps:**
- I have already calculated the number of ratings per joke. I plan to take the jokes that most people rate and find a special thing that they might have in common. 
- I have already found the most popular jokes. I plan to use these jokes and find some patterns.
- Using fuzzywuzzy to do all of the above. 

## Any changes in direction or topic?
I followed Simon's advice to check for variability in the ratings of the jokes. I didn't find any significant differences. It seems that there isn't a rating pattern that we can identify. The rating seems random. 

## Problems/Questions
Creating the csv with the jokes text was a very time-consuming procedure.
I have no idea how to visualise this story.

## Checklist
	
- [x] I have included my visuals
- [x] I have added writing about my topic
- [x] I have been updating my DIARY.md with details about my process
- [x] I have uploaded/updated any Jupyter Notebooks or other datasets into my code repository
- [ ] I have received two comments of peer feedback on my project update

**Comment by adaskalopoulou** [comment]
# Update
	
## Content

### Topics
I created 10 different joke topics:
1) religion
2) Clintons
3) health
4) family
5) marriage
6) people from other countries
7) jokes about men
8) jokes about women
9) engineers
10) typical format (i.e. What the difference between...? and How many ... does it take to ...?)

I found that about 12 jokes were associated with each topic. I tried to find differences in ratings based on these different joke topics but I couldn't identify a rating pattern. Maybe the only pattern was that between 2003-2006 people were giving worse ratings than in 2006-2009. 

### Word count
I counted the words in each joke and I created a new variable based on their length:
1) a joke with less than 15 words is called "very short"
2) a joke with more than 15 and less than 40 words is called "short"
3) a joke with more than 40 and less than 80 words is called "medium"-length
4) a joke with more than 80 and less than 150 words is called "long"
5) a joke with more than 150 words is called "very long"

Then I looked into differences in ratings based on whether a joke is longer or shorter. Again, no major patterns were identified. 
Slight differences:
Users didn't like "very short" and "short" jokes that much.
Users found the "very long" jokes a bit funnier. 

![screenshot 2017-07-31 17 46 29](https://user-images.githubusercontent.com/28814404/28799863-3a80005a-7618-11e7-87b0-3df837a3b34c.png)
This might look significant, but I should remind you that the rating scale is from -10 to 10. 

## Any changes in direction or topic?
I am saving this project for later next month when we will learn how to predict if a joke is funny or not. 

## Checklist
	
- [x] I have included my visuals
- [x] I have added writing about my topic
- [x] I have been updating my DIARY.md with details about my process
- [x] I have uploaded/updated any Jupyter Notebooks or other datasets into my code repository
- [ ] I have received two comments of peer feedback on my project update
