### ISSUE TITLE
Has Brexit brought Brussels more lobbyists? [Project]

### ISSUE THREAD

**Issue by IoannisAntypas** [jsoma/data-studio-projects#42]
# Pitch
...and who are they? 

We measure the rate of increase of new lobbyists registering in the EU Transparency Register between years to find out if Brexit has brought Brussels more lobbyists and then we find out what they are up to!

## Summary

Brussels is the Washington DC. of Europe. Well, not really, but it is the only place that features as much lobbying.  Every day, top European Bureaucrats welcome an army of different lobbyists, representing business, social, and national organizations, promoting their interests in European decision making bodies.

The triumph of the the pro-Brexit vote was a seismic event for Brussels, and many predicted that it would be the beginning of the end for the Union of European states. A year on, the European Union seems to be more united and cohesive than ever, with the British government unable to yet form a cohesive position regarding the arduous negotiations of Brexit the next years.

Has this turn of events brought more lobbyists to Brussels than ever before? Who are they, where do they come from, and who do they represent?

## Details

Eurostat has all the data we need. 

I have found out there is indeed a difference post referendum, and more lobbyists have landed in Brussels than ever before between June 24 2016 (one day after Brexit) and June 24 2017. 

The screenshots below show the total number of new lobbyists who have registered over the past three one year intervals.

2016-2017:

![06 24 16-06 24 17](https://user-images.githubusercontent.com/28814422/28552759-0b7a0c7e-70be-11e7-907a-7ec64479f142.png)

2015-2017

![06 24 15-06 24 16](https://user-images.githubusercontent.com/28814422/28552775-1971cc04-70be-11e7-948e-1998118e3aac.png)

2014-2015

![06 24 14-06 24 15](https://user-images.githubusercontent.com/28814422/28552778-209b5f2c-70be-11e7-8451-0d0f747e8c60.png)

Total number 

![overall](https://user-images.githubusercontent.com/28814422/28552786-27efd500-70be-11e7-8e9b-846f40781f0d.png)

- Beyond the increase in numbers we will also analyze who the 2016-2017 lobbyists are.

- We will see how many of them are ngos, business or professional associations, think tanks, or consultancies/law firms etc

- Which country they come from

- Size

- Field of interest, eg Competition, Consumer Affairs, Enterprise, Internal Market, Information Society

**Possible headline(s):** 

Has Brexit brought Brussels more lobbyists?

**Data set(s):** 

Everything is here 
http://ec.europa.eu/transparencyregister/public/consultation/search.do?dataReport=Change+my+search+criteria

Praise Eurostat

**Code repository:** 

Not yet
	
**Possible problems/fears/questions:** 

If this project doesn't go as bad as the previous I will consider it a spectacular success.

## Work so far

Identified and downloaded my dataset. Found the different areas I will measure

## Checklist

This checklist must be completed before you submit your draft.

- [x ] I have already spent time with my data set, opening it, exploring it, etc
- [ x] I have created a "DIARY.md" file to save links and list all of the terrible, no good problems I come across
- [ x] My issue issue has `[Project]` in the title
- [ x] My issue links to my data set(s)
- [ ] My issue links to my code repository
- [x ] My issue explains what I'd like to explore in the data set
- [ x] My issue includes images - either inspiration or what I've done so far
- [ ] I have received two comments of peer feedback on my pitch issue

**Comment by simon-pinkmartini** [comment]
Nice idea. You should definitely look at where the lobbyists come from (are more British companies trying to influence EU policy?). ((Also, let me know if you find an interesting story there relating to Swiss lobbyists))

**Comment by chrgavalas** [comment]
As discussed in person, it's a very good story for a specifically targeted audience. For a broader one, you'd to either elaborate further on what a lobbyist actually is or what are the direct fields affected by their intervention in Brussels. You are the man for this analysis since you live in Brussels :)

**Comment by qdinhbui2** [comment]
This is an interesting idea. Make sure you do some reporting to make sure that this data is what you think it is -- more lobbyists coming to Brussels. It could be the case that these records are these records are simply formalities.
