### ISSUE TITLE
What differentiates doodles from drawings [Project]

### ISSUE THREAD

**Issue by mathieulede** [jsoma/data-studio-projects#44]
# What differentiates doodles from drawings

## Pitch
Millions of drawings have been collected by Google to feed a neural network capable of recognizing what is beeing drawn. Anyone can take part in the research. A concept is given to you, you have 20 seconds to draw it.
I would like to focus this project on the unrecognized drawings from the dataset. The drawings that were to bad or to different from what the system expected.
As each drawing is geolocalized, it is possible to find which population has done the highest percentage of unrecognized drawing for each concept. It is also possible to get which concept is the hardest to draw or how many different lines does it require to draw, for example, an apple or a car.

## Summary
>The Quick Draw Dataset is a collection of 50 million drawings across 345 categories, contributed by players of the game Quick, Draw!. The drawings were captured as timestamped vectors, tagged with metadata including what the player was asked to draw and in which country the player was located.

[Link to the dataset](https://github.com/googlecreativelab/quickdraw-dataset)  

## Details

**Possible headlines**  

1. You versus the Neural Net
2. The drawings that resist AI
3. "I can't draw": Google feels the same way...

**Code repository**  
[Project 2](https://github.com/mathieulede/data-studio/tree/master/code/project2)

**Possible problems/fears/questions:**  
I have to merge a lot of datasets in binary format.

**Sketches/inspiration**  
[How do you draw a circle?](https://qz.com/994486/the-way-you-draw-circles-says-a-lot-about-you/)

## Work so far
I Learned how to read and unpack the binary files in python and made a simple analysis for the "apple" concept.

## Checklist

This checklist must be completed before you submit your draft.

- [x] I have already spent time with my data set, opening it, exploring it, etc
- [x] I have created a "DIARY.md" file to save links and list all of the terrible, no good problems I come across
- [x] My issue issue has `[Project]` in the title
- [x] My issue links to my data set(s)
- [x] My issue links to my code repository
- [x] My issue explains what I'd like to explore in the data set
- [x] My issue includes images - either inspiration or what I've done so far
- [ ] I have received two comments of peer feedback on my pitch issue

**Comment by mathieulede** [comment]
+ Try to put emphasis on the unrecognized drawings that are in fact really good.

![graph-04](https://user-images.githubusercontent.com/28827574/28700308-ec22675c-731c-11e7-9be8-c038ac430520.png)
![graph-02](https://user-images.githubusercontent.com/28827574/28700310-ef2fb2e2-731c-11e7-9707-eae5c27dfc9a.png)
![graph-01](https://user-images.githubusercontent.com/28827574/28700312-f184f82c-731c-11e7-9fa0-25a3b0bdb471.png)
![graph-05](https://user-images.githubusercontent.com/28827574/28700313-f4074a3c-731c-11e7-98a1-bdafd70f4e5f.png)
![graph-03](https://user-images.githubusercontent.com/28827574/28700528-59f9777e-731e-11e7-9f6c-8664b2378801.png)

**Comment by mathieulede** [comment]
Guess what animal it is (drawn by an Egyptian, march 12 2017):

![drawing](https://user-images.githubusercontent.com/28827574/28700440-cb488164-731d-11e7-9052-6697d6bf4a79.png)

This one is easier:

![drawing](https://user-images.githubusercontent.com/28827574/28700599-c6ec5478-731e-11e7-82c5-f896d3be9242.png)

**Comment by Ediegram** [comment]
great topic! -- really interesting. It's difficult to follow the narrative without the rest of your story and some more clear introduction for the charts.

**Comment by mathieulede** [comment]
The topic moved a little bit appart from the initial idea and speaks now about Artificial Intelligence and creativity. What can we lose with the ever increasing machine-learning systems.

I have to write a little story to explain the idea. The graphs should be scattered across the story.

![output_g2](https://user-images.githubusercontent.com/28827574/28948096-8079cd82-7881-11e7-8c0c-7252ef5587f3.jpg)

![output_g4](https://user-images.githubusercontent.com/28827574/28948200-2ef7cc56-7882-11e7-8765-7b2a9985dcca.jpg)

More here:
https://mathieulede.github.io/data-studio/quick_draw/
