### ISSUE TITLE
Influence of automobile industry on German politics [Project]

### ISSUE THREAD

**Issue by ElisaHarlan** [jsoma/data-studio-projects#45]
Please complete all of the following sections, or a robot will spookily dance around your issue! A completed version of this template can be found at https://github.com/jsoma/data-studio-projects/issues/1

# Pitch

## Summary
Many processes in transport and infrastructure policy raise the question of how big the influence of the automobile industry is on politics. This extends from the expansion of the public transport sector as a public-private partnership (PPP) through the negotiations on the reduction of CO2 values for cars on European level. Some incidents even regard certain state action, such as the so-called "emission scandal" of Volkswagen, the biggest European automobile manufacturer. 
Against this backdrop, it is important to investigate the relationship between the German Government and the authorities of the automotive industry (manufacturers and suppliers) during the   current legislative period. It is also important to know what other actors were able to articulate their interests in transport policy.

## Details

**Possible headline(s):** 
Depends on the results of the data

**Data set(s):** 
It is a very current dataset (7/5/2017) from a website called kleineanfragen.de that collects inquiries that all parties (in the German Parliament) can submit to the German Government. The request is most often a narrowly defined question a parliamentarian has with regard to the executive. It is an instrument of parliamentary control.
http://dip21.bundestag.de/dip21/btd/18/123/1812370.pdf

**Code repository:** 
	
**Possible problems/fears/questions:** 
The dataset looks only clean at first sight ... 

## Work so far
http://www.lemonde.fr/politique/visuel_interactif/2012/08/10/le-cumul-des-mandats-des-parlementaires-socialistes_1744713_823448.html#meter_toaster
Imagining how it could look like...
![le monde_socialiste](https://user-images.githubusercontent.com/28815568/28555634-1c6ace9a-70cf-11e7-90d1-05c7db21efdd.png)

## Checklist

This checklist must be completed before you submit your draft.

- [x] I have already spent time with my data set, opening it, exploring it, etc
- [x] I have created a "DIARY.md" file to save links and list all of the terrible, no good problems I come across
- [x] My issue issue has `[Project]` in the title
- [x] My issue links to my data set(s)
- [x] My issue links to my code repository
- [x] My issue explains what I'd like to explore in the data set
- [x] My issue includes images - either inspiration or what I've done so far
- [ ] I have received two comments of peer feedback on my pitch issue

**Comment by ElisaHarlan** [comment]
# Update
	
## Content
![ministries_2](https://user-images.githubusercontent.com/28815568/28739067-b2b7d322-73c5-11e7-8ef0-90479d9603ef.png)	

## Any changes in direction or topic?
No
	
## Problems/Questions
I did not manage to do a Sankey Diagram in Python, so I decided to draw stuff on Illustrator (poorly, I know). I would have liked to pick all connections that are in my df, not only seven ministries and seven companies, but I did not have the instruments to visualize the things. 
	
## Checklist
	
- [x] I have included my visuals
- [ ] I have added writing about my topic
- [ ] I have been updating my DIARY.md with details about my process
- [ ] I have uploaded/updated any Jupyter Notebooks or other datasets into my code repository
- [ ] I have received two comments of peer feedback on my project update

**Comment by sarahslo** [comment]
hey, don't shortchange yourself. this is a really good start.
so the data order, how you organize it will help you make the story clear.  you want to show who influences the different ministries, but you have arranged it to show how ministries are connected to all of the carmakers.
flip it. put the carmakers on the top. make sure you tell us somewhere with a label **what is the measure?** here it is euros? but what precisely?
so organize them by car maker with the biggest euro number on the top, and then the ministries by most to least across the bottom. this will help is see the data better. 
ALWAYS think about the order you are showing data in. This is a simple thing to do that will make a huge difference.
In terms of labels, note that the lemonde graphic on the top also includes numbers for the totals on the bars. you could add a similar approach here which is reader-friendly by doing the math for us and showing the totals.

i like this!

**Comment by ElisaHarlan** [comment]
Dear Sarah, I wanted to thank you for your very helpful comment on my project idea. Later this week, I found additional data on subsidies carmakers receive from the government and I decided to melt this two ideas together to one project. Thank you so much for your support!!
This is the link to the most current version of my project: 
https://elisaharlan.github.io/studio-projects/cars/
