### ISSUE TITLE
Traveling along the Silk Road[Project]

### ISSUE THREAD

**Issue by zuxinyi** [jsoma/data-studio-projects#46]
Please complete all of the following sections, or a robot will spookily dance around your issue! A completed version of this template can be found at https://github.com/jsoma/data-studio-projects/issues/1

# Pitch

## Summary
The Silk Road here is not the ancient network of trade routes which links the ancient societies of Asia with those of Europe and the Near East!!(although this is originally what I thought that this database is about.)

Silk Road, according to wikipedia's introduction, was an "online black market and the first modern darknet market, best known as a platform for selling illegal drugs. " it was operated as a Tor hidden service, and uses Bitcoin as its exchange currency. I want to see what kind of trade was most frequently conducted, what types of goods were sold on Silk Road, and how much revenues were made both by sellers and Silk Road operators.

## Details

**Possible headline(s):** 
Traveling along the Silk Road
Exchanges along the Silk Road

**Data set(s):** 
https://arima.cylab.cmu.edu/sr/
**Code repository:** 
https://github.com/zuxinyi/data-studio-projects/tree/master/code/SILK_ROAD
**Possible problems/fears/questions:** 
Working with sql in pandas
## Checklist

This checklist must be completed before you submit your draft.

- [x] I have already spent time with my data set, opening it, exploring it, etc
- [ ] I have created a "DIARY.md" file to save links and list all of the terrible, no good problems I come across
- [x] My issue issue has `[Project]` in the title
- [x] My issue links to my data set(s)
- [x] My issue links to my code repository
- [x] My issue explains what I'd like to explore in the data set
- [ ] My issue includes images - either inspiration or what I've done so far
- [ ] I have received two comments of peer feedback on my pitch issue

**Comment by qdinhbui2** [comment]
This is a fun idea. Let me know what you see in the data first before we can talk about chart forms.
