### ISSUE TITLE
Fast Food Restaurants Close to NYC Schools [Project]

### ISSUE THREAD

**Issue by demetriospogkas** [jsoma/data-studio-projects#48]
Please complete all of the following sections, or a robot will spookily dance around your issue! A completed version of this template can be found at https://github.com/jsoma/data-studio-projects/issues/1

# Pitch

## Summary
Inquire how close to schools are restaurant chains selling fast food.
Compare against healthy food chains.
Correlate with areas that have high rates of youth obesity.
Focus on New York City neighborhoods. 

## Details

**Possible headline(s):** 
"Fast Food Close to Schools Indicates Obesity Rates?"

**Data set(s):** 
NYC Health: http://a816-dohbesp.nyc.gov/IndicatorPublic/VisualizationData.aspx?id=2061,4466a0,113,Summarize  
Wikipedia https://en.wikipedia.org/wiki/List_of_fast_food_restaurant_chains

Building Own Restaurant Stores Location Database.

**Code repository:** 
https://github.com/demetriospogkas/The-Lede-2017-Data-Projects/tree/master/code/Project-03_Fast-Food-Near-NYC-Schools/01_Project-Pitch

**Possible problems/fears/questions:** 
NYC is actually not really known for having an obesity problem, rather a lot of people seem to be excercising, so I might have to shift focus on a state or city that has a more sizeable obesity problem. For the time being I'm building store locations for NYC, and will see how it goes.

## Work so far
Test Plots:  
KFC stores
![](https://raw.githubusercontent.com/demetriospogkas/The-Lede-2017-Data-Projects/master/code/Project-03_Fast-Food-Near-NYC-Schools/01_Project-Pitch/04-Test-KFC.png)

McDonald's
![](https://raw.githubusercontent.com/demetriospogkas/The-Lede-2017-Data-Projects/master/code/Project-03_Fast-Food-Near-NYC-Schools/01_Project-Pitch/04-Test-McDonalds.png)

Taco Bell
![](https://raw.githubusercontent.com/demetriospogkas/The-Lede-2017-Data-Projects/master/code/Project-03_Fast-Food-Near-NYC-Schools/01_Project-Pitch/04-Test-Taco-Bell.png)

Wendy's
![](https://raw.githubusercontent.com/demetriospogkas/The-Lede-2017-Data-Projects/master/code/Project-03_Fast-Food-Near-NYC-Schools/01_Project-Pitch/04-Test-Wendys.png)

## Checklist

This checklist must be completed before you submit your draft.

- [x] I have already spent time with my data set, opening it, exploring it, etc
- [x] I have created a "DIARY.md" file to save links and list all of the terrible, no good problems I come across
- [x] My issue issue has `[Project]` in the title
- [x] My issue links to my data set(s)
- [x] My issue links to my code repository
- [x] My issue explains what I'd like to explore in the data set
- [x] My issue includes images - either inspiration or what I've done so far
- [ ] I have received two comments of peer feedback on my pitch issue

**Comment by chrgavalas** [comment]
I don't know about New York specifically but the US in general is among the most obese countries on earth along with Australia and Greece! It's a great idea. On top of what you say, I'd like to see a correlation between obesity rates and grocery stores selling healthy food because I am pretty sure that's where the real problem starts. Soma did a similar exercise with the food deserts of Chicago!

**Comment by kcough** [comment]
Obesity is definitely an issue in NYC, so I don't think you need to switch cities: "In New York City, obesity is epidemic: more than half of adult New Yorkers are overweight (34%) or obese (22%). Data show that obesity begins early in life: nearly half of all elementary school children and Head Start children are not a healthy weight. In New York City, 1 in 5 kindergarten students, and 1 in 4 Head Start children, is obese." http://www1.nyc.gov/site/doh/health/health-topics/obesity.page

It might be interesting to look at the shift in obesity rates since 1990 and compare that to the number of fast food chains--how many McDonalds existed in a certain neighborhood in 1990 vs today, and how has the obesity rate changed?

**Comment by demetriospogkas** [comment]
# Update
	
## Content
![](https://raw.githubusercontent.com/demetriospogkas/The-Lede-2017-Data-Projects/master/code/Project-03_Fast-Food-Near-NYC-Schools/02_First-Draft/Test-Horizontal-Obesity-and-Fast-Foods%20v02.png)
(this image is only a draft of how the visual should/might look like. I need to revise the numbers, so the final outcome might look different in terms of the actual data visualised)

## Any changes in direction or topic?
Progress so far: Mined store locations for 7 fast food restaurant chains, and joined them with schools and UHF34 neighborhoods geometries. With vincenty module I am able to look for number of restaurants in any given radius from every school.
	
## Problems/Questions
- I realised that the data I have downloaded, concern Adult Obesity Rates and not Youth Obesity Rates. I will have to go back to the NYC Data Portal and look for the Youth Obesity Rates.  
- I need to revise, determine and make clear my methodology for calculating how many restaurants are close to each school, because the longer the radius is, the more restaurants are over-lapping with each other, and I'm getting potentially inaccurate results. For example, a radius of 0.1 miles around each school yiels ~380 results for restaurants, while a radius of 0.5 around schools is yielding <10,000 results for restaurants.  
- Also, I should calculate an average of number of restaurants close to schools, or absolute numbers? Absolute numbers are inaccurate because of overlapping?  

## Checklist
	
- [x] I have included my visuals
- [ ] I have added writing about my topic
- [x] I have been updating my DIARY.md with details about my process
- [x] I have uploaded/updated any Jupyter Notebooks or other datasets into my code repository
- [ ] I have received two comments of peer feedback on my project update

**Comment by demetriospogkas** [comment]
# Update

## Content
Codes: https://github.com/demetriospogkas/The-Lede-2017-Data-Projects/tree/master/code/Project-03_Fast-Food-Near-NYC-Schools/03_Revision
Website: https://goo.gl/qk9PZy

![](https://demetriospogkas.github.io/The-Lede-2017-Data-Projects/Project-03_Fast-Food-Near-NYC-Schools/images/overweight-adult-fast-food-new-york-city.png)	
![](https://demetriospogkas.github.io/The-Lede-2017-Data-Projects/Project-03_Fast-Food-Near-NYC-Schools/images/overweight-obese-adult-new-york-city.png)

## Any changes in direction or topic?
	
## Problems/Questions
Instead of Fast Food vs. School I worked on Fast Food against Adult Overweight/Obesity.
Planning to work on Fast Food against Schools until Friday
	
## Checklist
	
- [x] I have included my visuals
- [x] I have added writing about my topic
- [x] I have been updating my DIARY.md with details about my process
- [x] I have uploaded/updated any Jupyter Notebooks or other datasets into my code repository
- [ ] I have received two comments of peer feedback on my project update
