### ISSUE TITLE
Brazilian government-sponsored credit card expenses that violate bidding law [Project]

### ISSUE THREAD

**Issue by RodrigoMenegat** [jsoma/data-studio-projects#49]
# Pitch
## Summary:
In Brazil, government agents that are responsible for buying goods and material for public institutions often receive a CPGF – Federal Government Paying Card. It’s a credit card whose funds are drawn directly from the State’s treasury. According to law, it should be used only in case of ‘emergencies’ and/or small payments that would be delayed if the normal bidding process was followed. What historically happened is that many government workers have used the card to make expensive buys without following the appropriate procedures, which may lead to inefficient spending, corruption and lack of accountability. I want to track these cases.

## Details
According to Brazilian bidding law, all the payments for services and goods above R$ 8000 should go through a full bidding process, in which many companies would compete to offer the best price and service. There are a few exceptions, such as spending made during states of emergency or of artistic goods. Objectively, to check what are the cases that likely broke the law, I would have to filter and see what were the payments made above that cap. What agencies are doing that, when, how often, how does it change overtime, who is receiving this money?

**Possible headline(s):** 
In 2017, government credit card holders spent R$ XXX millions in products that should have been subject to a bidding proccess

**Data set(s):**  [CPGF expending](http://www.portaldatransparencia.gov.br/downloads/mensal.asp?c=CPGF) 

**Code repository:**  [Here](https://github.com/RodrigoMenegat/studio-projects/tree/master/code/government-credit-cards)

**Possible problems/fears/questions:** 
I am unsure of the exact terms and implications of the bidding law. I should contact a lawyer that specializes in this issue to get a better grasp on that.

I also don’t know what is the best way to visualize that. Maybe a tree map with all the agencies and their respective spending? Or rely in a narrative-text-blob traditional story and traditional horizontal bar charts?

## Work so far
I discovered that, in 2015, most of the irregular buys were made by police battalions in Rio de Janeiro – they were buying groceries in large numbers, in one particular supermarket. The most interesting thing is that those batallions were NOT from the Rio de Janeiro state. Many of them came from up north. Why were their commanders buying stuff in those supermarkets near the beach? What were the battalions doing there, in the first place? 

I have a (really ugly) network graph showing all the bussinesses that received more than R$ 8000 in a single buy from a government official (in orange) and the agents resposible for the spending (in blue).

![ugly-chart](https://user-images.githubusercontent.com/28814352/28557504-d12c7f58-70da-11e7-87e1-0d7cbfc2cd3c.png)

## Checklist
This checklist must be completed before you submit your draft.
- [x] I have already spent time with my data set, opening it, exploring it, etc
- [x] I have created a "DIARY.md" file to save links and list all of the terrible, no good problems I come across
- [x] My issue issue has `[Project]` in the title
- [x] My issue links to my data set(s)
- [x] My issue links to my code repository
- [x] My issue explains what I'd like to explore in the data set
- [x] My issue includes images - either inspiration or what I've done so far
- [ ] I have received two comments of peer feedback on my pitch issue

**Comment by wonderfulexperience** [comment]
That's great investigative journalism! Your usage of data will be very uncomfortable for the Brazilian government. Maybe you can also aggregate the data by government department, company industry or region to provide some more insights?

**Comment by RodrigoMenegat** [comment]
# Update
  
## Content

![barbecues](https://user-images.githubusercontent.com/28814352/28850587-7db1b3f4-76eb-11e7-86ed-6c5e97dfadc4.jpg)

### Since 2010, Brazilian officials ate two steakhouse dinners per day with public money

In the last seven years, Brazilian public funds were used to pay for, on average, two barbecue meals every day.

Since December of 2009, when all the expenses paid with government-sponsored credit cards were made available online, 4911 bills were registered on ‘churrascarias’ – the Brazilian barbecue houses, where, usually, an all-you-can-eat selection of fine cuts is served on sword-like skewers. 

Usually, a meal on a ‘churrascaria’ costs twice or more than in other sort of establishments. On total, around R$ 1,2 million – an amount equivalent to US$ 385,000 – was spent on those restaurants. 

The greatest part of those expenses came from army personnel and staffers from the Ministry of Defense. Indeed, some of the restaurants that received the most money are located near highways, which suggests that officials might be going there to eat during duty travels. Nevertheless, there are many examples of extravagant dinners as well.

 In the most recent case, between July 6 and July 10 of 2017, cardholders from the Ministry of Defense’s administrative office went three times to “Fogo de Chão”, a luxurious steakhouse of worldwide fame located in Brasília, the federal capital. In the sum of those, approximately R$ 8600 were spent – an amount sufficient for 62 people to enjoy a full all-you-can-eat meal with fine meats.

In contrast, the average monthly per-capita income of a Brazilian household in 2016, according to the Brazilian Institute of Geography and Statistics (IBGE), was of R$ 1226 – seven times less than the amount spent in prime steaks by the officials in those five days alone.

Talking about the IBGE, it was responsible for some curious purchases as well: between March 2014 and March 2015, a unit of the institution made thirteen payments to an establishment called “Disk-Cerveja” – a beer home-delivery hotline.

The government-sponsored credit cards, officially named Federal Government Payment Card (CPFG, in the Portuguese acronym), were originally created to make easier for public officials to buy supplies in exceptional cases when submitting the purchases to a board approval process would take an unreasonable amount of time.

**BREAKING THE LAW**
Apart from the expenses with luxury dining and booze delivery, staffers of the public sector that made purchases above R$ 8000 for their agencies possibly broke the Brazilian bidding law. 

According to it, all the acquisitions that surpass this cap should undergo a full bidding process, in which companies would compete to provide the best possible price. 

There are a few exceptions, such as states of public calamity and the acquisition of goods of artistic value. “Usage material” for the Armed Forces is also included in the exceptions, in these exact vague terms.

Since 2010, over-the-cap purchases were made 2297 times – and out of those, 2277 cases were deemed confidential to “ensure the safety of the society and the State”. Of the remaining 20 purchases, 17 came, again, from staffers of the Ministry of Defense. The expenses were made in stores of automobile parts, supermarkets, computer appliances, an internet provider and hotels.

**BLACK BOX**
Those questionable expenses can be linked to a broader lack of transparency. Even though all the purchases made with government credit-cards are supposedly available for online, more than 60% those payments are, by all practical means, untraceable.

This happens because around R$ 220 million were deemed confidential by the government for national security issues.

Of that amount, R$ 160 million came from the Federal Police, the Brazilian Intelligence Agency (ABIN), the federal capital security forces, the Army, the Airforce or the tax-collecting agency. The rest comes from the President and Vice-President offices – offices which’s expensed are 99% and 97% under secrecy, respectively.

Apart from that, another R$ 60 million was directly withdrew from ATMs – what makes the destination of the money impossible to follow. Overall, then, approximately R$ 280 million spent using government-funded credit cards isn’t transparent.

## Any changes in direction or topic?
  Yes. I could find some expensed that **might** be violating bidding laws, but they were not as widespread as I thought they would be -- and most of those were considered confidential, so I had almost no data about them!

  I put that information into my story, but since it was really boring, I started telling from another angle: crazy spending in fancy barbecue houses.

  On average, we are paying for government officials to eat **two barbecues a day** - and not barbecues as american know it, but the [Brazilian churrasco](http://www.cnn.com/travel/article/brazilian-barbecue-guide/index.html): fine meat, served in swords, all-you-can-eat.

  I used this hook to talk about possible frauds and the lack of transparency in the usages of those credit cards.
## Problems/Questions
- Still need to find a way to visualize the lack of transparency. 
- Need to account the changes in currency and inflation rates over time - but I don't know how to do this.
- I don't think my visualization choice for the barbecues was the best one - I choose that one because it made it easier to highlight the craziest dinners.
- Still need to explain better what those cards are: not every official has one, only a few.

## Checklist
  
- [x] I have included my visuals
- [x] I have added writing about my topic
- [x] I have been updating my DIARY.md with details about my process
- [x] I have uploaded/updated any Jupyter Notebooks or other datasets into my code repository
- [x] I have received two comments of peer feedback on my project update

**Comment by qdinhbui2** [comment]
You have a solid graphic. I like the outliers. One thing I would like to know are how many dots per year. 

If you're wondering how to do the calculations. I would inflation adjust using brazilian price index, then convert to dollars using the USD/REAS exchange rate, making sure you apply the right annual average exchange rate each year. 

A good example for inflation is here: https://www.minneapolisfed.org/community/teaching-aids/cpi-calculator-information

**Comment by RodrigoMenegat** [comment]
@qdinhbui2 do you think I should plot the axis in USD or BRL? 

I guess the first option would make the chart easier to understand for an english-speaking audience, but the data would look way more compressed. Maybe I'd lose track of just how above-average those outliers are.

**Comment by qdinhbui2** [comment]
I think for class -- USD.

**Comment by sarahslo** [comment]
Excellent work. I would like to see all the expenditures this way -- a bunch of charts for each type of category so we can see what it is being spent on. But I love that you have chosen expensive dinners. What I would do is add two colors here, 1 for the 62 infantry and 1 for the ministry of defense. Then we would see not only that they tend to outspend, but we would see how much they make up of this entire dataset. As you mentioned earlier, a lot. This is really excellent. It's the type of thing that with some reporting and a lot of confirmation, I would publish. I'd like a clearer grid on the chart so you can see the values better.

I don't agree you need to adjust for inflation. If some of these data went back 20 years, then I would say yes. Unless there is huge fluctuation in the Real? If there is, then definitely adjust the Reas.  Currency conversion can muddy the waters. We want to know just how much they spent, so having the conversion in the labeling does that job.

Another thing you could have done was highlight that one restaurant they went to 3 times. Or the beer delivery service. A lot of what you write is curious but you don't surface that in the data. Why no?

Really fun and smart.

**Comment by RodrigoMenegat** [comment]
# Final
 
## Project visuals/text
### Since 2010, Brazilian officials ate two steakhouse dinners per day with public money
RODRIGO MENEGAT

In the last seven years, Brazilian public funds were used to pay for, on average, two barbecue meals every day.

Since December of 2009, when all the expenses paid with government-sponsored credit cards were made available online, 4911 bills were registered on ‘churrascarias’ – the Brazilian barbecue houses, where, usually, an all-you-can-eat selection of fine cuts is served on sword-like skewers.

Usually, a meal on a ‘churrascaria’ costs twice or more than in other sort of establishments. On total, around R$ 1,2 million – an amount equivalent to US$ 385,000 – was spent on those restaurants.

![barbecues-small](https://user-images.githubusercontent.com/28814352/28985948-e936b9f0-7932-11e7-8c88-4db13ef96113.jpg)

The greatest part of those expenses came from army personnel and staffers from the Ministry of Defense. Indeed, some of the restaurants that received the most money are located near highways, which suggests that officials might be going there to eat during duty travels. Nevertheless, there are many examples of extravagant dinners as well.

In the most recent case, between July 6 and July 10 of 2017, cardholders from the Ministry of Defense’s administrative office went three times to “Fogo de Chão”, a luxurious steakhouse of worldwide fame located in Brasília, the federal capital. In the sum of those, approximately R$ 8600 were spent – an amount sufficient for 62 people to enjoy a pricey R$ 120 (US$ 38) dinner.

In contrast, the average monthly per-capita income of a Brazilian household in 2016, according to the Brazilian Institute of Geography and Statistics (IBGE), was of R$ 1226 – seven times less than the amount spent in prime steaks by the officials in those five days alone.

Talking about the IBGE, it was responsible for some curious purchases as well: between March 2014 and March 2015, a unit of the institution made thirteen payments to an establishment called “Disk-Cerveja” – a beer home-delivery hotline.

The government-sponsored credit cards, officially named Federal Government Payment Card (CPFG, in the Portuguese acronym), were originally created to make it easier for public officials to buy supplies in exceptional cases, when submitting the purchases to a board approval process would take an unreasonable amount of time.

#### BREAKING THE LAW

Apart from the questionable nature of expenses with luxury dining and booze delivery, staffers of the public sector that made purchases above R$ 8000 for their agencies possibly broke the Brazilian bidding law.

According to it, all the acquisitions that surpass this cap should undergo a full bidding process, in which companies would compete to provide the best price.

There are a few exceptions, such as purchases made during a state of public calamity and the purchase of artistic goods. “Usage material” for the Armed Forces is also among them, in these exact vague terms.

Since 2010, over-the-cap purchases were made 2297 times – and out of those, 2277 cases were deemed confidential to “ensure the safety of the society and the State”. Of the remaining 20 purchases, 17 came, again, from staffers of the Ministry of Defense. The payments were made in automobile parts and computer applicances stores, supermarkets, an internet provider and hotels.

![sigilo-small](https://user-images.githubusercontent.com/28814352/28985953-f1362df2-7932-11e7-9470-6d0d6cf251f8.jpg)

#### BLACK BOX

Those questionable expenses can be linked to a broader lack of transparency. Even though all the purchases made with government credit-cards are supposedly available for public scrutiny online, more than 60% those payments are, by all practical means, untraceable.

This happens because around R$ 220 million were deemed confidential by the government for national security issues.

Of that amount, R$ 160 million came from the Federal Police, the Brazilian Intelligence Agency (ABIN), the federal capital security forces, the Army, the Airforce or the tax-collecting agency. The rest comes from the President and Vice-President offices – where expenses are 99% and 97% secret, respectively. Apart from that, another R$ 60 million was directly withdrew from ATMs – what makes the destination of the money impossible to follow. Overall, then, approximately R$ 280 million spent using government-funded credit cards isn’t transparent.

## Details
Not much changed since the last update, mostly because of time constraints. I only have one more graphic, comparing secret x non-secret purchases over the R$ 8000 cap.

**Headline:**  Since 2010, Brazilian officials ate two steakhouse dinners per day with public money

**Published website version:** [Here!](https://rodrigomenegat.github.io/studio-projects/all-the-government-barbecues/)

**Code repository:**[Here!](https://github.com/RodrigoMenegat/studio-projects/tree/master/code/all-the-government-barbecues)

**Final data set(s):** [Here!](https://drive.google.com/file/d/0B6khFsxSwoi2cHEwZDNaM3MxMUU/view?usp=sharing)

## What did you find to be the most difficult part of this project?
Code and data-wise, nothing in particular. I spent some time 'interviewing' the database to find an interesting hook, though. I had problems with a really trivial thing: find out the perfect size, in pixels, of my visualizatios!


## Are you satisfied with what you produced? Is there anything you would like to change or improve?
Kind of. I think the story is appealing, but my analysis lacks some important angles, such as a categorical breakdown of each purchase (something that I would have to do manually, by grouping all the stores and looking them up online or deciding what they do by their name alone).

## Checklist

- [x] I have included my visuals
- [x] I have posted my project to my project website
- [x] I have been updating my DIARY.md with details about my process
- [x] I have uploaded/updated any Jupyter Notebooks or other datasets into my code repository
