### ISSUE TITLE
Visualization of the correlation between donation education and organ donor registry rate [Project]

### ISSUE THREAD

**Issue by hichenwang** [jsoma/data-studio-projects#51]
Please complete all of the following sections, or a robot will spookily dance around your issue! A completed version of this template can be found at https://github.com/jsoma/data-studio-projects/issues/1

# Pitch

## Summary
I was inspired by the organ transplants data set in the data is plural google spreadsheet and thinking about except for implementing presumed consent, which has been initiated by several states in different years but has received strong opposition for different kinds of reasons, what else we can do to alleviate the gap between the supply and demand of organ donation. 

“So, if Presumed Consent is not the solution, how can we increase organ donation to ensure that no one dies while waiting for an organ? According to Rafael Matesanz, head of Spain’s ONT, the answer lies in its highly structured and managed transplant coordination network with intensive care transplant coordinators based at the site of the donation[ix]. Versions of this system are also used in the US, with in-house Organ Procurement Coordinators and Intensivist consultants, and have been shown to be remarkably effective, and merit expansion across all major hospitals.” (source: http://donatelifecalifornia.org/education/faqs/presumed-consent/) 

The major methods to improve organ donor registry rate include school donation education and drivers education, which implemented only in 13 and 15 out of 52 states. 

I want to look at how this donation education influenced organ donor registry rate.
And also how high organ donor registry rate helps to alleviate the organ demand tension.

<img width="523" alt="screen shot 2017-07-25 at 1 54 37 pm" src="https://user-images.githubusercontent.com/28814446/28586201-efc7a774-7140-11e7-9b68-50bd2f2f793d.png">

## Details

**Possible headline(s):** Only 15 states are doing organ donation education, a rewarding method that more states should apply

**Data set(s):** 
https://www.donatelife.net/wp-content/uploads/2016/06/2015-DLA_Annual-Report_FINAL-for-onscreen-viewing.pdf
https://www.organdonor.gov/legislation_micro/#

Very helpful readings:
https://bioethicsarchive.georgetown.edu/pcbe/background/organ_donation.html#part1
https://www.usnews.com/news/articles/2016-02-12/presumed-consent-and-americas-organ-donor-shortage 

**Code repository:** 
	
**Possible problems/fears/questions:** 
1.	Need to find when did each of the states have its organ donation education (school and drivers) to check its influence on organ donation registration number 

## Work so far
I found the organ donor registry rate of all the states, but only from 2013-2015, and the regulations of all the states.

## Checklist

This checklist must be completed before you submit your draft.

- [ ] I have already spent time with my data set, opening it, exploring it, etc
- [ ] I have created a "DIARY.md" file to save links and list all of the terrible, no good problems I come across
- [x] My issue issue has `[Project]` in the title
- [ ] My issue links to my data set(s)
- [ ] My issue links to my code repository
- [x] My issue explains what I'd like to explore in the data set
- [x] My issue includes images - either inspiration or what I've done so far
- [ ] I have received two comments of peer feedback on my pitch issue

**Comment by hichenwang** [comment]
# Update

## Content
A week of struggling with changing my stories. 

The states that provide driver education and school education of organ donation don't really have a higher organ donation rate, some of them even rank very low, and there are too many factors could potentially influence organ donation decisions.

2nd pitch idea (this idea didn't work either): I was also inspired by the analysis 'donatelifecalifornia' did http://donatelifecalifornia.org/education/faqs/presumed-consent/, in which they found the countries with a higher pct of Catholic population have more organ donors.

<img width="823" alt="screen shot 2017-08-02 at 2 29 46 am" src="https://user-images.githubusercontent.com/28814446/28860501-e8f22920-772a-11e7-93c0-627222c9acae.png">

I want to see whether this finding was also true in the states of Amerca, but there are no correlations.

![download](https://user-images.githubusercontent.com/28814446/28860524-029f6fea-772b-11e7-85a3-877d749f7aaf.png)
	
## Any changes in direction or topic?
Again, there are too many things can influence organ donation decisions and I'm thinking to do sth. more straightforward. I started from the organ donation and transplantation dataset on U.S. Department of Health and Human Services https://optn.transplant.hrsa.gov/data/, and I want to go back to that massive data set to find a story. 

**3rd pitch idea (I want to work on this one):**
I want to compare how long a patient needs to wait for an organ transplantation in 2003 and 2014. 
Inspired by the video watched in the class http://www.fallen.io/ww2/, I want to use two calendars do the comparison and use scrolling to show the length of time. 
Say, if one patient registered on Jan 1, 2003, and Jan 1, 2014, on what date will he get his transplantation. 

**Idea 1 for the 3rd pitch: focusing on the age group 18-34 and do multiple kinds of organs:**

![image](https://user-images.githubusercontent.com/28814446/28860962-c4c35cd4-772c-11e7-896c-8ac5e735a8cb.png)

**Idea 2 for the 3rd pitch: the other is doing multiple age groups but only focusing on one kind of organ, say, liver:**

![image](https://user-images.githubusercontent.com/28814446/28861033-0b1093a0-772d-11e7-8385-36c3337ce9b5.png)


## Problems/Questions
1. I don't know which idea to pick, though I slightly prefer the second one, as organ transplantation waiting time vary significantly among different age groups, and I think it would be interesting to show this. 

![image](https://user-images.githubusercontent.com/28814446/28861464-ff550d28-772e-11e7-9565-35adf8c5eeda.png)

2. And also, I don't know except for showing how long people need to wait, what else I can add to the graphic to make it more meaningful. 
	
## Checklist
	
- [x] I have included my visuals
- [x] I have added writing about my topic
- [ ] I have been updating my DIARY.md with details about my process
- [ ] I have uploaded/updated any Jupyter Notebooks or other datasets into my code repository
- [ ] I have received two comments of peer feedback on my project update

**Comment by Ediegram** [comment]
easy way to make a grid for calendar:

<img width="1016" alt="screen shot 2017-08-03 at 9 24 41 am" src="https://user-images.githubusercontent.com/18584853/28923977-f223f10a-782d-11e7-8c10-1fba33c666d6.png">

<img width="1034" alt="screen shot 2017-08-03 at 9 25 14 am" src="https://user-images.githubusercontent.com/18584853/28923978-f224cc4c-782d-11e7-84b7-3654eaed2fe9.png">

**Comment by hichenwang** [comment]
# Revision
	
## Content
After presenting the calendar idea in the class (https://hichenwang.github.io/project_2_liver_trans/liver_trans.html), I found the information in the charts was still confusing, even I tried different ways to eliminate the miscommunication by like adding annotations and lines.  

I decided to create a stacked bar charts to show the changes of each age group. You can find my work here: https://hichenwang.github.io/project_2_liver_trans/liver_trans%20copy.html
So far, I feel this illustration is much clearer. 
![liver_trans_new](https://user-images.githubusercontent.com/28814446/29252267-d93541f6-8031-11e7-9bb5-1a5f8110bdaf.png)

## Any changes in direction or topic?
Topic-wise, no. But it inspired me of another pitch idea, which will possibly be my next pitch. 

## Problems/Questions
I am worried about the layout - where to put my text. I was planning to put all the text in the left down corner, but personally, I feel it's hard to connect the chart with text by using this layout. 
I would like to hear feedback both on the new chart and on the layout. 	

## Checklist
	
- [x] I have included my visuals
- [x] I have added writing about my topic
- [ ] I have been updating my DIARY.md with details about my process
- [x] I have uploaded/updated any Jupyter Notebooks or other datasets into my code repository
- [ ] I have received two comments of peer feedback on my project update
