### ISSUE TITLE
Why are some Swiss pension funds more expensive? [Project]

### ISSUE THREAD

**Issue by wonderfulexperience** [jsoma/data-studio-projects#52]
# Pitch

## Summary

The corporate pension funds ("occupational pension plans") in Switzerland manage a huge amount of assets (more than $ 900 bn), which represent a large part of the country's household wealth. It is therefore very relevant how efficient these funds are managed.

## Details

A survey of large pensions funds show administrative costs varied between $ 160 and 600 per year and insured person. What is the reason that some of these funds are so much more expensive? Are bigger funds more cost-efficient? Or have the more expensive funds better expertise and provide higher returns?

The inspiration comes from surveying funds. Their returns are negatively correlated to how much they charge (e.g. http://www.fundlibrary.com/features/etfs/page.asp?id=15648&p_=y):
![images](https://user-images.githubusercontent.com/28814374/28573053-3e890558-7117-11e7-9187-02591a48fead.jpg)

**Possible headline(s):** 
- "These pension funds are not worth their money"
- "It is also true for pension funds: Higher costs don't mean higher returns"

**Data set(s):** 
Survey data from the pension advisory company WH&P: http://www.pensionskassenvergleich.ch/

Aggregated data from the Swiss statistics office: https://www.bfs.admin.ch/bfs/en/home/statistics/social-security/occupational-pension-plans.html

**Code repository:** 
https://github.com/wonderfulexperience/data-studio-projects/tree/master/code/Project_2

**Possible problems/fears/questions:** 
Too little data points, no clear message regarding costs

## Work so far
Looking at data points.

## Checklist

This checklist must be completed before you submit your draft.

- [X] I have already spent time with my data set, opening it, exploring it, etc
- [X] I have created a "DIARY.md" file to save links and list all of the terrible, no good problems I come across
- [X] My issue issue has `[Project]` in the title
- [X] My issue links to my data set(s)
- [X] My issue links to my code repository
- [X] My issue explains what I'd like to explore in the data set
- [X] My issue includes images - either inspiration or what I've done so far
- [x] I have received two comments of peer feedback on my pitch issue

**Comment by SYChJung** [comment]
Really interesting! Pointing out the dark side of pension funds. This can help people to choose the proper pension funds.

**Comment by simon-pinkmartini** [comment]
Yes, you should definitely do some naming & shaming here! Maybe you can contact some independent pension funds consultants for data?

**Comment by wonderfulexperience** [comment]
# Update
	
## Content
I selected now different charts to show how much pension funds charge and how it is related to asset allocation. My main focus is now on if pension funds charge for better performance.

Surprisingly, pension funds didn't increase the allocation of their assets to stocks:
![download](https://user-images.githubusercontent.com/28814374/28677750-7b8d85a4-72bc-11e7-9fac-3df4070872d4.png)

Many funds increased their fees over the last years:
![download-1](https://user-images.githubusercontent.com/28814374/28677801-9c2c44d0-72bc-11e7-8d25-ed4079950cff.png)

There seems to be a relationship between higher fees and higher allocation to stocks and alternative investments (hedge funds and others):
![download-2](https://user-images.githubusercontent.com/28814374/28677922-f03102fa-72bc-11e7-8c55-06c8781d1d0d.png)

And higher costs are actually negatively related to performance:
![download-3](https://user-images.githubusercontent.com/28814374/28677826-b3417640-72bc-11e7-84e6-8982c626644e.png)

## Any changes in direction or topic?
I am working on comparing returns, fees and asset allocations in one chart.
	
## Problems/Questions
The dataset is limited and I use asset allocation of 2016 even when comparing to returns over the last four years.
	
## Checklist
	
- [X] I have included my visuals
- [X] I have added writing about my topic
- [X] I have been updating my DIARY.md with details about my process
- [X] I have uploaded/updated any Jupyter Notebooks or other datasets into my code repository
- [] I have received two comments of peer feedback on my project update

**Comment by wonderfulexperience** [comment]
# Final

## Project visuals/text
I did an animation on a website.
https://wonderfulexperience.github.io/pensions/

<img width="558" alt="bildschirmfoto 2017-08-08 um 09 18 05" src="https://user-images.githubusercontent.com/28814374/29073680-8214149e-7c1a-11e7-92b4-808ac1398c3e.png">

## Details

**Headline:** 
Most pension funds are just too expensive

**Published website version:**
https://wonderfulexperience.github.io/pensions/

**Code repository:**
https://github.com/wonderfulexperience/data-studio-projects/tree/master/code/Project_2

**Final data set(s):** 
https://github.com/wonderfulexperience/data-studio-projects/tree/master/code/Project_2/pension%20funds%20data%20and%20pitch/pensionskassenvergleich

## What did you find to be the most difficult part of this project?

Doing an animation is hard.

## Are you satisfied with what you produced? Is there anything you would like to change or improve?

I didn't write an article with the animation, which could get deeper into my points. The animation itself doesn't look very professionally which would need more polishing.

## Checklist

- [X] I have included my visuals
- [X] I have posted my project to my project website
- [X] I have been updating my DIARY.md with details about my process
- [X] I have uploaded/updated any Jupyter Notebooks or other datasets into my code repository
