### ISSUE TITLE
Reading the subtext in SNB statements [Project]

### ISSUE THREAD

**Issue by simon-pinkmartini** [jsoma/data-studio-projects#53]
# Update

## Content
I did some more text analysis (all before we actually started to work with NLP programs in class...) and wrote a story that puts forward a clear argument: how the SNB tried to emphasize continuity in its communication, especially after the important policy event in 2011 (peg).

## Details
**Title:** For the Swiss National Bank, everything stays the same (except that it doesn't)
**URL:** http://165.227.144.49/snb-lagebeurteilungen/web/snb-communication.html
**Code:** https://github.com/simon-pinkmartini/studio-projects/tree/master/code/snb-lagebeurteilungen

## Problems and questions
* Obviously I would use some of the NLP libraries next time, instead of hand-writing all the functions myself. Before publishing, I might actually have to do this.
* Also, the graphics currently come as pure matplotlib output, no additional work done in Illustrator. Some annotations would be great inside the graphics, showing the moments of policy change.
* Last, I also have to get in touch with the SNB to see what they have to say about the analysis.

## Preview
![similarity](https://user-images.githubusercontent.com/28814395/28894873-3e3b764c-77a4-11e7-9bd5-d576b6f7c92e.png)

# Pitch

Reading the subtext in SNB statements

## Summary

The Swiss National Bank is Switzerland's most important economic policy maker. Over the last years, their politics has been a real roller-coaster ride, swinging from one stance to the opposite within days. At the same time, the communication of the SNB's ledership has always been somewhat cryptic. This is why I think it would be interesting to do a computer-based language analysis of all the SNB's policy statements going back to 2001 (the year when they adopted a new inflation-targeting framework that includes quarterly statements on their policy actions).

## Details

In the SNB's statements, which are usually 1 to 3 pages long, I will look at basic things like text length, average length of sentences and so on. The idea is to check whether there is a trend over time, whether there are outliers and whether I can make a link to actual economic and political events that occurred at a given moment of time. I will also look at the frequency of the words used and try to look for patterns there.

**Possible headline(s):** 
"What the SNB's president says without saying it"
"The SNB's linguistic struggle with stability"

**Data set(s):** 
All the statements can be downloaded from www.snb.ch. There are 4 statments per year. Over a period of 15 years, this gives a body of 60 texts to analyze.

**Code repository:** 
https://github.com/simon-pinkmartini/studio-projects/tree/master/code/snb-lagebeurteilungen
	
**Possible problems/fears/questions:** 
- My main fear is that I won't spot any patterns whatsoever over time. This would mean that my story is all about how constant/persistent/boring the SNB's communication is. Which is not sexy.
- In the second phase of the project, I want to check out some NLP libraries (natural language processing), but in German, not in English. This could be tricky.

## Work so far
* I scraped all the pdfs from the SNB's website. This didn't pose any problems. I used requests in combination with BeautifulSoup to do it.
* I extracted the actual statements from the pdfs using pdf2txt. This only worked partly fine. In some instances, the algorithm mixed up the word order. I had to correct this manually.
* I went over all texts with pandas/regex and removed all the junk lines, like letterheads and so on. This worked partly fine, as a lot of manual checking was necessary.
* I did some of the basic analysis described above (statement length, word frequencies). Some of the results are boring, but I found one interesting thing: over the years, the SNB has used some words more and more frequently that emphasize stability (words like "still", "stays", "unchanged", etc.). This is something I can discuss more deeply in the article.

## Screenshots
![index](https://user-images.githubusercontent.com/28814395/28577925-2848190a-7126-11e7-8bb3-50358edd6038.png)
![index2](https://user-images.githubusercontent.com/28814395/28577932-2aacd528-7126-11e7-813f-1941c9c38fca.png)
![index3](https://user-images.githubusercontent.com/28814395/28577936-2d7b5a22-7126-11e7-93f3-ae60bc33c082.png)

## Checklist

This checklist must be completed before you submit your draft.

- [x] I have already spent time with my data set, opening it, exploring it, etc
- [ ] I have created a "DIARY.md" file to save links and list all of the terrible, no good problems I come across
- [x] My issue issue has `[Project]` in the title
- [x] My issue links to my data set(s)
- [x] My issue links to my code repository
- [x] My issue explains what I'd like to explore in the data set
- [x] My issue includes images - either inspiration or what I've done so far
- [ ] I have received two comments of peer feedback on my pitch issue

**Comment by IoannisAntypas** [comment]
This is a great idea. I was actually interviewing the chief representative of the Swiss chamber of commerce in Brussels and he told me exactly the same thing, that the SNB is very austere with its communications especially when it comes to inflation targets, so I think there can be a very good story there.

Its also good that you have been very descriptive and open about what could go wrong because its not an easy task!

**Comment by wonderfulexperience** [comment]
Could you also look at terms which are consistent with the foreign exchange policy? How did the wording change after introducing the exchange rate floor to the Euro? And how did it change after the exchange rate floor was removed?

**Comment by Ediegram** [comment]
This is interesting; I like it. I suggest including a chart showing the interest rate over this time period (hint: it's a step!)
