### ISSUE TITLE
People Wrongly Convicted of Crimes [Project]

### ISSUE THREAD

**Issue by amandolinjames** [jsoma/data-studio-projects#54]
# Pitch
I'm researching who has been wrongly convicted for a crime, and then exonerated, or freed from jail, after new evidence showed misconduct, or proved someone's innocence in the case that made it clear that this person has been falsely accused and shouldn't serve time. 

## Summary
After DNA evidence started being used in 1989 to prove someone's evidence in a rape case in Chicago, hundreds of people have been acquitted of crimes they did not commit. What are the ages of people who are most often wrongly convicted? What is their race? What are the most popular states for wrong convictions? 

## Details

**Possible headline(s):** 
What do Exoneration Cases Have in Common? Most Wrongly Convicted Teenagers Are Black Males with Cases of Official Misconduct

**Data set(s):** 
http://www.law.umich.edu/special/exoneration/Pages/glossary.aspx
**Code repository:** 
[](https://github.com/amandolinjames/Data-Studio/tree/master/Code/Exonerations)

**Possible problems/fears/questions:** 
One challenge will be finding a new angle to this story, since it's a stereotype that young, black males are mistreated by police. I want to tell a story about exonerations that contributes something new to the conversation about mistrials, and there are a lot of options of angles to choose from. Some others I have considered: looking at where most cases of mistrials come from? (Harris County, Texas), looking at what is the average time spent in jail by someone who is later found innocent? What is the percentage of black males (and other races) convicted in each state, compared to the number of wrongful convictions by race in each state? This will include finding a second dataset that shows the number of people convicted in each state by race. 
## Work so far

![screen shot 2017-07-25 at 2 39 17 pm](https://user-images.githubusercontent.com/29207139/28588033-13afe6dc-7147-11e7-9d71-cf7dd9baf69e.png)

![screen shot 2017-07-25 at 2 40 22 pm](https://user-images.githubusercontent.com/29207139/28588058-3928601a-7147-11e7-84e4-a2fc9343fff0.png)

![screen shot 2017-07-25 at 2 40 51 pm](https://user-images.githubusercontent.com/29207139/28588081-4a4b19e6-7147-11e7-98a5-8edb1475d071.png)

![screen shot 2017-07-25 at 2 41 50 pm](https://user-images.githubusercontent.com/29207139/28588113-6e24c9d4-7147-11e7-8976-d91215177969.png)

![screen shot 2017-07-25 at 2 42 59 pm](https://user-images.githubusercontent.com/29207139/28588143-96e3da4a-7147-11e7-89c3-a50982f04391.png)

![screen shot 2017-07-25 at 2 43 26 pm](https://user-images.githubusercontent.com/29207139/28588155-a684115e-7147-11e7-9ff0-b9c6cc51de79.png)
![screen shot 2017-07-25 at 2 43 48 pm](https://user-images.githubusercontent.com/29207139/28588171-b15e5b3e-7147-11e7-89ab-96b182ee234c.png)

#Update

![screen shot 2017-07-28 at 10 30 51 am](https://user-images.githubusercontent.com/29207139/28721931-e2292390-737f-11e7-8609-2d54695b7c1b.png)
	
## Content

I decided to show the locations of places where the most exoneration cases originated because I noticed an interestingly high number in a specific county in Texas. 	

## Any changes in direction or topic?
I wanted to explore more about the use of DNA but was unable to find a good way to graph it. 
	
## Problems/Questions
Right now my graph feels basic, and I am still interested in charting something about the number of black teens wrongfully convicted in cases where there was official misconduct. 

## Checklist
	
- [x] I have included my visuals
- [x] I have added writing about my topic
- [x] I have been updating my DIARY.md with details about my process
- [x] I have uploaded/updated any Jupyter Notebooks or other datasets into my code repository
- [ ] I have received two comments of peer feedback on my project update

## Checklist

This checklist must be completed before you submit your draft.

- [x] I have already spent time with my data set, opening it, exploring it, etc
- [ ] I have created a "DIARY.md" file to save links and list all of the terrible, no good problems I come across
- [x] My issue issue has `[Project]` in the title
- [x] My issue links to my data set(s)
- [x ] My issue links to my code repository
- [x] My issue explains what I'd like to explore in the data set
- [x] My issue includes images - either inspiration or what I've done so far
- [ ] I have received two comments of peer feedback on my pitch issue

**Comment by edl2118** [comment]
Amanda, I think this is a really interesting data set. And, I like the state/county perspective that you're taking. It's interesting for me to see that Texas and Illinois have the greatest number of exonerations. Have you considered plotting the number of exonerations from DNA evidence over time? I'm curious to see what that trend looks like after 1989. Was it a sharp spike or more gradual? This may be outside of your data set but I also wondered what other evidence apart from DNA led to exonerations? Was the 449 from DNA evidence a small or large percentage of total evidence leading to exonerations? And what % of exonerations of black males were specifically due to DNA evidence? Was there something else that contributed to their exonerations? I feel this is such a relevant topic and I'm so excited to see how you will piece all this together in a visualization!
