### ISSUE TITLE
Adaptive strategies for African Farmers in response to climate change [project]

### ISSUE THREAD

**Issue by edl2118** [jsoma/data-studio-projects#55]
Please complete all of the following sections, or a robot will spookily dance around your issue! A completed version of this template can be found at https://github.com/jsoma/data-studio-projects/issues/1

# Pitch

## Summary

I was chatting with my Lyft driver and we got on the topic of climate change. It was an interesting conversation because he was pretty informed about all the media coverage on rising temperatures, melting ice caps and rising acidity in oceans. So, it wasn't for a lack of awareness that he didn't think of climate change as a critical issue for our time. He just wasn't connecting to the stories he was reading. 

This reminded me of an article I read a few years back in National Geographic about how climate change may have played a part in the Syrian refugee crisis. That journalistic piece stuck with me because up to then I hadn't really considered how climate was contributing to migrations which in turn could play a part in civil conflict. So, I started to wonder about other data sets that could provide a more personal look into how changes in climate might be impacting people's lives and livelihoods. 

## Details
I would like to explore the data from an agricultural survey coordinated by the Centre for Environmental Economics and Policy for Africa (CEEPA) and published by Nature in 2016. The CEEPA survey randomly sampled 9,597 households across eleven African countries between the growing seasons 2002/2003 or 2003/2004. Surveys were conducted as face-to-face interviews. 

While households were chosen randomly, the countries were chosen to represent the four sub-regions of Africa (East, West, North and Southern). And, the districts were selected to represent the different agro-ecological zones in a country:

![image](https://user-images.githubusercontent.com/28814369/28588256-fb71ac94-7147-11e7-82b4-c33f7aff0d79.png)

Waha, K. et al. An agricultural survey for more than 9,500 African households. Sci. Data 3:160020 doi:10.1038/sdata.2016.20 (2016).

My main research questions are:
1) What common strategies are farmers using to cope with perceived climate changes? 

2) Do strategies differ significantly when we step it out and look at climate changes that are perceived to be short-term, long-term, and extreme?

3) What's at stake? That is, what proportion of the farmers net income is from farming activities?

4) Time permitting, I'd like to see if actual reported temperatures fluctuated much in this period of the study 2002-2004. Households were asked about their perception of shifts in climate. It would be interesting to look at whether their were real shifts in climate during this period.

Some visualization ideas:
I would like to plot several simple bar charts in one space
![image](https://user-images.githubusercontent.com/28814369/28584536-15d97da8-713b-11e7-850e-8b86def5a53f.png)

**Possible headline(s):** 
What 9500 African Households Are Doing To Cope With Climate Change

**Data set(s):** 
http://dx.doi.org/10.6084/m9.figshare.c.1574094) 

**Code repository:** 
https://github.com/edl2118/studio-projects.git
	
**Possible problems/fears/questions:** 
Questions:
There are uncertainties in the data from Cameroon and Zimbabwe that require some choices to be made about whether to drop data from these two countries. We don't have any adaptation data for Cameroon so if my key focus is on adaptations, I should probably exclude them from my analysis altogether. And, some researchers chose to drop data for Zimbabwe maybe because there may be some confounding effects from the turbulent economic and political situation from that time. I will be excluding Cameroon and Zimbabwe from my analysis.

Fears: 
I fear there is not much of a story here. I was hoping there would be interview comments so I could better understand the personal stories but that's not the case. I worry that in the end, I'll just have a bunch of figures and the reader will feel no connection with the data.

Issues:
One of the problems I encountered right off the bat was just reading in the text file. With the help of a very patient classmate, I was able able to turn all these strange rows of characters into a workable data frame by adding <<encoding='MY_ENCODING'>> to the code I was using:
![image](https://user-images.githubusercontent.com/28814369/28590426-191565e4-7150-11e7-9332-4d68221bbd45.png)

## Work so far
-Some preliminary exploration of the data set
-Reading the survey manual and metadata to better understand the data collection process
-I'm in the process of cleaning the data and will need to address the n/a, NaN values as well as use open refine to clean things up

## Checklist

This checklist must be completed before you submit your draft.

- [x] I have already spent time with my data set, opening it, exploring it, etc
- [ ] I have created a "DIARY.md" file to save links and list all of the terrible, no good problems I come across
- [x] My issue issue has `[Project]` in the title
- [x] My issue links to my data set(s)
- [x] My issue links to my code repository
- [x] My issue explains what I'd like to explore in the data set
- [x] My issue includes images - either inspiration or what I've done so far
- [ ] I have received two comments of peer feedback on my pitch issue

**Comment by edl2118** [comment]
# Update
	
## Content
Analysis of CEEPA’s results suggests that a significant number of farmers are not implementing any adaptation strategy. While we would expect that most are choosing not to do anything differently in the short term, surprisingly they report not to have an adaptation strategy even when climate changes are perceived to be longer term issues:

![ceepa_draft2](https://user-images.githubusercontent.com/28814369/28900309-4e41d012-77be-11e7-995b-766534489089.gif)

	
## Any changes in direction or topic?
Yes, I waffled back and forth a lot about where to take the story. I think my mistake was in not having a clear point of view in the beginning and I was just kind of exploring the data and seeing where it would take me. I thought there would be some interesting strategies rising to the surface but in the end the most common adaptation strategy was having no adaptation strategy. So I pivoted and tried to figure out why that was. Was it because of subsidies? Was it the size of the farm? Did it have something to do with the extension workers who may/may not have given any advice? 

I thought that the subsidies angle was interesting because it kind of suprised me. I thought we would see a higher percentage of farmers adopting more climate strategies if they received funds but that wasn't the case.

	
## Problems/Questions
It's not clear from this dataset what the constraints are for farmers to adopt climate strategies. The only question asked in the survey was about constraints for short term climate change and there the #1 answer was no constraints followed by #2 not enough funds. Probably delving into other data sets about constraints perhaps in machines or labor or the amount of the subsidies could shed some light.

## Checklist
	
- [x] I have included my visuals
- [x] I have added writing about my topic
- [ ] I have been updating my DIARY.md with details about my process
- [x] I have uploaded/updated any Jupyter Notebooks or other datasets into my code repository
- [ ] I have received two comments of peer feedback on my project update

**Comment by sarahslo** [comment]
This is good work. You started out with a very ambitious set of questions, one that the data was not going to be able to answer. And you found that out. Which is really what happens a lot with data! It's an anarchist. You made the right call by dropping Cameron and Zimbabwe. You were right to be cautious about political and economic factors that could have an impact of the data.

And, you found something that surprise you in the data - the subsidies. So in the end, you found a story but it was not the one that you expected. Still, you managed to make a point with it. So I see this as a complete success.

Once you see what the data actually brings, the next step is to embrace it. Work WITH what you have and not against it. Something that is here that you have not noticed is that while the majority of farmers are doing nothing, those that are most active have changed their planting strategy. That is something you could have pursued more in you were looking for another angle.

But overall, this is a very good job. You had a lot of problems including scraping and you stuck with it and I think with a headline that says, emergency is on the way and farmers are not taking action -- it is an emotional story in the end.

Give yourself credit.
