### ISSUE TITLE
Cancer rates [Project]

### ISSUE THREAD

**Issue by JulienAssouline** [jsoma/data-studio-projects#56]
Please complete all of the following sections, or a robot will spookily dance around your issue! A completed version of this template can be found at https://github.com/jsoma/data-studio-projects/issues/1

# Pitch
I was on Twitter when the news about John McCain's cancer broke. Cancer has been a prevalent topic around my family, because, we've been affected by cancer over the past few years. I know that we are not alone, however, as just about everyone has been affected by cancer in some shape or form. 

I was, therefore, interested in examining how many people are affected by cancer every year. The trends in cancer deaths, and which cancer types are the most common.

## Summary
Thus far I've been able to find that cancer is the second most common leading cause of death in the US. But, cancer deaths are decreasing dramatically every year. Fewer people are also getting diagnosed with cancer. 

I have been able to find data on where the US ranks among other countries and plan on analyzing that data as well, because even though their cancer death rates are on the decline, they still may have a lot of cancer cases compared to other countries. 
## Details

**Possible headline(s):** The Decline in Cancer Deaths

**Data set(s):** https://seer.cancer.gov/csr/1975_2014/browse_csr.php?sectionSEL=2&pageSEL=sect_02_table.07.html

https://www.cancer.gov/types/common-cancers

http://www.wcrf.org/int/cancer-facts-figures/data-cancer-frequency-country

https://wonder.cdc.gov/controller/datarequest/D77;jsessionid=09D79FE8D56EA0934606A32282BA912F

**Code repository:**  https://github.com/JulienAssouline/data-studios-projects/blob/master/code/Project%203/Cancer%20Rates.ipynb
	
**Possible problems/fears/questions:**  I'm not entirely sure how to visualize some of the data. The trend data will obviously be a line chart, but the causes of deaths, for example, is a little more tricky. I could probably simply make a bar chart, but I'd like to try to come up with something a little more creative, but that should also be appropriate. 

I would also love to find out why the trend is happening but it could be hard to prove because there's probably a lot of factors that go into it. 

## Work so far 
![screen shot 2017-07-26 at 7 43 19 pm](https://user-images.githubusercontent.com/17466947/28648286-c3bc3a3c-723a-11e7-9e0c-93d06d56a44a.png)

![screen shot 2017-07-26 at 7 43 29 pm](https://user-images.githubusercontent.com/17466947/28648290-c8a7d15a-723a-11e7-8bf8-69577643c988.png)

## Checklist

This checklist must be completed before you submit your draft.

- [x] I have already spent time with my data set, opening it, exploring it, etc
- [ ] I have created a "DIARY.md" file to save links and list all of the terrible, no good problems I come across
- [x] My issue has `[Project]` in the title
- [x] My issue links to my data set(s)
- [x] My issue links to my code repository
- [x] My issue explains what I'd like to explore in the data set
- [x] My issue includes images - either inspiration or what I've done so far
- [ ] I have received two comments of peer feedback on my pitch issue

**Comment by JulienAssouline** [comment]
# Update

## Content
![cancer-is-the-second-leading-cause-of-death-in-the-us 1](https://user-images.githubusercontent.com/17466947/28756149-bae99522-7536-11e7-824e-4e67e09d5f45.gif)


![cancer-deaths-are-declining-dramatically-in-the-us](https://user-images.githubusercontent.com/17466947/28756124-6ee38386-7536-11e7-9c64-dd8f12c576ec.png)

![fewer-people-are-getting-diagnosed-with-cancer](https://user-images.githubusercontent.com/17466947/28756128-74ed267e-7536-11e7-80d2-37852d285378.png)

Just about everyone is affected by cancer, one way or another. It's the second leading cause of death in the US, just under heart disease, killing just under 600,000 people in 2015. Heart disease and cancer are by orders of magnitude the most common causes of deaths in the United States. But, on the cancer front, progress is being made. 

Since it's peak in 1991, the rate of people who have died from cancer has been steadily dropping every single year. 

In fact, since 1991, the rate of people who have died from cancer has dropped by 25 percent. Plus, the number of people who are getting diagnosed with cancer has also dropped since it hit its peak in 1992. 

The rate of cancer diagnoses hasn't dropped as much as the rate of cancer deaths, but there's some good news with that. It basically means that we're getting better at treating cancer. 

## Any changes in direction or topic?
Yes, I'm going to focus more of the difference between the number of people diagnosed and the number of deaths in cancer. I think the idea that more people are surviving cancer is a more interesting story. I have also been able to find data the most common cancer types, by how many people are getting diagnosed and how many people are dying from those cancer rates. 
## Problems/Questions
I still need to change the scales, and tick marks on my line charts. I could do this in ggplot2 and D3 easily, but I'd like to figure out how to do this in illustrator, to become better with the tool. 

It would also be great to talk to someone and find out why this trend is happening and what have been the biggest breakthroughs in cancer research. 

Code: https://github.com/JulienAssouline/data-studios-projects/tree/master/code/Project%203
## Checklist
	
- [x] I have included my visuals
- [x] I have added writing about my topic
- [x] I have been updating my DIARY.md with details about my process
- [x] I have uploaded/updated any Jupyter Notebooks or other datasets into my code repository
- [ ] I have received two comments of peer feedback on my project update

**Comment by qdinhbui2** [comment]
` I think the idea that more people are surviving cancer is a more interesting story.`

That is a much better story. I would focus on that. Maybe look at the trends of survival by type of cancer.

**Comment by sarahslo** [comment]
i'm curious here about the 'as compared to what'. cancer deaths are declining, what about heart disease? or accidents? alzheimers? diabetes?

or, what about the different types of cancer?  it's worth looking at men vs women, to capture breast cancer and prostate cancer. is there a way to look at the likelihood of developing a certain type of cancer, your survival chances/rate and then deaths over time. 

lots of ways to play with this data.

![screen shot 2017-08-14 at 9 23 28 pm](https://user-images.githubusercontent.com/659014/29298611-1c642360-8137-11e7-91a3-4e0761bb9218.png)
