### ISSUE TITLE
The most underpaid players in the NHL [Project]

### ISSUE THREAD

**Issue by peterjost** [jsoma/data-studio-projects#57]
# Pitch

## Summary
With total earnings of $14,000,000 per year Los Angeles Anze Kopitar is the best paid professional hockey player of the world. But is he worth the money? Or are there some other players in the NHL who score better for less money?

## Details
The National Hockey League, the best hockey league allover the world, releases a bunch of statistics around the league and their players - including scoring and salary. I want to explore this data to find the most value players of the league.

**Possible headline(s):** 
Connor McDavid - the most underpaid player in hockey history
This hockey player blames Kopitar, Crosby & Co.

**Data set(s):** 
http://www.hockeyabstract.com/testimonials/nhl2016-17playerdata

**Code repository:** 
https://github.com/peterjost/studio-projects
	
**Possible problems/fears/questions:** 

## Work so far

![image](https://user-images.githubusercontent.com/28814371/28648429-c668409a-723b-11e7-887d-09769d9b4373.png)

![image](https://user-images.githubusercontent.com/28814371/28793194-359ac394-7600-11e7-94d2-1766bee7e25e.png)

![image](https://user-images.githubusercontent.com/28814371/28793156-1897da70-7600-11e7-952c-96aa5542fd5c.png)

Explored the data, cleaned the data a bit, searched for some quick wins.
To get a first impression: In 2016/17 Connor McDavid got paid $9,250 per point - Carl Soderberg, also a forward with the same number of games, got paid $339,285 for every single point...

## Checklist

This checklist must be completed before you submit your draft.

- [x] I have already spent time with my data set, opening it, exploring it, etc
- [x] I have created a "DIARY.md" file to save links and list all of the terrible, no good problems I come across
- [x] My issue issue has `[Project]` in the title
- [x] My issue links to my data set(s)
- [x] My issue links to my code repository
- [x] My issue explains what I'd like to explore in the data set
- [x] My issue includes images - either inspiration or what I've done so far
- [ ] I have received two comments of peer feedback on my pitch issue

**Comment by chrgavalas** [comment]
I love sports stories! But I don't really know hockey and the little details that determine who's good or not so good. If the scoring data is enough to make the correlation then that's clearly fine and the story is solid and great! But my hunch is that other player attributes will be playing a role... Great idea!

**Comment by peterjost** [comment]
# Update
	
## Content
	

![image](https://user-images.githubusercontent.com/28814371/29080729-8c5ab228-7c2e-11e7-8893-e6e77c5fcd50.png)

![image](https://user-images.githubusercontent.com/28814371/29080905-14931a90-7c2f-11e7-8973-e38e991e3521.png)

![image](https://user-images.githubusercontent.com/28814371/29080798-c3e30ce0-7c2e-11e7-8676-697c4c20f1c4.png)

![image](https://user-images.githubusercontent.com/28814371/29082917-0fa8ea86-7c35-11e7-9d64-86b3174f2d8e.png)

![image](https://user-images.githubusercontent.com/28814371/29081875-d0960746-7c31-11e7-9de8-e4da8ae06dff.png)

![image](https://user-images.githubusercontent.com/28814371/29081643-187c71fe-7c31-11e7-978f-51b2676a9a6b.png)



**
## Any changes in direction or topic?
No major changes.

## Problems/Questions
	
## Checklist
	
- [x] I have included my visuals
- [x] I have added writing about my topic
- [x] I have been updating my DIARY.md with details about my process
- [x] I have uploaded/updated any Jupyter Notebooks or other datasets into my code repository
- [ ] I have received two comments of peer feedback on my project update
