### ISSUE TITLE
Visualizing Water Stress Change in Each Country [Project]

### ISSUE THREAD

**Issue by SYChJung** [jsoma/data-studio-projects#58]
Please complete all of the following sections, or a robot will spookily dance around your issue! A completed version of this template can be found at https://github.com/jsoma/data-studio-projects/issues/1

# Pitch
Visualizing Water Stress Change in Each Country

## Summary
For my second project, I am going to visualize water stress changes for each country according to various criteria.

## Details
WRI (World Resources Institute) made a dataset about future water stress in 167 countries for 2020, 2030, and 2040. I want to reorganize the dataset and visualize it to show the water stress changes of each country according to various criteria: All sectors, industrial, domestic, agricultural; optimistic and pessimistic estimations.
![water_stress_world_map_webready](https://user-images.githubusercontent.com/28815149/28750299-ed831a0e-74b3-11e7-931a-3b3c2e77834e.jpg)

**Possible headline(s):** 
- Visualizing Water Stress Change in Each Country

**Data set(s):** 
- Aqueduct Projected Water Stress Country Rankings, WRI (http://www.wri.org/resources/data-sets/aqueduct-projected-water-stress-country-rankings)

**Code repository:** 
- https://github.com/SYChJung/studio-projects/tree/master/code/project2

**Possible problems/fears/questions:** 

## Checklist

This checklist must be completed before you submit your draft.

- [x] I have already spent time with my data set, opening it, exploring it, etc
- [x] I have created a "DIARY.md" file to save links and list all of the terrible, no good problems I come across
- [x] My issue issue has `[Project]` in the title
- [x] My issue links to my data set(s)
- [x] My issue links to my code repository
- [x] My issue explains what I'd like to explore in the data set
- [x] My issue includes images - either inspiration or what I've done so far
- [x] I have received two comments of peer feedback on my pitch issue

**Comment by SYChJung** [comment]
# Draft
I organized a dataset of water stress, and I’m using D3.js to plot the changes over time.

## Content
I organized the dataset of water stress changes of each country according to various criteria: All sectors, industrial, domestic, agricultural water stress; optimistic and pessimistic estimations.

This is the link to the dataset I made.
- https://github.com/SYChJung/studio-projects/tree/master/code/project2

This is a chart about industrial water stress changes between 2020 and 2040, in an optimistic projection.
![industrial_op](https://user-images.githubusercontent.com/28815149/28757324-635b37d0-754e-11e7-997f-7ccdf0e92382.png)


## Any changes in direction or topic?


## Problems/Questions
I can plot the graph with pandas. I am trying to replicate that structure with D3.js.


## Checklist
	
- [x] I have included my visuals
- [x] I have added writing about my topic
- [x] I have been updating my DIARY.md with details about my process
- [x] I have uploaded/updated any Jupyter Notebooks or other datasets into my code repository
- [ ] I have received two comments of peer feedback on my project update

**Comment by wonderfulexperience** [comment]
This is a very relevant topic. I am wondering what kind of story you want to tell. Maybe you can make it clearer to the reader why he should be interested and focus his attention on a few countries which will suffer the most?

**Comment by qdinhbui2** [comment]
You need to explain clearly upfront in your pitch what water stress is and why it is important. I don't really know what the story is about. If there is a simple explanation to the idea, then you can focus in on a better headline. If you're doing two points in time, I would think about doing a slope chart.

**Comment by SYChJung** [comment]
# Revision
I have visualized water stress data pertaining to all sectors.

## Content
I used D3.js to plot the general water stress of all sectors. It shows the water stress projection changes from 2020 to 2040. Now I am going to add tooltips for more information and make the charts for the other 11 datasets.

This is the link to the html file I made.
- https://github.com/SYChJung/studio-projects/tree/master/code/project2

This is a screenshot of my visualization (in progress)
![screencapture-file-users-s-desktop-studio-projects-code-project2-d3_water_stress-html-1501636585663](https://user-images.githubusercontent.com/28815149/28853471-b96f89f8-76fe-11e7-8892-3ac25ed54183.png)

## Any changes in direction or topic?
Nope.

## Problems/Questions


## Checklist
[x] I have included my visuals
[ ] I have added writing about my topic
[x] I have been updating my DIARY.md with details about my process
[x] I have uploaded/updated any Jupyter Notebooks or other datasets into my code repository
[ ] I have received two comments of peer feedback on my project update

**Comment by SYChJung** [comment]
# Final

## Project visuals/text
I made four charts according to four different areas that may experience water stress: All sectors, industrial, domestic, and agricultural. For each chart I presented 10 countries: five countries with the greatest business-as-usual water stress increases and five countries with the greatest business-as-usual water stress decreases. Each country has nine dots representing business-as-usual, optimistic, and pessimistic water stress estimations in 2020, 2030, and 2040.

If you move your mouse over the box, more information shows up: name of the country, optimistic water stresses in 2020, 2030, and 2040; Business-as-usual water stresses in 2020, 2030, and 2040; pessimistic water stresses in 2020, 2030, and 2040; and water stress change from 2020 to 2040.
![project2-d3_water_stress-screenshot](https://user-images.githubusercontent.com/28815149/28992632-d50d0f1e-796f-11e7-8254-3af9595e68cf.png)

## What did you find to be the most difficult part of this project?

## Details
Headline : Visualizing Water Stress Change in Each Country

Published website version :  https://rawgit.com/SYChJung/studio-projects/master/code/project2/D3_water_stress.html

Code repository : https://github.com/SYChJung/studio-projects/tree/master/code/project2

Final data set(s) : https://github.com/SYChJung/studio-projects/blob/master/code/project2/Visualizing_Water_Stress_Change_in_Each_Country.ipynb


## Are you satisfied with what you produced? Is there anything you would like to change or improve?

## Checklist
[x] I have included my visuals
[x] I have posted my project to my project website
[x] I have been updating my DIARY.md with details about my process
[x] I have uploaded/updated any Jupyter Notebooks or other datasets into my code repository

**Comment by sarahslo** [comment]
this is beautiful and interesting but i don't know what it is telling me because there is no key that says which country is which color, i assume these are changes year to year but there are no year labels and there are no labels on the numbers so i don't know what is being measure or the measure of each chart.

take the step to add these labels so we can look at this at get it quickly. the explanation in words should be an added bonus to the visual story, not the main way we understand it.

keep going!
