### ISSUE TITLE
EU Commissioners' lobby meetings [Project]

### ISSUE THREAD

**Issue by marcelpauly** [jsoma/data-studio-projects#59]
# Pitch

## Summary

Since December 2014 the EU Commissioners and their teams have to publish information on meetings held with lobbyists. [Transparency International gathers this data](http://www.integritywatch.eu/ec.html) and adds information on the companies and organisations.

<img width="1159" alt="bildschirmfoto 2017-07-30 um 13 29 00" src="https://user-images.githubusercontent.com/7937281/28755527-1e3a83cc-752b-11e7-9621-aaa0e59753bb.png">

Beyond Transparency's standard diagrams I'd like to analyse who meets the most/the least NGOs and which Commissioner has the most meetings by himself/herself (instead of his/her team).

## Details

**Possible headline(s):** These EU Commissioners listen to the economy the most

**Data set(s):** [Transparency International](http://www.integritywatch.eu/ec.html) ([CSVs](https://github.com/marcelpauly/data-studio-projects/tree/master/code/lobby_meetings/data))

**Code repository:** https://github.com/marcelpauly/data-studio-projects/tree/master/code/lobby_meetings
	
**Possible problems/fears/questions:** –

## Work so far

I downloaded, opened, cleaned and merged the datasets.

## Checklist

This checklist must be completed before you submit your draft.

- [x] I have already spent time with my data set, opening it, exploring it, etc
- [x] I have created a "DIARY.md" file to save links and list all of the terrible, no good problems I come across
- [x] My issue issue has `[Project]` in the title
- [x] My issue links to my data set(s)
- [x] My issue links to my code repository
- [x] My issue explains what I'd like to explore in the data set
- [x] My issue includes images - either inspiration or what I've done so far
- [ ] I have received two comments of peer feedback on my pitch issue

**Comment by IoannisAntypas** [comment]
Excellent idea, I think you could also compare somehow how close are those meetings to their role. Does Dimitris Avramopoulos (migration) meet mostly migration related lobbyists? How close to the agenda of Günther Oettinger (Budget and Human Resources)  are his meetings?

**Comment by marcelpauly** [comment]
# Update

## Content

I played with the data and built a graph with the 20 EU Commission cabinets which had the most lobby meetings (12/2014-07/2017). It shows both the total number of meetings and the shares by type of the lobby groups:

![lobby](https://user-images.githubusercontent.com/7937281/28904456-03000a86-77d9-11e7-9544-dda66eca542a.png)

## Any changes in direction or topic?

No, but I'm still working on a graph that shows the frequency of a cabinet's or a lobby group's meetings.

## Problems/Questions

How do I align stuff when I have an overlap on one side (like above on the right because of the x-axis label "100%")?

How do I find **nice** colors?

## Checklist

- [x] I have included my visuals
- [x] I have added writing about my topic
- [x] I have been updating my DIARY.md with details about my process
- [x] I have uploaded/updated any Jupyter Notebooks or other datasets into my code repository
- [ ] I have received two comments of peer feedback on my project update

**Comment by marcelpauly** [comment]
# Update

## Content

In the first chart I changed the colors, corrected the squares' sizes and rearrange the elements:

![lobby](https://user-images.githubusercontent.com/7937281/29046486-ae833fe4-7b95-11e7-881e-8d567fe0cec9.png)

I also created a second chart about the different cabinets' frquencies of meeting loby groups:

![frequency](https://user-images.githubusercontent.com/7937281/29046490-b3c71e9e-7b95-11e7-8e18-4078f2a285bb.png)

## Any changes in direction or topic?

nope

## Problems/Questions

not so far

## Checklist
	
- [x] I have included my visuals
- [x] I have added writing about my topic
- [x] I have been updating my DIARY.md with details about my process
- [x] I have uploaded/updated any Jupyter Notebooks or other datasets into my code repository
- [ ] I have received two comments of peer feedback on my project update

**Comment by qdinhbui2** [comment]
I like the remake of your chart. The one with the small lines. Unfortunately, despite being more visually appealing it actually contains less information for the reader. 

The first chart is a good start, but I don't believe the total meetings blocks are working for me. If you want to add one more dimension of data, you can scale the width of your bar chart according to how large each group is. Like this

<img width="706" alt="screen shot 2017-08-08 at 9 23 59 pm" src="https://user-images.githubusercontent.com/2335575/29101398-f609bc90-7c7f-11e7-83af-a91a732fa935.png">

Lastly, it's a fine chart but I don't really see the angle of the story yet. You need to clearly make a case. Are meetings with lobbyists a bad thing? A good thing? Both? What is the angle?

**Comment by qdinhbui2** [comment]
Also when you scale the bars, make sure you rearrange the bars according to most meetings to fewest meetings.

**Comment by marcelpauly** [comment]
# Final

## Project visuals/text

Thanks a lot, @qdinhbui2, I tried to adopt your suggestions. Here we go:

![lobby](https://user-images.githubusercontent.com/7937281/29145666-0b5cfcf4-7d2c-11e7-800b-8314e9e09b92.png)

## Details

**Headline:** Brussels' influencers

**Published website version:** https://marcelpauly.github.io/data-studio-projects/lobby_meetings/

**Code repository:** https://github.com/marcelpauly/data-studio-projects/tree/master/code/lobby_meetings

**Final data set(s):** https://github.com/marcelpauly/data-studio-projects/tree/master/code/lobby_meetings/data

## What did you find to be the most difficult part of this project?

To come up with a clear visual idea that supports the story I wanted to tell.

## Are you satisfied with what you produced? Is there anything you would like to change or improve?

There are still small things in the visual I'm not happy with, like the "tape lines" on the bars. But I can't come up with something better.

## Checklist

- [x] I have included my visuals
- [x] I have posted my project to my project website
- [x] I have been updating my DIARY.md with details about my process
- [x] I have uploaded/updated any Jupyter Notebooks or other datasets into my code repository
