### ISSUE TITLE
How Local Is Local News? [Project]

### ISSUE THREAD

**Issue by maijaliisa** [jsoma/data-studio-projects#60]
Please complete all of the following sections, or a robot will spookily dance around your issue! A completed version of this template can be found at https://github.com/jsoma/data-studio-projects/issues/1

# Pitch
How local is local news? I want to look at the Front Page of the AJC over the year and sort by topic. I believe this will show some interesting trends in how a regional newspaper covers local/national news.

I am particularly interested in comparing headlines based on US political topics (from 2012-2016) 
## Summary
The AJC is the largest newspaper in Metro Atlanta and one of the biggest regional paper in the country. Looking at how it covers local vs. national politics could show some interesting trends in national politics. 

## Details

**Possible headline(s):** 
-How local is local news? 
-All politics is...national? - The trend away from local coverage in regional newspapers 

**Data set(s):** 
https://global.factiva.com/ha/default.aspx#./!?&_suid=150145385581209692197847142947
**Code repository:** 
https://github.com/maijaliisa/studio-projects/tree/master/code/AJCPAGE1 
**Possible problems/fears/questions:** 
-Keeping everything in the scope of finishing within one week 
## Work so far
-Found all of the data I need and converted it into csv formats 
## Checklist

This checklist must be completed before you submit your draft.

- [X] I have already spent time with my data set, opening it, exploring it, etc
- [X] I have created a "DIARY.md" file to save links and list all of the terrible, no good problems I come across
- [X] My issue issue has `[Project]` in the title
- [X] My issue links to my data set(s)
- [X] My issue links to my code repository
- [X] My issue explains what I'd like to explore in the data set
- [X] My issue includes images - either inspiration or what I've done so far
- [ ] I have received two comments of peer feedback on my pitch issue

[screen shot 2017-07-30 at 7 59 21 pm](https://user-images.githubusercontent.com/28814389/28759104-c97f3c4c-7566-11e7-8d6e-3173ffac4759.png)

**Comment by amandolinjames** [comment]
LOVE this idea. I wondered where you found the dataset but when I clicked the link it didn't work. Where did you find it? Do they have it for other states? 

I think it's an awesome idea to focus on one area, like Atlanta, instead of being more broad. I also am excited to see the graphs and see how bad the drop in local coverage has been. Are you looking at solely print- or print and TV?

**Comment by wonderfulexperience** [comment]
Would be great to show categories for national / local topics to illustrate the trends. Maybe there is a specific national topic which drew away all the attention from local topics? And maybe some local topics are still covered extensively (and other local topics suffered)?

**Comment by maijaliisa** [comment]
# Update
I found some interesting trends in just the shear number of political stories that ran in the AJC...so I am going in the direction of "wow, local news is covering politics a lot more. What is behind this trend?" 
	
## Content
Draft here: https://maijaliisa.github.io/studio-projects/a-very-cool-project/GitHubAJCFrontPage/ 
	
## Any changes in direction or topic?
	
## Problems/Questions
I am still not really happy with the graphics...simple line graphs seem not all that interesting. I am also trying to figure out the margins on the page because the spacing is a little distracting. 
	
## Checklist
	
- [X] I have included my visuals
- [X] I have added writing about my topic
- [X] I have been updating my DIARY.md with details about my process
- [X] I have uploaded/updated any Jupyter Notebooks or other datasets into my code repository
- [ ] I have received two comments of peer feedback on my project update
