### ISSUE TITLE
Visualizing Bird Breeding Behavior [Project]

### ISSUE THREAD

**Issue by SYChJung** [jsoma/data-studio-projects#61]
Please complete all of the following sections, or a robot will spookily dance around your issue! A completed version of this template can be found at https://github.com/jsoma/data-studio-projects/issues/1

# Pitch
Visualizing Bird Breeding Behavior

## Summary
For my third project, I am going to visualize data on breeding birds

## Details
I found a fun dataset: “New York State’s first and second breeding bird atlases documented the distribution of the state’s avifauna during two distinct time periods: 1980-1985 and 2000-2005.” I want to analyze and visualize this data. I am particularly interested in seeing how breeding behavior is related to species, and if and how they change over the years.

**Possible headline(s):** 
- Bird Breeding Behavior (I’m working on it)

**Data set(s):** 
- Breeding Bird Atlases (https://catalog.data.gov/dataset/breeding-bird-atlases)

**Code repository:** 
	
**Possible problems/fears/questions:** 

## Checklist

This checklist must be completed before you submit your draft.

- [x] I have already spent time with my data set, opening it, exploring it, etc
- [x] I have created a "DIARY.md" file to save links and list all of the terrible, no good problems I come across
- [x] My issue issue has `[Project]` in the title
- [x] My issue links to my data set(s)
- [x] My issue links to my code repository
- [x] My issue explains what I'd like to explore in the data set
- [x] My issue includes images - either inspiration or what I've done so far
- [ ] I have received two comments of peer feedback on my pitch issue

**Comment by wonderfulexperience** [comment]
This could be very complex as there are many different kind of birds. Maybe you can focus on a specific bird? I am not sure yet how you want to visualize it?

**Comment by SYChJung** [comment]
# Draft
I made a dataframe of breeding behaviors by each kind of bird, and I’m using D3.js to plot the data.

## Content
I organized the Breeding Bird Atlases dataset into a dataframe of breeding behaviors by each kind of bird. With this I will use D3.js to make a graph showing the number of birds for each breeding behavior. The numbers of birds will be represented by circles; the bigger the circle is, the greater the number.

This is the link to the dataframe I made.
- 


## Any changes in direction or topic?
Nope.

## Problems/Questions
I am trying to find the right way to write the D3 code for the job.

## Checklist
[x] I have included my visuals
[x] I have added writing about my topic
[x] I have been updating my DIARY.md with details about my process
[x] I have uploaded/updated any Jupyter Notebooks or other datasets into my code repository
[ ] I have received two comments of peer feedback on my project update

**Comment by qdinhbui2** [comment]
I don't know if you have a story yet. You need to do more exploring before you decide what kind of product you want to make. You have two distinct time periods 1980-1985 and 2000-2005, which is unfortunate because 2005 is still quite old data, so I'm not sure if readers would find this particularly interesting.

I would say explore the data and look for distinct changes over time. Don't spend more than 3 hours on it. If you don't find anything really interesting (and I mean REALLY interesting), move on and try a different idea.

**Comment by SYChJung** [comment]
# Revision
I have visualized the number of birds by breeding behavior and by kind of bird

## Content
The size of each circle represents the number of birds corresponding to the breeding behavior and kind of bird. Now I am going to add tooltips for more information and other features.

This is the link to the html file I made.
- https://github.com/SYChJung/studio-projects/tree/master/code/project3

This is a screenshot of my visualization (in progress)
![breeding_df-html-1502160320312](https://user-images.githubusercontent.com/28815149/29054429-268d2e36-7bc4-11e7-9bc8-79e7ffcb868b.png)


## Any changes in direction or topic?
Nope.

## Problems/Questions


## Checklist

[x] I have included my visuals
[x] I have added writing about my topic
[x] I have been updating my DIARY.md with details about my process
[x] I have uploaded/updated any Jupyter Notebooks or other datasets into my code repository
[ ] I have received two comments of peer feedback on my project update

**Comment by SYChJung** [comment]
# Final

## Project visuals/text
This is a graph showing the number of birds according to their breeding behavior and species. The size of each circle represents the number of birds in each category. 
New York State’s breeding bird atlases record bird sightings in the state from 1980 to 1985 and from 2000 to 2005. Each record contains information about the location where the bird was sighted, the observer, the year of observation, etc. Among these, the information about the breeding behaviors and the kinds of birds interested me most. 
If you move your cursor over the circle, you can see more information: number of birds, kind of bird, bird breeding behavior. 
![project3-breeding_df-html-1502508807329](https://user-images.githubusercontent.com/28815149/29237547-671dda86-7eee-11e7-9a95-c50b811ff650.png)

## What did you find to be the most difficult part of this project?

## Details

Headline : Bird_Breeding_Behavior

Published website version : https://rawgit.com/SYChJung/studio-projects/master/code/project3/Breeding_df.html

Code repository : https://github.com/SYChJung/studio-projects/blob/master/code/project3/Breeding_df.html

Final data set(s) : https://github.com/SYChJung/studio-projects/blob/master/code/project3/Breeding_df.csv


## Are you satisfied with what you produced? Is there anything you would like to change or improve?

## Checklist

[x] I have included my visuals
[x] I have posted my project to my project website
[x] I have been updating my DIARY.md with details about my process
[x] I have uploaded/updated any Jupyter Notebooks or other datasets into my code repository
