### ISSUE TITLE
Under president Temer, had the 'secret' expenses of the Brazilian government increased? [Project]

### ISSUE THREAD

**Issue by RodrigoMenegat** [jsoma/data-studio-projects#63]
# Pitch
Under president Temer, has the 'secret' expenditures of the Brazilian government increased?

## Summary
Most of the expenditures made by the Brazilian federal government can be traced back in the Portal da Transparência ("Transparency Portal"), a website that displays all the spending in detail. Nevertheless, some part of it is untraceable: ATM cash withdrawals made with government-sponsored credit-cards (see [this other pitch](https://github.com/jsoma/data-studio-projects/issues/49) for more details about thouse nasty things) and any spending that is offciaily declared confidential by the government - a category that may include from presidential dinners to guns bought by the armed forces. 

I want to see how much of the total expenditures this secret spendings represent and how this share changes over time.

## Details

**Possible headline(s):** 
Under Temer, secret spendings of Brazilian government rose xx%

**Data set(s):** 
There are three sets of .csv files I have to work with:
- Direct payments made by government agencies: 
http://transparencia.gov.br/downloads/mensal.asp?c=GastosDiretos
- Payments made with government-sponsored credit carts:
http://transparencia.gov.br/downloads/mensal.asp?c=CPGF
- Payments made by a central agency responsible for buying plane tickets and similar goods:
http://transparencia.gov.br/downloads/mensal.asp?c=CPGFComprasCentralizadas

**Code repository:** 
https://github.com/RodrigoMenegat/studio-projects/tree/master/code/temer-spending

**Possible problems/fears/questions:** 
My only fear is not finding any significant change in secret spending over time. Then, time to find another pitch...

## Work so far
Downloaded all the avaliable .csv files and merged them into a single one using the command line.

## Checklist
- [x] I have already spent time with my data set, opening it, exploring it, etc
- [x] I have created a "DIARY.md" file to save links and list all of the terrible, no good problems I come across
- [x] My issue issue has `[Project]` in the title
- [x] My issue links to my data set(s)
- [x] My issue links to my code repository
- [x] My issue explains what I'd like to explore in the data set
- [ ] My issue includes images - either inspiration or what I've done so far
- [ ] I have received two comments of peer feedback on my pitch issue

**Comment by ElisaHarlan** [comment]
This is a great idea! Maybe you could not only concentrate on the amount of money they were spending, but on the different categories they were spending money on.. This could also be very interesting.

**Comment by RodrigoMenegat** [comment]
No story here. Issue closed!
