### ISSUE TITLE
Mapping homeless people [Project]

### ISSUE THREAD

**Issue by cathrinesot** [jsoma/data-studio-projects#65]
# Pitch

## Summary

I want to make a project about homeless people in the US. The focus will be on their age and the areas they leave in. The number of homeless people will be compared to the GDP of each area to see if there might be some interesting findings. 

## Details
I saw this platform about exploring the homeless: http://www.understandhomelessness.com/explore/

and I will try to analyze the data of the Estimates of Homelessness in the U.S. 
the desired outcome should look like this:

![screen shot 2017-07-31 at 1 10 12 am](https://user-images.githubusercontent.com/28814380/28763580-2b1f0718-758d-11e7-9bab-14ca3951ee86.png)

**Possible headline(s):** 

Why ( ??  ) state has so many homeless people

**Data set(s):** 

http://www.understandhomelessness.com/data-notes/

https://www.hudexchange.info/resource/4832/2015-ahar-part-1-pit-estimates-of-homelessness/

**Code repository:** 

https://github.com/cathrinesot/studioprojects/tree/master/code/homeless
	
**Possible problems/fears/questions:** 

There are a lot of different parameters that should be considered for this particular analysis, so I will have to find extra datasets to compare it with. 

## Work so far

I downloaded the data and cleaned them.

## Checklist

This checklist must be completed before you submit your draft.

- [x] I have already spent time with my data set, opening it, exploring it, etc
- [x] I have created a "DIARY.md" file to save links and list all of the terrible, no good problems I come across
- [x] My issue issue has `[Project]` in the title
- [x] My issue links to my data set(s)
- [x] My issue links to my code repository
- [x] My issue explains what I'd like to explore in the data set
- [x] My issue includes images - either inspiration or what I've done so far
- [x] I have received two comments of peer feedback on my pitch issue

**Comment by amandolinjames** [comment]
What a good topic. Wondering if you will be looking at the "top 10 states with a homelessness problem" that could be interesting!

**Comment by cathrinesot** [comment]
I will definitely do this!!! Thank you!

**Comment by chrgavalas** [comment]
Definitely great story. There's poverty in America and it needs to be shown. I'd suggest you do something special about New York, a city people usually associate with wealth but has areas where poverty rates are significant compared to the rest of the city. But you can do it statewide. And make sure to define what it actually means to be poor and then compare this same variable to the previous years so as to examine the trend.

**Comment by cathrinesot** [comment]
# Update
	
1 notebook

https://github.com/cathrinesot/studioprojects/blob/master/code/homeless/Homeless%20People%20in%20the%20US.ipynb


## Content

Homeless in the US from 2007 to 2016 per category

![screen shot 2017-08-08 at 7 43 11 pm](https://user-images.githubusercontent.com/28814380/29099440-5e58aa0c-7c73-11e7-96d8-6519c0143b89.png)

## Any changes in direction or topic?
	Yes, I will start with New York city, instead of  "U.S. States With The Most Homeless People", because I found that New York city had a huge increase in homeless population over the past few years. 

## Problems/Questions

I have to standardize with the population in order to find the percentage of homeless people on every state. 

## Checklist
	
- [x] I have included my visuals
- [x] I have added writing about my topic
- [x] I have been updating my DIARY.md with details about my process
- [x] I have uploaded/updated any Jupyter Notebooks or other datasets into my code repository
- [x] I have received two comments of peer feedback on my project update

**Comment by qdinhbui2** [comment]
I worry that your sketch is a little bit too ambitious. You don't want to craft a dashboard. You want to craft a story. So you need to pick a design that will best represent your data. I think a simple graphic where you show each homeless category by state would be just fine. It's up to you what form that should be in though.
