### ISSUE TITLE
Maine Conservation Lands[Project]

### ISSUE THREAD

**Issue by kcough** [jsoma/data-studio-projects#66]
# Pitch
Mapping Maine land use and protected areas-Maine lags behind the rest of the country in land conservation. 

## Summary

Only 7% of Maine land is conserved (compared to 40% and 50% in some western states) and only 1% of Maine's coastline is open for public use. I would like to create a static visualization of this map: 

http://www.maine.gov/dacf/parks/publications_maps/conservation_lands_maine.html
with information overlaid on the acreage and who manages the site.

## Details

**Possible headline(s):** 
Maine Lagging Behind in Conservation of Public Lands

**Data set(s):** 
http://www.maine.gov/megis/catalog/
http://marineprotectedareas.noaa.gov/dataanalysis/mpainventory/

**Code repository:** 
https://github.com/kcough/data-studio-projects/tree/master/code/maine_conservation_lands
and marine protection areas (nationwide):
https://github.com/kcough/data-studio-projects/tree/master/code/marine_protection

**Possible problems/fears/questions:** 

## Work so far
I've mapped Maine's conservation lands and explored another dataset with marine protection areas (I'm thinking it's too much information to have both on one map though)

<img width="365" alt="maine_conservation_lands" src="https://user-images.githubusercontent.com/22796338/28780672-9db8a444-75d5-11e7-8b42-b29e72a2ce5b.png">

## Checklist

This checklist must be completed before you submit your draft.

- [x] I have already spent time with my data set, opening it, exploring it, etc
- [x] I have created a "DIARY.md" file to save links and list all of the terrible, no good problems I come across
- [x] My issue issue has `[Project]` in the title
- [x] My issue links to my data set(s)
- [x] My issue links to my code repository
- [ ] My issue explains what I'd like to explore in the data set
- [ ] My issue includes images - either inspiration or what I've done so far
- [ ] I have received two comments of peer feedback on my pitch issue

**Comment by qdinhbui2** [comment]
This is a great idea. One chart form you could explore is this [one](https://www.nytimes.com/interactive/2014/09/08/us/climate-change-could-push-birds-north-shrink-their-ranges.html)). click on 2080. The dotted line and boxes would work really well here. Then you could do all 50 states or New England.

**Comment by kcough** [comment]
# UPDATE:

After speaking with someone from Maine's largest land trust organization (Maine Coast Heritage Trust), I realized that there are pieces missing from the dataset. There are also discrepancies between the Maine Office of GIS data and the other databases I'm using (National Conservation Easement Database and Protected Areas Database of the United States). The MEGIS database was updated most recently, and I've contacted the office to see if they can clarify why the database is missing several large land holdings. I am also in the process of contacting all 67 land trusts in Maine to ask them for an updated list on all of their holdings, and will create my own dataset out of that information.
