### ISSUE TITLE
How I met your mother [Project]

### ISSUE THREAD

**Issue by mathieulede** [jsoma/data-studio-projects#67]
# Pitch
People have answered questions about their sentimental life during six years. During this time, they married, divorced, met new partners, had children, etc.
I would like to draw a map of the relations/events that lead to a relationship and its possible evolutions.
For example, the number of relations involved in the chain that link two people before they meet.
If that doesn't work, I still can simply show the evolution of few selected couples (by religion, income, etc.), with up and down, break-up, children and other events during six years. Could be represented as a timeline.

## Summary
>How Couples Meet and Stay Together (HCMST) is a study of how Americans meet their spouses and romantic partners.

**Possible headline(s):** 
1. How I met your mother

**Data set(s):** 
[Link to the dataset](https://data.stanford.edu/hcmst)  

**Code repository:** 
[Project 3](https://github.com/mathieulede/data-studio/tree/master/code/project3)

**Possible problems/fears/questions:** 
![599f840bc1379429366a1c2061c3a3a5](https://user-images.githubusercontent.com/28827574/28781083-e318a27c-75d6-11e7-943d-a810b4510323.jpg)

## Checklist

This checklist must be completed before you submit your draft.

- [x] I have already spent time with my data set, opening it, exploring it, etc
- [x] I have created a "DIARY.md" file to save links and list all of the terrible, no good problems I come across
- [x] My issue issue has `[Project]` in the title
- [x] My issue links to my data set(s)
- [x] My issue links to my code repository
- [x] My issue explains what I'd like to explore in the data set
- [x] My issue includes images - either inspiration or what I've done so far
- [ ] I have received two comments of peer feedback on my pitch issue

**Comment by mathieulede** [comment]
![screen shot 2017-08-01 at 7 28 08 pm](https://user-images.githubusercontent.com/28827574/28851900-8c2f1ac2-76f3-11e7-9aa6-026caf84a498.png)

**Comment by Ediegram** [comment]
The chart needs annotation and explanation of what the links mean.

**Comment by mathieulede** [comment]
First draft:

![output-07](https://user-images.githubusercontent.com/28827574/28946940-3d9886b2-787b-11e7-8673-f390b07d917c.jpg)

**Comment by qdinhbui2** [comment]
This is a very interesting dataset! The chart I think needs more annotation. I applaud the effort at a more interesting chart form but this chart is somewhat misleading. By arranging the circles in an orbit, I feel like I'm supposed to derive some meaning in how they're arranged, but I don't really see the connect.

**Comment by mathieulede** [comment]
Well that's too complicated and a bit misleading, wanted to try something like that but I squeezed everything into a form instead of looking for the best way to show it. But look that's the whole world of love! :)

![ouput_v2](https://user-images.githubusercontent.com/28827574/29199072-a8ee9ce8-7e17-11e7-9cc4-32129100e408.jpg)
