### ISSUE TITLE
Never give money to this kind of people [Projects]

### ISSUE THREAD

**Issue by wonderfulexperience** [jsoma/data-studio-projects#68]
# Pitch

## Summary

Lending Club is the largest peer-to-peer lending platform in the world. Since 2010, more than $ 26bn dollars in loans were issued. Borrowers use Lending Club to get cheaper financing than with a bank or to get a loan if the banks do not think they are eligible for it. The provider for loan funds can be private or public. The lenders are private investors as well as companies.

Lending Club offers individual data on borrowers. Using this data, I want to have a look who are the characteristics of borrowers.

Questions:
- For what do rich/poor people need to borrow money?
- What kind of profile do people have who are late in paying back their loans?
  (gender, regional, job title, income, reason, state)
- What's a bad thing to borrow money for?

Here is an overview of loan issuance at Lending Club:
<img width="948" alt="bildschirmfoto 2017-07-28 um 11 23 31" src="https://user-images.githubusercontent.com/28814374/28781102-f159886a-75d6-11e7-9389-699c4febeb62.png">

## Details

**Possible headline(s):** 
- "The worst kind of people to give money to"
- "Never give money to this type of people"
- "If somebody asks for money to do this, they probably won't give it back"

**Data set(s):** 
https://www.lendingclub.com/info/download-data.action

**Code repository:** 
https://github.com/wonderfulexperience/data-studio-projects/tree/master/code/Project_3
	
**Possible problems/fears/questions:** 
- no definite results
- too big data file to handle efficiently

## Work so far
- exploring data

## Checklist

This checklist must be completed before you submit your draft.

- [X] I have already spent time with my data set, opening it, exploring it, etc
- [X] I have created a "DIARY.md" file to save links and list all of the terrible, no good problems I come across
- [X] My issue issue has `[Project]` in the title
- [X] My issue links to my data set(s)
- [X] My issue links to my code repository
- [X] My issue explains what I'd like to explore in the data set
- [X] My issue includes images - either inspiration or what I've done so far
- [ ] I have received two comments of peer feedback on my pitch issue

**Comment by amandolinjames** [comment]
Sounds interesting! Would be cool to look at which states have the most people w bad credit history- wonder if it's in the South.

**Comment by wonderfulexperience** [comment]
# Update
	
## Content
Showing different charts where people have the highest rates of problems to pay back a loan on lending club.

Loans with problems by income quartile
![quartile](https://user-images.githubusercontent.com/28814374/29074671-26fbadc0-7c1e-11e7-8193-d7adac39be18.png)

Loans with problems by best and worst of around 1000 demographic groups
![grouped](https://user-images.githubusercontent.com/28814374/29074678-2ce3be4e-7c1e-11e7-9a88-333e43d83698.png)

## Any changes in direction or topic?
I want to include an interactive section where people can check their own credit score.
	
## Problems/Questions
I want to say in the story line that there is a wide variation of the rate of problem loans by demographic group. Maybe I should make that more clear.

## Checklist
	
- [X] I have included my visuals
- [X] I have added writing about my topic
- [X] I have been updating my DIARY.md with details about my process
- [X] I have uploaded/updated any Jupyter Notebooks or other datasets into my code repository
- [ ] I have received two comments of peer feedback on my project update
