### ISSUE TITLE
Who are the lobbyists of Brussels/ Is your neighbor a lobbyist? [Projects]

### ISSUE THREAD

**Issue by IoannisAntypas** [jsoma/data-studio-projects#69]
# Pitch
This is part two of my investigation on lobbying in Europe. Last project I examined whether the number of lobbyists in Brussels had risen after Brexit. This week, I would like to use the transparency register again to find out which individuals/companies/ngos are registered, and where are they situated. 

## Summary

This time we will map every single company that is included in the transparency register and cluster them together per country. Each company will be a dot in the map, which when clicked will reveal the companys' name, address, legal status, website address, phone and post box, person with legal responsibility, person in charge of eu relations, goals, level of interest, interests with the EU, company size, fields of interest, EU grants secured.

I will be using the same dataset as last project, taking all of the data from them and mapping them with leaflet. 

## Details

**Possible headline(s):** 

Do you live next to an EU lobby?

**Data set(s):** 

Everything is here
http://ec.europa.eu/transparencyregister/public/consultation/search.do?dataReport=Change+my+search+criteria

**Code repository:** 

Not yet

**Possible problems/fears/questions:** 
Its another map/interactivity and with points. I have never done that so I hope I get it right. 

## Work so far

Identified and downloaded my dataset. Found the different areas I will measure

## Checklist

This checklist must be completed before you submit your draft.

- [x ] I have already spent time with my data set, opening it, exploring it, etc
- [ x] I have created a "DIARY.md" file to save links and list all of the terrible, no good problems I come across
- [ x] My issue issue has `[Project]` in the title
- [ x] My issue links to my data set(s)
- [ ] My issue links to my code repository
- [ x] My issue explains what I'd like to explore in the data set
- [ ] My issue includes images - either inspiration or what I've done so far
- [ ] I have received two comments of peer feedback on my pitch issue

**Comment by qdinhbui2** [comment]
I'm not that interested if I live near a lobbyist. It's not clear to me that lobbyists locations are interesting -- unless they are somewhere they aren't expected to be.
