### ISSUE TITLE
Greece: Accidents at work (2008-2015) [Project]

### ISSUE THREAD

**Issue by 2109Sot** [jsoma/data-studio-projects#7]
Please complete all of the following sections, or a robot will spookily dance around your issue! A completed version of this template can be found at https://github.com/jsoma/data-studio-projects/issues/1

# Pitch

## Summary

Following the death of a 62 years old female sanitation worker* and mother of four children on July 1st, while collecting garbage at the neighbourhood of Zografou, Athens, and using data from ELSTAT (Hellenic Statistical Authority), I’d like to look into the workplace accidents in Greece and whether they are connected to the economic crisis. However, the data from ELSTAT goes until 2015 so I was thinking of starting my research from 2008, that is two years before Greece signed its first Memorandum with the European Union and the IMF. 

* Garbage collectors had to return to work after a 10-day protest that left huge piles of trash around Athens under a phenomenal heat wave all over the country where temperatures reach 44 degrees Celsius in Athens prompting a public health agency to issue a warning over the continuing strike.

## Details

**Possible headline(s):** 

1. To what extent safety check cutbacks affect workplace accidents in Greece?
2. Dying to work: Accidents in the Greek workplace before and after the first Memorandum.
3. Accidents in the Greek workplace: This is what happens when you cut safety measures.

**Data set(s):** 

http://www.statistics.gr/en/statistics/-/publication/SHE03/2015

**Code repository:** 

https://github.com/2109Sot/studio-projects/tree/master/code/accidents_at_work
	
**Possible problems/fears/questions:** 

There is not much data and this is not going to be a really detailed analysis.  

## Work so far

<img width="972" alt="screen shot 2017-07-16 at 22 28 52" src="https://user-images.githubusercontent.com/28814400/28273082-4fead1c4-6adb-11e7-8565-ad2a34eeb3fe.png">

## Checklist

This checklist must be completed before you submit your draft.

- [x] I have already spent time with my data set, opening it, exploring it, etc
- [x] I have created a "DIARY.md" file to save links and list all of the terrible, no good problems I come across
- [x] My issue issue has `[Project]` in the title
- [x] My issue links to my data set(s)
- [x] My issue links to my code repository
- [x] My issue explains what I'd like to explore in the data set
- [x] My issue includes images - either inspiration or what I've done so far
- [x] I have received two comments of peer feedback on my pitch issue

**Comment by Dgorgs** [comment]
Very interesting topic. And shocking at the same time.

**Comment by marcelpauly** [comment]
Cool! I think I would use the whole time periode to look for effects by the crisis and then I would use 2014/15 data for some other analysis: gender, position, regional if possible.

**Comment by edl2118** [comment]
Great add in for the interviews. I think that will make the data come alive in a way that the numbers themselves won't. It will make the story more compelling for sure imo

**Comment by mukhtaryare** [comment]
This is a fascinating idea. Maybe expanding your data to cover more years would be helpful.

**Comment by 2109Sot** [comment]
# Update
	
## Content

I have spent quite some time working on my visualisations, but still there is a lot to do to make them communicate my story. In terms of my datasets, I am almost done as the data on the topic is pretty limited and straightforward.

![total_accidents_05_15](https://user-images.githubusercontent.com/28814400/28448312-132d8da4-6da5-11e7-80d7-8e57251c0e19.png)

![occupations_14_15-01](https://user-images.githubusercontent.com/28814400/28448315-1bd4634c-6da5-11e7-95ba-3d986f9a0cc3.png)

![men_women_14_15](https://user-images.githubusercontent.com/28814400/28448316-1fd9317a-6da5-11e7-845e-c097a4b6e47f.png)

## Any changes in direction or topic?

I am focusing more on specific types of injuries, such as burns and amputations, rather than on the general image. Also the gender and occupation of the victim have been taken into account.
	
## Problems/Questions

Not sure if I can get into a more thorough analysis on the topic, since the data is really limited. Find extra sources?
	
## Checklist
	
- [x] I have included my visuals
- [x] I have added writing about my topic
- [x] I have been updating my DIARY.md with details about my process
- [x] I have uploaded/updated any Jupyter Notebooks or other datasets into my code repository
- [ ] I have received two comments of peer feedback on my project update

**Comment by 2109Sot** [comment]
# Final

## Project visuals/text

“Forbearance and conscientiousness, combined with the excessive heat, and the lack of all the necessary means of personal protection, led our to our colleague’s death, instead of life, because she was struggling to collect garbage,” said Nikos Trakas, President of the municipality workers union POE-OTA, in an interview confirming the death by heart attack of Daniela Preloretzou, a 62-year-old female sanitation worker, on Friday, June 30, during her second shift in less that 24 hours under a phenomenal heatwave in Athens. Two days later, on Sunday, July 2, a 45-year-old male sanitation worker got injured at work in Thessaloniki and then admitted to the intensive care unit of a local hospital.

The two incidents briefly catapulted the question of accidents in the Greek workplace and my assumption that their figures have skyrocketed in recent years due the economic crisis. Using records from the Hellenic Statistical Authority (ELSTAT) in .csv format, I started gathering preliminary information about accidents in the Greek workplace from 2005 — three years before the global economic crisis began and five years before Greece signed the first Referendum with its European creditors — until 2015, when ELSTAT’s reference period ends. Well, it didn’t take long before I realized that my initial assumption was rather naive.

![accidents_total_final_05_15](https://user-images.githubusercontent.com/28814400/28701942-b618d352-7327-11e7-8651-f461f7342ebf.png)

Instead of a dramatic increase, there has been a great reduction in the accident rate by almost 96% since the beginning of my reference period, from 10,684 in 2005 to 3,762 in 2013. But why?

**Two reasons**

According to Kleanthis Chatzinikolaidis, President of the National Association of Labour Inspection (SEPE), such a reduction in the number of work-related injuries is linked to two reasons. First, up until 2009, companies, as part of their investments in safety measures, were buying new equipment that complied with European regulatory requirements and were taking good care of them. The second reason is linked to the reduced building activity in Greece during the first years of the crisis. Less buildings mean less accidents for workers. Indeed, as we can see in the chart below, in both 2014 and 2015 ‘Construction’ and ‘Manufacturing’ were among the most harmed sectors, with the overall accident rate going up by 10% every year since 2013, mainly because of the lack of funding for safety measures and new equipment from 2010 onwards.

![sector_total_final_14_15](https://user-images.githubusercontent.com/28814400/28701950-cee6aefe-7327-11e7-8cb8-4651786ce3ec.png)

As far as the most important consequence of an accident at work — whether it is fatal or not — is concerned, in 2014, out of 4,241 in total, 46 fatalities were recorded. The corresponding number fell slightly in 2015 to 45 fatal accidents, out of 4,459 in total.

Although, many of the accidents involve male workers, about one third of the victims are female. Out of 4,459 accidents at work, which was the total number in 2015, 3,237 accidents refer to men and 1,222 to women, while the corresponding figures for 2014 were 3,127 and 1,114, respectively, the total number of accidents being 4,241.

![men_women_final_14_15](https://user-images.githubusercontent.com/28814400/28701957-dd77bc10-7327-11e7-920b-95f7110ef610.png)

As regards the occupation of the victims, on the basis of the available data for 2014 and 2015, it is observed that most of the victims belong to the occupation category ‘Elementary Occupations’, followed by ‘Plant and Machine Operators’. This should come with no surprize, given that both occupations are related to ‘Manufacturing’ and ‘Construction’, the two most harmed sectors during the same period so to speak.

![occupation_total_final_14_15](https://user-images.githubusercontent.com/28814400/28701966-ec2ba3c0-7327-11e7-8295-8239e4f9a0c8.png)

It is also worth noting, when it comes to the type of injury, that from 2005 to 2015 there have been 2,209 burns and 2,070 amputations. As you can see in the chart below, the most frequent types of injury during the same period are ‘Fractures’ (23,804 accidents), ‘Rupturing Wounds’ (18,504 accidents), ‘Ruptures’ (17,104 accidents), and ‘Strains’ (6,429 accidents).

![injury_type_final_05_15](https://user-images.githubusercontent.com/28814400/28701975-f8a3f382-7327-11e7-9574-0bfd2add6e3b.png)

Finally, as regards the parts of the body that were more frequently injured, ‘Wrist and Fingers’ were by far the most injured (21,670 accidents), followed by ‘Foot’ (8,198 accidents), and ‘Joint of Foot and Tibia’ (7,123 accidents).

![bodyparts_total_final_05_15](https://user-images.githubusercontent.com/28814400/28701986-090c4b3e-7328-11e7-97be-b56470d908cf.png)

**Notes on methodology**: Data refer mainly to employees insured by Social Insurance Institute (IKA) who had an accident at work and differ from the ones declared to SEPE. Data on the branch of economic activity of the enterprise are classified in accordance with the national classification “STAKOD 2008” (on the basis of the Statistical Classification of the Economic Activity NACE Rev.2). More information on the survey is available on the website of [ELSTAT](http://www.statistics.gr/en/statistics/-/publication/SHE03/-).

## Details

**Headline:** 

Accidents in the Greek workplace: This is what happens when companies cut safety measures

**Published website version:**

https://2109sot.github.io/studio-projects/accidents_at_work/

**Code repository:**

https://github.com/2109Sot/studio-projects/tree/master/code/accidents_at_work

**Final data set(s):** 

http://www.statistics.gr/en/statistics/-/publication/SHE03/-

## What did you find to be the most difficult part of this project?

The are different organisations in Greece that keep track of the accidents in the workplace. Nonetheless  ELSTAT is considered as the "official" statistical authority in the country and I this why I chose to use their data, apart from the fact that it's the only available online. My results would not be the same if I had used a different dataset. 

## Are you satisfied with what you produced? Is there anything you would like to change or improve?

Apart from the first graph, which shows a trend in my time-frame (2005 - 2015), the rest seem to me as more or less a report with some basic charts. I would like to tell a better story, but my dataset didn't cooperate well.

## Checklist

- [x] I have included my visuals
- [x] I have posted my project to my project website
- [x] I have been updating my DIARY.md with details about my process
- [x] I have uploaded/updated any Jupyter Notebooks or other datasets into my code repository

**Comment by Ediegram** [comment]
As we discussed in class, the data are missing the all important denominator. Better to express as rates, 'per 100K workers' for example.
