### ISSUE TITLE
Which Countries Are Open to Transgender People? [Project]

### ISSUE THREAD

**Issue by amandolinjames** [jsoma/data-studio-projects#70]
Please complete all of the following sections, or a robot will spookily dance around your issue! A completed version of this template can be found at https://github.com/jsoma/data-studio-projects/issues/1

# Pitch
Most countries have citizenship forms that include two gender options: Male or Female. Not everyone identifies this way. 

## Summary
I'll look at which countries' naturalization applications include more than two boxes, and what the others are, maybe a blank space,  or one that says 'other.'

## Details

**Possible headline(s):** 
Which countries are the most inclusive of transgender people? 

**Data set(s):** 
There isn't a dataset yet! I am creating one by looking at the citizenship forms for every country. I want this dataset to be repurposed for other people to use. 

**Code repository:** 
	
**Possible problems/fears/questions:** 
Unsure how I will visualize it. Any ideas? 

## Work so far
Germany
![germancitizenship](https://user-images.githubusercontent.com/29207139/28796080-2f60f912-760a-11e7-849f-e9b38b485d25.png)

Australia
![australiacitizenship](https://user-images.githubusercontent.com/29207139/28796107-4c64d65a-760a-11e7-8518-3ae6fc8922ce.png)

Just an example of the work I'm doing looking at each form. 
## Checklist

##Update
After looking up citizenship forms for all of the countries and trying to make my own dataset, I realized it is very hard to find forms for every country. Many are not PDFs and you have to create an online account to register for citizenship to be able to see it. This wasn't viable within the span of a week sadly. I had to completely scrap the idea. I kept the concept of looking at official forms and am now looking at the U.S. Census Race Box. Below is my preliminary work, a very rough draft. I created my own dataset using archived census forms. I am unsure what to analyze beyond looking at what options were shown on the form over time. I also would like to show the graph as a vertical time line, and include some facts in annotation about what laws were passed then that affected immigration, such as Japanese internment camps, LBJ's welcome to immigrants, the Cold War immigration period, and so on. I don't know how to make a vertical graph though with the line in the center, and annotation on either side of it. 

##New Dataset

http://racebox.org

![screen shot 2017-08-03 at 6 02 25 pm](https://user-images.githubusercontent.com/29207139/28945807-066904e6-7876-11e7-8ea2-d2d7591c6c17.png)

This checklist must be completed before you submit your draft.

- [x] I have already spent time with my data set, opening it, exploring it, etc
- [x] I have created a "DIARY.md" file to save links and list all of the terrible, no good problems I come across
- [x] My issue issue has `[Project]` in the title
- [x] My issue links to my data set(s)
- [x] My issue links to my code repository
- [x] My issue explains what I'd like to explore in the data set
- [x] My issue includes images - either inspiration or what I've done so far
- [ ] I have received two comments of peer feedback on my pitch issue

**Comment by ElisaHarlan** [comment]
Very exciting idea! First, I'd say, make a map. But this is not exactly what is expected of us. What about 
![image](https://user-images.githubusercontent.com/28815568/28808367-643745ee-7649-11e7-8fa3-b87b5dc4ae51.png)
I am sure there are many subsets on a continuum, like "not mentioned at all" to a possible selection of different gender identities. Maybe boxes. 
![image](https://user-images.githubusercontent.com/28815568/28808436-f6bc18c2-7649-11e7-8b69-110918069ecb.png)

**Comment by wonderfulexperience** [comment]
Wow, building your own dataset is always a worthwhile idea. If you find out when countries introduced more transgender-accepting forms, maybe you can plot it on a timeline? Else you could plot the countries grouped by world region (instead of a map).

**Comment by chrgavalas** [comment]
Amanda sounds great! Just make sure to clarify what's your piece's perception of "being open to transgender people". What would the indicators be? For instance I recently read this piece on CNN about which countries allow transgender people join their army (http://www.cnn.com/2017/07/27/us/world-transgender-ban-facts/index.html). I'm looking forward to seeing this!

**Comment by sarahslo** [comment]
Interesting. Here's the thing, you'll want to add other information from this form to make this dataset more interesting. At the moment, the question you are asking in binary: Is other an option on the form? Yes/No.   
So as you collect the forms, look for patterns of what they collect and what they don't beyond just gender. 
Josh Begley, a data artist and journalist did some [good work with forms](http://racebox.org/), forms in and of themselves are objects are cool to see. So maybe there is a geographic distribution to places that give other as an option, and they also ask you...your profession. Or instead of profession they say trade, so maybe there is something else in the language of the form that is telling about the country. 
It's hard to know how to visualize this until you know a bit more about what you are chasing. 
Keep going! Good project.
