### ISSUE TITLE
Wheels of gold: the subsidies for German car companies [Project]

### ISSUE THREAD

**Issue by ElisaHarlan** [jsoma/data-studio-projects#71]
Please complete all of the following sections, or a robot will spookily dance around your issue! A completed version of this template can be found at https://github.com/jsoma/data-studio-projects/issues/1

# Pitch

## Summary

The automobile industry is funded extensively by public funds. This ranges from direct grants for research and development to indirect subsidies, for example in the field of fuel taxation.
The extent to which the car industry has been subsidized directly or indirectly through public funding in the last decade (fiscal years 2007 to 2016) is explored in this dataset. 

Following the project from last week (contact between German government and car companies), this dataset could shed light on the priorities of the government in terms of actual spending. Goal would be to connect those two projects.

## Details

**Possible headline(s):** 
Wheels of gold: the subsidies for German car companies

**Data set(s):** 
http://dip21.bundestag.de/dip21/btd/18/123/1812370.pdf

**Code repository:** 
	
**Possible problems/fears/questions:** 
The dataset is not very clean, different spellings, order of the data. 

## Work so far
Explored the dataset, threw it into a knotprogram.
![automobilzuwendungen](https://user-images.githubusercontent.com/28815568/28808095-94d00b3e-7647-11e7-97dc-089787254d57.png)
![node_image](https://user-images.githubusercontent.com/28815568/28808116-ace4b954-7647-11e7-8d02-3f918029bb1c.png)

## Checklist

This checklist must be completed before you submit your draft.

- [x] I have already spent time with my data set, opening it, exploring it, etc
- [ ] I have created a "DIARY.md" file to save links and list all of the terrible, no good problems I come across
- [x] My issue issue has `[Project]` in the title
- [x] My issue links to my data set(s)
- [ ] My issue links to my code repository
- [x] My issue explains what I'd like to explore in the data set
- [x] My issue includes images - either inspiration or what I've done so far
- [ ] I have received two comments of peer feedback on my pitch issue

**Comment by Dgorgs** [comment]
This topic is currently dominating the media. It is a big issue. More than any other nation, Germans are obsessed by cars.  The "partnership" between car business and politics has been critisized by environmentalists and the opposition. The scandal regarding the exhaust emissions is bringing this topic up even more. Great project idea!

**Comment by ElisaHarlan** [comment]
# Final

## Project visuals/text

## Details

**Headline:** 
The cozy relation between the German Carindustry and the Government

**Published website version:**
https://elisaharlan.github.io/studio-projects/cars/

**Code repository:**
https://github.com/ElisaHarlan/studio-projects/tree/master/code

**Final data set(s):** 
http://dip21.bundestag.de/dip21/btd/18/128/1812880.pdf
http://dip21.bundestag.de/dip21/btd/18/123/1812370.pdf

## What did you find to be the most difficult part of this project?
restructuring the data, using regex, finding interesting patterns

## Are you satisfied with what you produced? Is there anything you would like to change or improve?
Well, it could look much more professional, I guess. 

## Checklist

- [x] I have included my visuals
- [x] I have posted my project to my project website
- [ ] I have been updating my DIARY.md with details about my process
- [x] I have uploaded/updated any Jupyter Notebooks or other datasets into my code repository
