### ISSUE TITLE
Complaint line[Project]

### ISSUE THREAD

**Issue by Dgorgs** [jsoma/data-studio-projects#72]
Please complete all of the following sections, or a robot will spookily dance around your issue! A completed version of this template can be found at https://github.com/jsoma/data-studio-projects/issues/1

# Pitch
Calls to 311-hotline

## Summary
In NYC, you can call 311 and complain about anything. I want to find out what the most common complaints are. And what it reveals about New York. There are probably patterns. And then I could break down the complaints by neighborhoods. Some New Yorkers grumble more than others. 

I was intrigued by this graph:

![bildschirmfoto 2017-07-31 um 23 22 37](https://user-images.githubusercontent.com/28849286/28808043-459250f4-7647-11e7-9d2c-922e986b18e7.png)

## Details
**Possible headline(s):** 
What a Hundred Million Calls reveal about New York

**Data set(s):** 
New York open data

**Code repository:** 

**Possible problems/fears/questions:** 
I am afraid that I won't finish on time

## Work so far
Explored the data set

## Checklist

This checklist must be completed before you submit your draft.

- [x ] I have already spent time with my data set, opening it, exploring it, etc
- [ ] I have created a "DIARY.md" file to save links and list all of the terrible, no good problems I come across
- [x ] My issue issue has `[Project]` in the title
- [x] My issue links to my data set(s)
- [ ] My issue links to my code repository
- [x ] My issue explains what I'd like to explore in the data set
- [x] My issue includes images - either inspiration or what I've done so far
- [ ] I have received two comments of peer feedback on my pitch issue

**Comment by ElisaHarlan** [comment]
Great idea, I really like this special kind of graph! Maybe you find data about another city and you can compare the cities.

**Comment by MarinaBraem** [comment]
Great idea! I like it very much. Go ahead and don't be afraid :-)
