### ISSUE TITLE
Introduction and death of every Game of Thrones character [Project]

### ISSUE THREAD

**Issue by JulienAssouline** [jsoma/data-studio-projects#73]
Please complete all of the following sections, or a robot will spookily dance around your issue! A completed version of this template can be found at https://github.com/jsoma/data-studio-projects/issues/1

# Pitch

## Summary
I've found information on a website that lists when every character in Game of Thrones has died, per episode. It has also a list of when characters were first introduced. 

My goal or idea is to create a graphic/timeline of when each character was first introduced, or when they first appeared on the show, and when, if, they died. 

This would help give context as to how short or long a characters life on the show was. For example, Ned Stark is still a character we think about, but he was only on the show for 10 episodes. Putting him into context with other long-lasting characters would help give scale as to his and other characters lives on the show. 

## Details
The website has a page for each episode. On that page, there is the number of deaths, plus the characters introduced. I will need to do a lot of scrapping in order to get all of the data. Thus far, I've been able to get all the deaths per episode. 

**Possible headline(s):** A Game of Thrones life

**Data set(s):** http://gameofthrones.wikia.com/wiki/Winter_Is_Coming

**Code repository:** https://github.com/JulienAssouline/data-studios-projects/tree/master/code/Project_4
	
**Possible problems/fears/questions:** 
My biggest fear is not that I won't be able to get that data. Rather it's that joining the names of the characters introduced with their deaths will introduce errors or missing data. 

## Work so far
https://github.com/JulienAssouline/data-studios-projects/tree/master/code/Project_4
## Checklist

This checklist must be completed before you submit your draft.

- [x] I have already spent time with my data set, opening it, exploring it, etc
- [ ] I have created a "DIARY.md" file to save links and list all of the terrible, no good problems I come across
- [x] My issue issue has `[Project]` in the title
- [x] My issue links to my data set(s)
- [x] My issue links to my code repository
- [x] My issue explains what I'd like to explore in the data set
- [ ] My issue includes images - either inspiration or what I've done so far
- [ ] I have received two comments of peer feedback on my pitch issue

**Comment by cathrinesot** [comment]
I am very interested to know how many characters died in GOT! Maybe you can put the faces of the main characters instead of dots or circles! Or you can have a different color from every family!  Good Luck! 🥇

**Comment by IoannisAntypas** [comment]
I think this is a great idea and very informative given that it is the most popular show on the planet right now and its currently mid-season! Try to have some sort of theme for each House as well!

**Comment by JulienAssouline** [comment]
# Update
The scrapping and cleaning took a long time. Right now I am still trying to find an exact story. I am leaning on pointing out the characters who've been with us from the start. There've been many characters who've come and gone from the show. Some we've loved and hated, but very few have been with us from beginning to end. I am still trying to figure out the best visual form right now. My goal is to come up with a graphic that reflects the number of characters who have been on the show but also reflects the length or the amount of time each character has been on the show. Both graphics below have the same visual form. The biggest difference is the second graph also includes characters who have an unknown fate. Basically, they weren't significant characters on the show. In the first graphic, I removed them. The graphics below also only represent a screenshot. The actual graphic is longer. 
## Content
![screen shot 2017-08-07 at 1 10 35 am](https://user-images.githubusercontent.com/17466947/29012983-88460c04-7b0d-11e7-9dca-c74e031baa04.png)
![screen shot 2017-08-07 at 1 12 07 am](https://user-images.githubusercontent.com/17466947/29012988-8c737de8-7b0d-11e7-9fc4-099b8ab41b08.png)

## Any changes in direction or topic?
Not at the moment. Still trying to figure things out. 
## Problems/Questions
I'm currently experimenting with how to visualize the information. After some testing, this is the best form I've come up with for now. It could change and I am open to any suggestions. 	
## Checklist
	
- [x] I have included my visuals
- [x] I have added writing about my topic
- [x] I have been updating my DIARY.md with details about my process
- [x] I have uploaded/updated any Jupyter Notebooks or other datasets into my code repository
- [ ] I have received two comments of peer feedback on my project update

**Comment by sarahslo** [comment]
So. I would like to see a key/legend at the top of this that gives me very Still Alive/Dead/Last seen.
You want to see that first so it is not a question.
Then, how can you organize the data to tell more or a story. If you sort it so you show the people who are still alive at the top and then as you move to shorter durations -- in other words, organize the data by the pattern -- it will become more clear
![screen shot 2017-08-07 at 18 38 43](https://user-images.githubusercontent.com/659014/29048641-ca6af27e-7b9f-11e7-94ca-69ab2278fdbb.png)

the other thing you can do, is organize it by character type. bunch main characters together? or families? or however you think it best should be organized. that way you can then see how long each group tends to live.

or, you could separate it between alive/dead.
nice start, will be curious to see where you take this.
