### ISSUE TITLE
People like you [Project]

### ISSUE THREAD

**Issue by simon-pinkmartini** [jsoma/data-studio-projects#74]
# Update

## Status
I included the data for income bracket, nationality and political party preference. Also modified the legend a bit. Code still in the same place.

# Update

## Status
I got the following data: number of people in each canton/commune/district by age, by marital status and by household size (these were the best formatted). I also know how to get the number of people by party strength and by income bracket. I structured the data so I can display it in leaflet. The app now has three select boxes where the user can input his data (or the data that interests him). The map then displays an aggregate score for each geographical area, indicating the degree of over- or underrepresentatition for the chosen sociodemographic variable.

## Images
<img width="912" alt="screen shot 2017-08-05 at 20 54 04" src="https://user-images.githubusercontent.com/28814395/28999735-1825c2bc-7a21-11e7-9ccd-f4cca074ca5e.png">

## Problems and Questions
* I think the visual is very straight forward when it comes to the individual categories (age, etc). But there are some open question with the aggregate score (which is just an average of the other scores, if more than one option is selected: the score could be misleading, since it assumes an even distribution of all the variables (but in fact we don't know the exact percentage of people with some combination, like 35-year old singles in 2-person households, for each geographical entity). The fact that this score is just an approximation is a conceptual (and with this data, to some degree unsolvable) problem. Might have to drop the idea of an aggregate score and instead just reset the other variables when a user switches his selection.
* Second open question is how to arrange the select-boxes with the rest of the information on the page. Also, it might make sense to include the Swiss average for each category somewhere, which is not the case now (it only shows the difference of the geographic areas vs the swiss average)

## Links
Original Data: https://www.pxweb.bfs.admin.ch/Selection.aspx?px_language=de&px_db=px-x-0102010000_101&px_tableid=px-x-0102010000_101\px-x-0102010000_101.px&px_type=PX
Code: https://github.com/simon-pinkmartini/studio-projects/tree/master/code/People-like-me
Webdemo: http://165.227.144.49/People-like-me/web/peoplelikeme.html

# Pitch
An interactive map (yes!) that tells you in which Swiss places people like you typically live. 

## Summary
Based on one or more user-defined attributes (for age, nationality, household size, income, ...), this tool will calculate a metric for each Swiss district. This metric will be visualized on a map to show how over- or underrepresented people sharing the selected attributes are in each district.

## Details
This is an exercise in number crunching and mathematics, since there has to be an algorithm that takes the user inputs and transforms it into a color, based on the available data for each district. I plan to use leaflet, combining the map with additional features like select boxes. The idea behind this is to get the user interested in socio-demographic data by offering a different, personalized point of entry into the data.

**Possible headline(s):** 
People Like You

**Data set(s):** 
* Most demographic data is available for 2015 from the Federal Office of Statistics
* Data on income classes is available from the Federal Tax Office

**Code repository:** 
No code yet
	
**Possible problems/fears/questions:** 
* The data load might prove to be too big for the visualization and slow it down

## Work so far
* Made sure the data I want is available
* I worked out data structure and the formula for the algorithm (on paper)

## Checklist

This checklist must be completed before you submit your draft.

- [x] I have already spent time with my data set, opening it, exploring it, etc
- [x] I have created a "DIARY.md" file to save links and list all of the terrible, no good problems I come across
- [x] My issue issue has `[Project]` in the title
- [x] My issue links to my data set(s)
- [x] My issue links to my code repository
- [x] My issue explains what I'd like to explore in the data set
- [x] My issue includes images - either inspiration or what I've done so far
- [x] I have received two comments of peer feedback on my pitch issue

**Comment by RodrigoMenegat** [comment]
That's cool! 

If I were you, I would have some pre-made entries and not rely only in user input data. You could, perhaps, build some curious/representative characters (the old singles who live with their parents, the young people who live alone) beforehand and have a button or something to display them quickly. Maybe even a randomizer.

**Comment by wonderfulexperience** [comment]
I think it's okay only to show one category at once, if you don't have individual data available. You could also write an article (additional to the interactive map), exploring a bit the strangest pattern you observed.
