### ISSUE TITLE
Sentiment analysis of Punk Rock songs [Project]

### ISSUE THREAD

**Issue by demetriospogkas** [jsoma/data-studio-projects#76]
Please complete all of the following sections, or a robot will spookily dance around your issue! A completed version of this template can be found at https://github.com/jsoma/data-studio-projects/issues/1

# Pitch

## Summary
Text analysis of Punk Rock Songs and comparison between artists/bands and/or years/decades.

## Details

**Possible headline(s):** 
"Punk Sentiments"

**Data set(s):** 
- Wikipedia lists of punk rock bands: https://en.wikipedia.org/wiki/List_of_punk_rock_bands,_0–K and https://en.wikipedia.org/wiki/List_of_punk_rock_bands,_L–Z
- Lyrics from MetroLyrics.
- NRC Word-Emotion Association Lexicon (EmoLex) from http://saifmohammad.com/WebPages/NRC-Emotion-Lexicon.htm.

**Code repository:** 
https://github.com/demetriospogkas/The-Lede-2017-Data-Projects/tree/master/code/Project-04-Sentiment-Analysis-of-Punk-Rock-Lyrics

**Possible problems/fears/questions:** 

## Work so far
https://github.com/demetriospogkas/The-Lede-2017-Data-Projects/blob/master/code/Project-04-Sentiment-Analysis-of-Punk-Rock-Lyrics/Punk-Rock-Sentiment-v01-2017-08-03.ipynb

![](https://raw.githubusercontent.com/demetriospogkas/The-Lede-2017-Data-Projects/master/code/Project-04-Sentiment-Analysis-of-Punk-Rock-Lyrics/Ramones-Sentiment-v01.png)

## Checklist

This checklist must be completed before you submit your draft.

- [x] I have already spent time with my data set, opening it, exploring it, etc
- [ ] I have created a "DIARY.md" file to save links and list all of the terrible, no good problems I come across
- [x] My issue issue has `[Project]` in the title
- [x] My issue links to my data set(s)
- [x] My issue links to my code repository
- [x] My issue explains what I'd like to explore in the data set
- [x] My issue includes images - either inspiration or what I've done so far
- [ ] I have received two comments of peer feedback on my pitch issue

**Comment by RodrigoMenegat** [comment]
Awesome! I am doing the same thing for Algorithms homework, but with metal bands.  It's funny how Ramones looks WAY more positive than Iron Maiden (see picture). But this makes a lot of sense!
![ironmaiden](https://user-images.githubusercontent.com/28814352/28941336-b63bd454-7865-11e7-81da-db7c4b4826a2.jpg)

**Comment by qdinhbui2** [comment]
I generally find these multidimensional spider charts hard. But I may be in the minority. One thought about music in general is whether you can make this a line chart. And plot the sentiment of a song over time. Like which songs start off joyful and end in sadness.

Something like this chart: 
http://www.nytimes.com/interactive/2009/07/02/business/economy/20090705-cycles-graphic.html

**Comment by demetriospogkas** [comment]
Thank you for this @qdinhbui2! I don't really want to use the radar charts I've attached on my original post, and although I've already plotted a few spider charts and I don't feel motivated to use them either, so I will come up with a different plot. A kind of line chart is one thing that I had in mind. The idea about how songs begin and end sound really interesting (only concern, that songs, especially punk songs are short with maybe a narrow range of vocabulary used, so a line plot of that, might be like a zig-zag ping-pong lines kind of thing -- or maybe that'd be the interesting thing about it) and the link you provided seems like a unique way to visualise it. 

So, yeah, I will head that direction, and will keep you posted for feedback.

**Comment by RodrigoMenegat** [comment]
You should definitely try to group things by genre, if you go for the spider charts. I just discovered that extreme metal looks like a duck. I wonder how pop punk looks like.

I think that radar charts usually don't mean anything at all and the way we choose to position each mesure is kind of arbitrary, but it's also fun. Reminds me of sports video-games.

![cannibal_corpse](https://user-images.githubusercontent.com/28814352/29108337-72321782-7cac-11e7-9478-ae326c2877f8.png)
![sepultura](https://user-images.githubusercontent.com/28814352/29108334-722f9e1c-7cac-11e7-9fa5-be13a6cf8a50.png)
![slayer](https://user-images.githubusercontent.com/28814352/29108336-72315158-7cac-11e7-8171-b011b67f8c87.png)

And Carcass is such a dope duck that it's even looking to the other side!

![carcass](https://user-images.githubusercontent.com/28814352/29108335-72301ea0-7cac-11e7-8efe-b136e8369177.png)

**Comment by demetriospogkas** [comment]
Hey @RodrigoMenegat thanks for this, it's really interesting. Punk spiders look something like diamonds, but still I dont really find it intuitive to use them :-p

![](https://s1.postimg.org/i3evct0q7/Screen_Shot_2017-08-09_at_8.22.30_AM.png)
![](https://s1.postimg.org/o5yd3k6vj/Screen_Shot_2017-08-09_at_8.21.56_AM.png)
![](https://s1.postimg.org/tk0ug9hm7/Screen_Shot_2017-08-09_at_8.21.41_AM.png)
![](https://s1.postimg.org/hj8lirqfj/Screen_Shot_2017-08-09_at_8.22.11_AM.png)

**Comment by demetriospogkas** [comment]
# Final

## Project visuals/text

## Details

**Headline:** 
Sentimental Punk

**Published website version:**
https://goo.gl/KwnVbn

**Code repository:**
https://github.com/demetriospogkas/The-Lede-2017-Data-Projects/tree/master/code/Project-04-Sentiment-Analysis-of-Punk-Rock-Lyrics/02_Final

**Final data set(s):** 
https://github.com/demetriospogkas/The-Lede-2017-Data-Projects/tree/master/code/Project-04-Sentiment-Analysis-of-Punk-Rock-Lyrics/02_Final

## What did you find to be the most difficult part of this project?

## Are you satisfied with what you produced? Is there anything you would like to change or improve?

## Checklist

- [x] I have included my visuals
- [x] I have posted my project to my project website
- [x] I have been updating my DIARY.md with details about my process
- [x] I have uploaded/updated any Jupyter Notebooks or other datasets into my code repository

**Comment by MarinaBraem** [comment]
A very cool result! I like it :-) and your progress in graphic design and layout is great!
