### ISSUE TITLE
No One Give's Up [Project]

### ISSUE THREAD

**Issue by MarinaBraem** [jsoma/data-studio-projects#77]
Please complete all of the following sections, or a robot will spookily dance around your issue! A completed version of this template can be found at https://github.com/jsoma/data-studio-projects/issues/1

# Pitch
> Nowhere do so few people give up. 
No one is so legendary and has this cult status. 
And nowhere are runners paying so much money as here. 
Is this a reason not to give up at the New York Marathon? 

## Research
**The Guardian** | Most expensive Marathons 
https://www.theguardian.com/lifeandstyle/datablog/2015/mar/17/running-costs-what-are-the-worlds-most-expensive-marathons

**Runner's World** | How has marathon changed over time?
https://rw.runnersworld.com/marathons/

**Sueddeutsche Zeitung** | Costs of the Top Runners
http://www.sueddeutsche.de/sport/marathon-in-new-york-als-wuerden-seine-gegner-bleiwesten-tragen-1.3238512

## Details

**Possible headline(s):** 
– No One Give's Up
– Most expensive Legend

**Data set(s):** 
**AIMS** | Association of International Marathons and Distance Races 
http://aims-worldrunning.org/
**AIMS | Meta-Data:** 
http://www.arrs.net/ or http://www.arrs.net/Meta.htm
**Statista** (Runners World, AIMS): https://de.statista.com

**Code repository:** 
https://github.com/MarinaBraem/New-Data-Studio/tree/master/Code/Project3_Marathon_Finisher

**Possible problems/fears/questions:** 

## Work so far
![no_one_gives_up_finsiher-01](https://user-images.githubusercontent.com/28846818/28953846-0b6b2bbc-78a9-11e7-85e1-2cb15a68629f.png)
![no_one_gives_up_finisher-02](https://user-images.githubusercontent.com/28846818/28953852-16b12bac-78a9-11e7-8ca4-bd4161f95f0d.png)
![no_one_gives_up_finsiher-03](https://user-images.githubusercontent.com/28846818/28953853-185e5d26-78a9-11e7-83c7-4b0ff80a9d7a.png)

## Checklist

This checklist must be completed before you submit your draft.

- [X] I have already spent time with my data set, opening it, exploring it, etc
- [X] I have created a "DIARY.md" file to save links and list all of the terrible, no good problems I come across
- [X] My issue issue has `[Project]` in the title
- [X] My issue links to my data set(s)
- [X] My issue links to my code repository
- [X] My issue explains what I'd like to explore in the data set
- [X] My issue includes images - either inspiration or what I've done so far
- [ ] I have received two comments of peer feedback on my pitch issue

**Comment by qdinhbui2** [comment]
This is a fun pitch, if I understand it correctly. You want to look at the percentage of runners who run each marathon and finish it right? And you're saying that a greater share of people who run the New York Marathon actually finish it relative to other races right?

If that's true, then what you'll want to do in your first chart is scale everything to 100% to account for the different number of people who run in each race. That will give a more accurate apples-to-apples comparison. 

Then label the gap (your teal bars) as "percentage of people who didn't finish".

I enjoy the time series as well. Try the same strategy for each marathon. One more interesting idea would be to add all the top marathons together, to see if people are getting better at running marathons overall (fewer quits among the elite).

Ok. So then you have a neat fact. Now you need to do some reporting to explain why. A good article is a two-step process. Open the reader's mind to a new way of thinking; now fill it with something.

**Comment by MarinaBraem** [comment]
Very cool, thank you for this helpful feedback!
