### ISSUE TITLE
MPs' demographics over time [Project]

### ISSUE THREAD

**Issue by marcelpauly** [jsoma/data-studio-projects#79]
# Pitch

## Summary

Gemany is going to elect a new Parliament in September. For this reason I want to have a look into the past parliamentary terms and find out how the Bundestag was composed of different demographic groups: How did the percentage of female MPs develop over time, how did the age distribution do so and how have different professions been represented?

## Details

**Possible headline(s):** Germany's Representatives

**Data set(s):** the German parliament's so called data handbook ([1949-1999](https://www.bundestag.de/blob/283210/8c97b35e267a3ba3db6994e8fa7dfe99/datenhandbuch_1949_1999-data.zip), [since 1990](https://www.bundestag.de/datenhandbuch))

**Code repository:** https://github.com/marcelpauly/data-studio-projects/tree/master/code/mps_demographics
	
**Possible problems/fears/questions:** a lot of PDFs …

## Work so far

I downloaded all the data from the past and the Bundestag emailed me the very latest data from the current parliamentary term. Unfortunately most of them are PDFs so right now I'm working on importing everything I need with Tabula …

## Checklist

This checklist must be completed before you submit your draft.

- [x] I have already spent time with my data set, opening it, exploring it, etc
- [x] I have created a "DIARY.md" file to save links and list all of the terrible, no good problems I come across
- [x] My issue issue has `[Project]` in the title
- [x] My issue links to my data set(s)
- [x] My issue links to my code repository
- [x] My issue explains what I'd like to explore in the data set
- [ ] My issue includes images - either inspiration or what I've done so far
- [ ] I have received two comments of peer feedback on my pitch issue

**Comment by marcelpauly** [comment]
# Update

## Content

I imported all data with Tabula and tried different graphs: linecharts (normal and step lines), barcharts, scatterplots … In the end I did something in between these types to show both the developments over time and the comparison between the different parties:

![women](https://user-images.githubusercontent.com/7937281/29125264-52b8262a-7ce9-11e7-9bf0-2a6050d21d0d.png)

![average_age](https://user-images.githubusercontent.com/7937281/29125275-56df3d56-7ce9-11e7-9190-b4bb10cd745e.png)

![new_mps](https://user-images.githubusercontent.com/7937281/29125288-5d9fa8f6-7ce9-11e7-9657-de6810e4c4a1.png)

I also did a mobile version for the female MPs chart:

![women_mobile](https://user-images.githubusercontent.com/7937281/29125294-61e193a2-7ce9-11e7-97f0-96496e88cb82.png)

## Any changes in direction or topic?

Nope.

## Problems/Questions

They changed the categories of professions at some point so I couldn't analyse them in a way that makes sense.

I also plotted a heatmap with the age distributions. I did it with Seaborn. But when I open it in illustrator they don't have editable text. Is there anything besides `matplotlib.rcParams['pdf.fonttype'] = 42` I have to do? (Also `sns.set_style(rc={"pdf.fonttype": 42})` doesn’t change anything …)

![index](https://user-images.githubusercontent.com/7937281/29125392-a57c99ea-7ce9-11e7-914e-0538b3b85c35.png)

## Checklist
	
- [x] I have included my visuals
- [x] I have added writing about my topic
- [x] I have been updating my DIARY.md with details about my process
- [x] I have uploaded/updated any Jupyter Notebooks or other datasets into my code repository
- [ ] I have received two comments of peer feedback on my project update

**Comment by marcelpauly** [comment]
# Update

## Content

I refined my visuals and created a mobile version for each one:

![women](https://user-images.githubusercontent.com/7937281/29288097-89429ff2-8105-11e7-9118-d27ee18e14d9.png)

![women_mobile](https://user-images.githubusercontent.com/7937281/29288096-893fdf42-8105-11e7-9922-abbc809ef1bf.png)

<img width="1101" alt="average_age" src="https://user-images.githubusercontent.com/7937281/29288093-893ac2fa-8105-11e7-9319-e5c5c30ce3fe.png">

![average_age_mobile](https://user-images.githubusercontent.com/7937281/29288094-893c7eba-8105-11e7-90d5-17756463f469.png)

![new_mps](https://user-images.githubusercontent.com/7937281/29288095-893e1b08-8105-11e7-8a0f-83490c93a1dd.png)

![new_mps_mobile](https://user-images.githubusercontent.com/7937281/29288098-89471b0e-8105-11e7-9fc7-36f7cecf3d57.png)

## Any changes in direction or topic?

I'm not working any longer on that age groups heatmap but I want to do another visual: small multiples for the parliament's demographic groups (gender and age groups) compared with the population. I'm using population pyramids for that. They should show how young/old people and women are underrepresented and middle-aged men are highly overrepresented. (And how it changed over time.)

I'm still working on getting the data for this. Right now I only have it for 2013 and it looks like this:

![test](https://user-images.githubusercontent.com/7937281/29287898-d1147e6e-8104-11e7-8352-cc004842ef36.png)

## Problems/Questions

Not sure if I get the data for the last one …

## Checklist

- [x] I have included my visuals
- [x] I have added writing about my topic
- [x] I have been updating my DIARY.md with details about my process
- [x] I have uploaded/updated any Jupyter Notebooks or other datasets into my code repository
- [ ] I have received two comments of peer feedback on my project update

**Comment by MarinaBraem** [comment]
Very impressive implementation and visualization. The pattern in the visualization speaks for itself and is exciting to follow. The application for mobile looks nice solved as well and I think, even if the legends are no longer visible by scrolling down, the topic is not overwhelming the reader. I like as well the last visualization with the age pyramid and the comparison between population/parliament (men/women). It's a meaningful comparison and speaks visually as well. Only one question: How works your x-scale?

**Comment by marcelpauly** [comment]
# Final

## Project visuals/text

Over the past days I worked on the small multiples with the population pyramids. I included the final version [into the article](https://marcelpauly.github.io/data-studio-projects/mps_demographics/). Here's a GIF preview of it:

![pyramids](https://user-images.githubusercontent.com/7937281/29443993-febf2452-83a9-11e7-9790-d7037d01a06d.gif)

I didn't change my old three major graphics:

![women](https://user-images.githubusercontent.com/7937281/29442274-88ce9486-839e-11e7-9bc1-7d0a4c9cb749.png)

<img width="1101" alt="average_age" src="https://user-images.githubusercontent.com/7937281/29442288-934fcfd8-839e-11e7-9013-bb8b31926506.png">

![new_mps](https://user-images.githubusercontent.com/7937281/29442291-97ceb75e-839e-11e7-89f6-ac757acf246d.png)

## Details

**Headline:** Demographically the German Bundestag is far away from being representative

**Published website version:** https://marcelpauly.github.io/data-studio-projects/mps_demographics/

**Code repository:** https://github.com/marcelpauly/data-studio-projects/tree/master/code/mps_demographics

**Final data set(s):** https://github.com/marcelpauly/data-studio-projects/tree/master/code/mps_demographics/input/data

## What did you find to be the most difficult part of this project?

To find reliable data to create the population pyramids. The parliament only provides aggregated data grouped by gender **or** age groups and no raw data. That's why I had to scrape raw data about the MPs from Wikipedia and double-check it. That took the most time, [I described the process in the notebook](https://github.com/marcelpauly/data-studio-projects/blob/master/code/mps_demographics/mps-demographics.ipynb).

## Are you satisfied with what you produced? Is there anything you would like to change or improve?

The small multiples and the GIF aren't perfect but on the whole I'm quite happy.

## Checklist

- [x] I have included my visuals
- [x] I have posted my project to my project website
- [x] I have been updating my DIARY.md with details about my process
- [x] I have uploaded/updated any Jupyter Notebooks or other datasets into my code repository
