### ISSUE TITLE
NBA refereeing: Who is favored in the last two minutes? [Project]

### ISSUE THREAD

**Issue by chrgavalas** [jsoma/data-studio-projects#80]
Please complete all of the following sections, or a robot will spookily dance around your issue! A completed version of this template can be found at https://github.com/jsoma/data-studio-projects/issues/1

# Pitch
Since March 2015, the NBA has been issuing post-game reports reviewing referees’ calls during the final two minutes of close games. Did you know that the most incorrect non call refs make include offensive fouls?

## Summary
The original reports are PDFs but journalist Russell Goldenberg has been converting them to spreadsheet-friendly CSVs. By analyzing the data, I’d like to find and visualize which players and teams are benefitting the most from incorrect calls as well as the type of calls refs mostly get wrong. 

## Details
The dataset includes all calls from the most recently reviewed day of games. The vast majority is correct calls and correct non calls, but there is a significant amount of incorrect non calls and just a small number of incorrect calls. 

**Possible headline(s):** 
NBA: As the clock ticks down, who gets the final whistle?
**Data set(s):** 
http://official.nba.com/nba-last-two-minute-reports-archive/
**Code repository:** 
https://github.com/chrgavalas/data-projects/tree/master/code/project6
**Possible problems/fears/questions:** 
I really don't know if I will be able to pull out info about the correlation of remaining time/type of incorrect calls and/or the analogy between home teams vs away teams who benefit the most in the last two minutes. I would need help for this. 
## Work so far
Cleaned the dataset, did some analysis and graphs. 
## Checklist

This checklist must be completed before you submit your draft.

- [x] I have already spent time with my data set, opening it, exploring it, etc
- [x] I have created a "DIARY.md" file to save links and list all of the terrible, no good problems I come across
- [x] My issue issue has `[Project]` in the title
- [x] My issue links to my data set(s)
- [x] My issue links to my code repository
- [x] My issue explains what I'd like to explore in the data set
- [x] My issue includes images - either inspiration or what I've done so far
- [ ] I have received two comments of peer feedback on my pitch issue

**Comment by chrgavalas** [comment]
# Update
	
## Content
In the heat of the moment and as a close NBA game comes to an end, players have all eyes on them and referees are expected to get it dead right. But in wanting to do so they steadily prefer to let the game be more physical and don’t intervene much. That’s where the vast majority of their mistakes comes from, data insist.
In March 2015, the NBA took a huge step in reinforcing its position as the leading sporting association in the world by reviewing plays from all games that enter their last two minutes with a five point lead, at the most. The report for each game is released typically the next day and is intended to provide extra transparency around debated calls.
But when it comes to the type of wrong decisions refs make at the end of close games, the top 10 list is increasingly filled in with incorrect non calls: offensive and personal fouls not called, fouls on a shooting attempt and on a loose ball not called as well as traveling violations ignored. 
![download-4](https://user-images.githubusercontent.com/30135399/29186419-6cda9d52-7dda-11e7-872a-791ab2e54751.png)
Here’s a look at one of the most common non call violations:
![travel](https://user-images.githubusercontent.com/30135399/29187983-9751be08-7ddf-11e7-974f-1654395dda1c.gif)
And one such call actually determined who will eventually win a decisive tie between the two top NBA teams on Christmas day in 2016, when Kevin Durant wasn't awarded a clear foul at the last second of his team away game against the Cleveland Cavaliers.
![durant_call](https://user-images.githubusercontent.com/30135399/29187666-8d893c3a-7dde-11e7-9795-e7132e065a2f.gif)
After the game, he spoke openly about the dangers associated with the measure. "You don’t throw the refs under the bus like that ‘cause the next game, that group of refs, whoever it is, gonna come out and be tense when they’re refereeing the game and they’re gonna try to get every play right, try to be perfect without just going out there and relaxing and making the right call", he said. 
But that's not to say Lebron James, the Cavaliers super star whose team won that night praised the decision reviewing process. He just gave a different perspective, admitting he should have been given a technical for hanging on the rim after a dunk and focusing on the importance of examining the correctness of calls throughout the game and not just at the end, when pressure is much higher for all sides. "It’s not fair to the referees that you only talk about the final two minutes and not the first 46", he claimed. 
**Lots of disapproval but refs got better this year**
Data gives credence to the fact that 2016 was indeed the year most incorrect non calls were given compared to both 2015 and 2017, even though the sample for the first year is much smaller. Mistakes were highly decreased this season which shows the measure might have helped the referees’ performance contrary to its critics.
![download-5](https://user-images.githubusercontent.com/30135399/29188084-f6e6953c-7ddf-11e7-9a41-14229e330678.png)
Furthermore, another reason referees can take pride in is the high percentage of the actual correct calls they make. Even after evaluation and examination of all reports during the roughly three seasons, when refs blow the whistle, calls are determined to be correct over 89% of the time. 
Correct non calls and correct calls are dominant (13758) compared to the incorrect non calls and incorrect calls (1601) which however draw the attention of the public. 
![download-7](https://user-images.githubusercontent.com/30135399/29188130-1e3ff876-7de0-11e7-83f6-8c076c11708b.png)
And aside from this, the National Basketball Referees Association (NBRA), which represents the 63 active NBA referees, believes that the subjective nature of what is considered a foul and necessitates a whistle undermines the validity of the non-calls assessed to be incorrect. 
“People forget that perfection is impossible, especially when it comes to officiating the greatest athletes in the world,” said Lee Seham, National Basketball Referees Association General Counsel in May 2015, a few months after the initiative was introduced.  
According to their view, flow of game, how the possible contact influenced the play, speed of play and having just six eyes watching the greatest athletes in the world – all of these factors influence the referees’ decision to blow the whistle.
**So who's the most advantaged and disadvantaged player?**
According to the data, **Marcin Gortat** of the Washington Wizards is the most advantaged player by referees in the last two minutes of close games having received to his favor almost 30 incorrect calls or non calls. He is followed in the list by Al Horford of the Boston Celtics, James Harden of the Houston Rockets, Brook Lopez of the Los Angeles Lakers and Daymond Green of the Golden State Warriors. 
![download-8](https://user-images.githubusercontent.com/30135399/29188692-e8884128-7de1-11e7-9432-90b75fcd8127.png)
On the opposite side, **James Harden** is counted as the most disadvantaged player by refs, followed by Andrew Wiggins of the Minnesota Timberwolves, Isaiah Thomas of the Boston Celtics, Paul George of the Indiana Pacers and Gordon Hayward of the Boston Celtics. 
![download-9](https://user-images.githubusercontent.com/30135399/29188724-0c053e8a-7de2-11e7-8482-e9b34e5c0fd8.png)
But on the flip side, Harden’s team, the Houston Rockets has been favored most of the times in those crucial last few seconds of neck to neck games. Second come the Toronto Raptors, followed by the Washington Wizards, the New York Knicks and the Dallas Mavericks. 
	
## Any changes in direction or topic?
Actually yes! Instead of just presenting the new form of reviewing along with some basic findings further down as the core of my storyline I ended up figuring it'd more focused and interesting to jump to a conclusion the data partly shows and make this my headline: the fact that as time goes down, refs don't intervene so much in the game.
## Problems/Questions
The problem is I'd want to achieve one more thing with my data in order to further buttress my argument but haven't been able to yet. I want to further break down time so as to show that in the last few seconds (let's say 10) whistles are even fewer than in the last 60 seconds and then fewer than those in seconds 60-120. That would make the argument very solid. I don't know how I can split the data though! 
## Checklist
	
- [x] I have included my visuals
- [x] I have added writing about my topic
- [x] I have been updating my DIARY.md with details about my process
- [x] I have uploaded/updated any Jupyter Notebooks or other datasets into my code repository
- [ ] I have received two comments of peer feedback on my project update

**Comment by sarahslo** [comment]
so the incorrect calls, what order is that in? by year? are the labels wrong?

and i'd suggest putting the advantaged players and the disadvantaged on the same scale. you see that the advantaging tends to happen more
![screen shot 2017-08-14 at 10 09 12 pm](https://user-images.githubusercontent.com/659014/29299525-572d7c20-813d-11e7-80eb-41ce1dd825cc.png)

see what i mean? scale is important, charts should be comparable.

**Comment by chrgavalas** [comment]
# Update
	
## Content
In the heat of the moment and as a close NBA game comes to an end, players have all eyes on them and referees are expected to get it dead right. But in wanting to do so they steadily prefer to let the game be more physical and don’t intervene much. That’s where the vast majority of their mistakes comes from, data insist.

In March 2015, the NBA took a huge step in reinforcing its position as the leading sporting association in the world by reviewing plays from all games that enter their last two minutes with a five point lead, at the most.

But when it comes to the type of wrong decisions refs make at the end of close games, the top 10 list is increasingly filled in with incorrect non calls: offensive and personal fouls not called, fouls on a shooting attempt and on a loose ball not called as well as traveling violations ignored.

<img width="890" alt="most-common-wrong" src="https://user-images.githubusercontent.com/30135399/29326665-6f880966-81ba-11e7-95aa-138aa5c835a4.png">

Here’s a look at one of the most common non call violations:

![travel](https://user-images.githubusercontent.com/30135399/29326680-7dd715e8-81ba-11e7-948f-1da3123f690f.gif)

Actually, when it comes to **wrong decisions** by referees in the last two minutes, non calls amount to 89% of the total whereas incorrect calls measure up to only 11%.

<img width="524" alt="distribution-of-incorrect-calls" src="https://user-images.githubusercontent.com/30135399/29326703-95a53c4a-81ba-11e7-9305-5201c9068408.png">

The report for each game is released typically the next day and is intended to provide extra transparency around debated calls. But despite the good intentions it wasn’t positively accepted by neither the referees nor the players.

Both **LeBron James** and **Kevin Durant**, the undeniably best offensive duo of the league, have been vocal about the dangers associated with the measure. 

"You don’t throw the refs under the bus like that ‘cause the next game, that group of refs, whoever it is, gonna come out and be tense when they’re refereeing the game and they’re gonna try to get every play right, try to be perfect without just going out there and relaxing and making the right call", Durant said in **December 2016** after a loss to the Cleveland Cavaliers in which the Golden State Warriors super star *wasn’t awarded a foul* in the last few seconds that could have changed the winner. 

![durant_call](https://user-images.githubusercontent.com/30135399/29326727-b1a12f9e-81ba-11e7-93c8-e4f35222a408.gif)

But even LeBron James whose team won on that night admitted he *should have been given a technical* for hanging on the rim after a dunk and stated that "it’s not fair to the referees that you only talk about the final two minutes and not the first 46".

Data gives credence to the fact that 2016 was indeed the year most incorrect non calls were given compared to both 2015 and 2017, *even though the sample for the first year is much smaller*. 

Mistakes were highly decreased this season which shows the measure might have helped the referees’ performance contrary to its critics.

<img width="630" alt="decisions-per-year" src="https://user-images.githubusercontent.com/30135399/29326767-cb13c522-81ba-11e7-958c-e73e032c13d7.png">

Furthermore, another reason referees can take pride in is the high percentage of the actual correct calls they make. Even after evaluation and examination of all reports during the roughly three seasons, refs are correct over 89% of the time. 

Correct non calls and correct calls are dominant (13.758) compared to the incorrect non calls and incorrect calls (1.601) which however draw the attention of the public. 

<img width="496" alt="distribution-of-calls" src="https://user-images.githubusercontent.com/30135399/29326784-dbc9f594-81ba-11e7-9720-e242e5b01824.png">

And aside from this, the **National Basketball Referees Association (NBRA)**, which represents the 63 active NBA referees, believes that the subjective nature of what is considered a foul and necessitates a whistle undermines the validity of the non-calls assessed to be incorrect. 

"People forget that perfection is impossible, especially when it comes to officiating the greatest athletes in the world," said **Lee Seham**, National Basketball Referees Association General Counsel in May 2015, a few months after the initiative was introduced. 

According to their view, flow of game, how the possible contact influenced the play, speed of play and having just six eyes watching the greatest athletes in the world – all of these factors influence the referees’ decision to blow the whistle. 

According to the data, **Marcin Gortat** of the Washington Wizards is the most advantaged player by referees in the last two minutes of close games having received to his favor almost 30 incorrect calls or non calls. He is followed in the list by Al Horford of the Boston Celtics, James Harden of the Houston Rockets, Brook Lopez of the Los Angeles Lakers and Daymond Green of the Golden State Warriors.  

<img width="918" alt="mostly-advantaged" src="https://user-images.githubusercontent.com/30135399/29326816-f98e212c-81ba-11e7-9c72-46615abe2509.png">

On the flip side, **James Harden** is counted as the most disadvantaged player by refs, followed by Andrew Wiggins of the Minnesota Timberwolves, Isaiah Thomas of the Boston Celtics, Paul George of the Indiana Pacers and Gordon Hayward of the Boston Celtics. 

<img width="905" alt="mostly-disadvantaged" src="https://user-images.githubusercontent.com/30135399/29326830-058906b8-81bb-11e7-960c-fe17dcb6770a.png">
	
## Any changes in direction or topic?
After analyzing further the data, it looks as if the non calls aren't getting proportionately more as the clock ticks down to the last few seconds. So I will stick to the fact that this is the case in the whole last two minutes, and I will change my headline to reflect exactly this. So, instead of saying "as the clock ticks down" I am going to say "down the stretch". 
	
## Problems/Questions
I wasn't able to find the proportion between calls given in favor of away vs home teams. The story can be read for the most part by a targeted audience that understands the game of basketball so by trying to explain the human nature of the mistakes I wanted to make it more accessible by the general public. I don't know if I quite succeeded in it, though. 
	
## Checklist
	
- [x] I have included my visuals
- [x] I have added writing about my topic
- [x] I have been updating my DIARY.md with details about my process
- [x] I have uploaded/updated any Jupyter Notebooks or other datasets into my code repository
- [] I have received two comments of peer feedback on my project update

**Comment by chrgavalas** [comment]
# Final

## Project visuals/text
In the heat of the moment and as a close NBA game comes to an end, players have all eyes on them and referees are expected to get it dead right. But in wanting to do so they steadily prefer to let the game be more physical and don’t intervene much. That’s where the vast majority of their mistakes comes from, data insist.

In March 2015, the NBA took a huge step in reinforcing its position as the leading sporting association in the world by reviewing plays from all games that enter their last two minutes with a five point lead, at the most.

But when it comes to the type of wrong decisions refs make at the end of close games, the top 10 list is increasingly filled in with incorrect non calls: offensive and personal fouls not called, fouls on a shooting attempt and on a loose ball not called as well as traveling violations ignored.

<img width="325" alt="most-common-wrong" src="https://user-images.githubusercontent.com/30135399/29421700-e5e48f5a-8343-11e7-9cd0-bb1e30df2e2e.png">

Here’s a look at one of the most common non call violations:

![travel](https://user-images.githubusercontent.com/30135399/29421707-ec0edb4c-8343-11e7-9945-9e24682e1864.gif)

Actually, when it comes to wrong decisions by referees in the last two minutes, non calls amount to 89% of the total whereas incorrect calls measure up to only 11%.

<img width="325" alt="distribution-of-incorrect-calls" src="https://user-images.githubusercontent.com/30135399/29421731-f52e7246-8343-11e7-96e3-eb23bd68bedd.png">

The report for each game is released typically the next day and is intended to provide extra transparency around debated calls. But despite the good intentions it wasn’t positively accepted by neither the referees nor the players.

Both LeBron James and Kevin Durant, the undeniably best offensive duo of the league, have been vocal about the dangers associated with the measure.

"You don’t throw the refs under the bus like that ‘cause the next game, that group of refs, whoever it is, gonna come out and be tense when they’re refereeing the game and they’re gonna try to get every play right, try to be perfect without just going out there and relaxing and making the right call", Durant said in December 2016 after a loss to the Cleveland Cavaliers in which the Golden State Warriors super star wasn’t awarded a foul in the last few seconds that could have changed the winner.

![durant_call](https://user-images.githubusercontent.com/30135399/29421758-0a5bf33c-8344-11e7-893a-7a9d0fb38cf5.gif)

But even LeBron James whose team won on that night admitted he should have been given a technical for hanging on the rim after a dunk and stated that "it’s not fair to the referees that you only talk about the final two minutes and not the first 46".

Data gives credence to the fact that 2016 was indeed the year most incorrect non calls were given compared to both 2015 and 2017, even though the sample for the first year is much smaller.

Mistakes were highly decreased this season which shows the measure might have helped the referees’ performance contrary to its critics.

<img width="325" alt="decisions-per-year" src="https://user-images.githubusercontent.com/30135399/29421774-15b3347a-8344-11e7-9710-4a3b229072f9.png">

Furthermore, another reason referees can take pride in is the high percentage of the actual correct calls they make. Even after evaluation and examination of all reports during the roughly three seasons, refs are correct over 89% of the time.

Correct non calls and correct calls are dominant (13.758) compared to the incorrect non calls and incorrect calls (1.601) which however draw the attention of the public.

<img width="325" alt="distribution-of-calls" src="https://user-images.githubusercontent.com/30135399/29421779-1a77988e-8344-11e7-83ce-5a0221cd6e06.png">

And aside from this, the National Basketball Referees Association (NBRA), which represents the 63 active NBA referees, believes that the subjective nature of what is considered a foul and necessitates a whistle undermines the validity of the non-calls assessed to be incorrect.

"People forget that perfection is impossible, especially when it comes to officiating the greatest athletes in the world," said Lee Seham, National Basketball Referees Association General Counsel in May 2015, a few months after the initiative was introduced.

According to their view, flow of game, how the possible contact influenced the play, speed of play and having just six eyes watching the greatest athletes in the world – all of these factors influence the referees’ decision to blow the whistle. 

According to the data, Marcin Gortat of the Washington Wizards is the most advantaged player by referees in the last two minutes of close games having received to his favor almost 30 incorrect calls or non calls. He is followed in the list by Al Horford of the Boston Celtics, James Harden of the Houston Rockets, Brook Lopez of the Los Angeles Lakers and Daymond Green of the Golden State Warriors.

<img width="325" alt="mostly-advantaged" src="https://user-images.githubusercontent.com/30135399/29421785-1eee89ae-8344-11e7-8ee7-1f45fbe723c3.png">

On the flip side, James Harden is counted as the most disadvantaged player by refs, followed by Andrew Wiggins of the Minnesota Timberwolves, Isaiah Thomas of the Boston Celtics, Paul George of the Indiana Pacers and Gordon Hayward of the Boston Celtics.

<img width="325" alt="mostly-disadvantaged" src="https://user-images.githubusercontent.com/30135399/29421813-380c1cee-8344-11e7-8a9b-366093a3d0ed.png">

## Details

**Headline:** 
NBA refs mistakes: Down the stretch, the whistle is not blown

**Published website version:**
https://chrgavalas.github.io/data-projects/NBA-refereeing/

**Code repository:**
https://github.com/chrgavalas/data-projects/tree/master/code/project6

**Final data set(s):** 
https://github.com/chrgavalas/data-projects/blob/master/code/project6/all_games.csv

## What did you find to be the most difficult part of this project?
To find the right angle of the story so that it would be more revealing, interesting and would go further than just present some basic analysis on players, teams and referees. 

## Are you satisfied with what you produced? Is there anything you would like to change or improve?
I am satisfied because this project goes one step further both in terms of storyline and graphs. I would have liked to include analysis on whether home teams are mostly favored in the last minutes at the detriment of away teams. But wasn't able to pull this info out from my data frame. 

## Checklist

- [x] I have included my visuals
- [x] I have posted my project to my project website
- [x] I have been updating my DIARY.md with details about my process
- [x] I have uploaded/updated any Jupyter Notebooks or other datasets into my code repository
