### ISSUE TITLE
Forbes 2017 World's Highest-Paid Celebrities: Call Me Startup Investors [Project]

### ISSUE THREAD

**Issue by hichenwang** [jsoma/data-studio-projects#82]
Please complete all of the following sections, or a robot will spookily dance around your issue! A completed version of this template can be found at https://github.com/jsoma/data-studio-projects/issues/1

# Pitch

## Summary
When I was exploring www.crunchbase.com, a dataset of global startups, I found the name of some most influential investors looked very familiar...LeBron James # 14, Justin Bieber # 18, Leonardo DiCaprio ranks # 26, Stephen Curry # 28.... 

Then, I chose to use the new Forbes 2017 World's Highest-Paid Celebrities list as my selection of celebrities. 

The questions I want to analyze include:
(1) Who are the most active startup investors?
(2) What kinds of companies are they interested in? When did they start to invest in startups?
(3) Which round of funding do they usually join?
(4) How have their investments been going? (companies been acquired? closed? more rounds of funding?)
(5) Any difference between men and women celebrities?

## Details

**Possible headline(s):** Forbes 2017 World's Highest-Paid Celebrities: Call Me Startup Investors

**Data set(s):** 
Forbes 2017 World's Highest-Paid Celebrities list is very easy to get:
https://github.com/hichenwang/Data_Studio_Projects/tree/master/code/project_3_forbes100_startups
I need to scrape the celebrities' investments as well as the info of the startups they put their money in. 

**Code repository:** https://github.com/hichenwang/Data_Studio_Projects/tree/master/code/project_3_forbes100_startups
	
**Possible problems/fears/questions:** 
(1) I want to make my visualization something like this: https://www.wsj.com/graphics/ceopay-2017/
As readers scroll down, the background images will change, but I don't really know how to realize this.

<img width="1274" alt="screen shot 2017-08-06 at 11 45 54 pm" src="https://user-images.githubusercontent.com/28814446/29011984-ac70892c-7b05-11e7-990b-760805afac5e.png">

<img width="1280" alt="screen shot 2017-08-06 at 11 46 07 pm" src="https://user-images.githubusercontent.com/28814446/29011964-81e22c24-7b05-11e7-934c-d5bd23b2e023.png">

## Checklist

This checklist must be completed before you submit your draft.

- [x] I have already spent time with my data set, opening it, exploring it, etc
- [x] I have created a "DIARY.md" file to save links and list all of the terrible, no good problems I come across
- [x] My issue issue has `[Project]` in the title
- [x] My issue links to my data set(s)
- [x] My issue links to my code repository
- [x] My issue explains what I'd like to explore in the data set
- [x] My issue includes images - either inspiration or what I've done so far
- [ ] I have received two comments of peer feedback on my pitch issue

**Comment by qdinhbui2** [comment]
This is a great pitch. A fun idea that I think you could send to tech crunch, wired or recode or something. I don't think you need to make an interactive graphic. Just start with the WSJ piece as inspiration all the grey lines being normal investors and all the green lines being celebrity investors ordered by highest paid.  

Then you could do another graphic in the same form ordered by greatest return.

Those two would be make for a great one-two punch.
