### ISSUE TITLE
What makes a funny joke, Part 2 [Project]

### ISSUE THREAD

**Issue by adaskalopoulou** [jsoma/data-studio-projects#84]
# Pitch

## Summary
Since 1999, Jester has been telling jokes. The website, built by UC Berkeley’s Laboratory for Automation Science and Engineering, asks users to rate its sometimes-humorous offerings, and then uses those answers to guess which of the remaining 100+ jokes you’ll like best. The UC Berkeley team has released databases that contain around 6 million ratings of 150 jokes from more than 100,000 anonymous users.

This project is the continuation of the project: https://github.com/jsoma/data-studio-projects/issues/41

In the revision of this project I plan to use our newly acquired skills in text analysis, sentiment analysis and clustering to investigate:
1. Are some joke topics more positive than others?
2. Which joke topics receive better ratings? 
3. What makes a good joke (with high ratings)? a) Surprise? b) Anticipation? c) Positivity?
4. Are long or short jokes more popular? 

## Details

**Data set(s):** 
http://eigentaste.berkeley.edu/dataset/

**Code repository:** 
https://github.com/adaskalopoulou/studio-projects/tree/master/code/project2

### Word count
I counted the words in each joke and I created a new variable based on their length:
1) a joke with less than 15 words is called "very short"
2) a joke with more than 15 and less than 40 words is called "short"
3) a joke with more than 40 and less than 80 words is called "medium"-length
4) a joke with more than 80 and less than 150 words is called "long"
5) a joke with more than 150 words is called "very long"

Then I looked into differences in ratings based on whether a joke is longer or shorter. Again, no major patterns were identified. 
Slight differences:
Users didn't like "very short" and "short" jokes that much.
Users found the "very long" jokes a bit funnier. 

![screenshot 2017-07-31 17 46 29](https://user-images.githubusercontent.com/28814404/28799863-3a80005a-7618-11e7-87b0-3df837a3b34c.png)
This might look significant, but I should remind you that the rating scale is from -10 to 10. 

## Checklist

- [x] I have already spent time with my data set, opening it, exploring it, etc
- [x] I have created a "DIARY.md" file to save links and list all of the terrible, no good problems I come across
- [x] My issue issue has `[Project]` in the title
- [x] My issue links to my data set(s)
- [x] My issue links to my code repository
- [x] My issue explains what I'd like to explore in the data set
- [x] My issue includes images - either inspiration or what I've done so far
- [ ] I have received two comments of peer feedback on my pitch issue

**Comment by amandolinjames** [comment]
This is super interesting!! Are you planning to chart it? Curious how you'll visualize it.

**Comment by adaskalopoulou** [comment]
# Update
    	
## Content

### I created 10 clusters/groups of jokes. 
These jokes are characterized by the following words:

Cluster 1: news owner told good sandwiches replied trainee bad talk doctor
Cluster 2: engineer says hell guy person like just going make did
Cluster 3: man doctor says blah woman old replies dont father wife
Cluster 4: hear did tell dyslexic wanted carter nelson willie bird school
Cluster 5: lightbulb does room change drink professor darwin neutron pants teddy
Cluster 6: shredder asked come replied work station degree graduate drunk yes
Cluster 7: difference whats president slash doesnt sasquatch toilet engineers plumber washington
Cluster 8: bulb screw light does men funny father thats night presidents
Cluster 9: 00 10 goes asks duck american person pope norris chuck
Cluster 10: time job school broom im mickey expression went applications psychiatrist

In the following graph one can see the relationship between the different group of jokes and their ratings. 

<img width="1049" alt="artboard 14 2x" src="https://user-images.githubusercontent.com/28814404/29289904-42c39598-810c-11e7-9e27-09c6d67be595.png">

### I did some sentiment analysis on the jokes. 

In the following graph one can see the relationship ratings and their level of positivity, surprise, and anticipation. 

<img width="677" alt="scatter3 2x" src="https://user-images.githubusercontent.com/28814404/29290162-101756ba-810d-11e7-8481-1ad10e182dbf.png">

Finally, in the following graph one can see the relationship between the different group of jokes and their level of positivity. I picked positivity levels because it was the only sentiment that made a difference in the ratings of the jokes. 

<img width="1047" alt="artboard 3 2x" src="https://user-images.githubusercontent.com/28814404/29290107-e9f2d1b2-810c-11e7-8718-11896dcef58b.png">




## Questions:

### 1) I am lost when it comes to showing the actual text of the jokes in the graphs. I would probably want to show 20 texts in total. The ten best and the ten worst.
An option would be to just to mark the dots-jokes with a letter, A, B, C, etc and display the joke text in a side-box.
Another option is to try something like this, but I don't feel that this really works. It's unreadable. 

<img width="1049" alt="artboard 14 2x_with_text" src="https://user-images.githubusercontent.com/28814404/29289292-e0ed5ef0-8109-11e7-9c83-8278229c7eec.png">

Any other thoughts/recommendations? 

### 2) I still haven't decided how to visualize the relationship between the length of jokes and ratings. 

I have tried the following:
a. This is more in harmony with the other visuals:
![screenshot 2017-08-14 15 56 37](https://user-images.githubusercontent.com/28814404/29289090-36acc84a-8109-11e7-96cb-3edf95e12df7.png)

b. These maybe are more human-readable. However, the categorization "very short", "short", "medium", "long", "very long" is subjective. 

![screenshot 2017-08-14 15 54 03](https://user-images.githubusercontent.com/28814404/29289158-658da6a2-8109-11e7-921d-8940cc5311c2.png)

![screenshot 2017-08-14 15 54 08](https://user-images.githubusercontent.com/28814404/29289162-67161f18-8109-11e7-9fde-59a96077c090.png)



## Checklist
    	
- [x] I have included my visuals
- [x] I have added writing about my topic
- [x] I have been updating my DIARY.md with details about my process
- [x] I have uploaded/updated any Jupyter Notebooks or other datasets into my code repository
- [ ] I have received two comments of peer feedback on my project update

**Comment by sarahslo** [comment]
for the jokes/text solution. remember navigation, what do you want the reader to see first, second, third. if the jokes are to be first then what if in this instance you made the charts small multiples so you could see the jokes next to the data.
![screen shot 2017-08-14 at 9 45 45 pm](https://user-images.githubusercontent.com/659014/29299075-2e9939a0-813a-11e7-9786-a52c7bdbfea6.png)

**Comment by adaskalopoulou** [comment]
# Final

## Project visuals/text

Most people rate humor as an important ingredient of life. For example, when asked to point out the most crucial traits of a spouse they usually put the “sense of humor” near the top. Given that humor is such a powerful tool for social success, what are the necessary conditions for something to be funny?

In quest of answers to this question, we looked at a UC Berkeley’s database that contains around 6 million ratings of 150 jokes from more than 100,000 anonymous users. From 1999 to 2009, “Jester”, the website built by Berkeley’s Laboratory for Automation Science and Engineering asks users to rate a list of jokes. In this analysis, we looked at the most complete set of ratings that were collected between 2006 – 2009. 

Scientists have come up with many theories but not with definitive answers about the perfect formula for funny. The three leading theories, as listed in the Stanford Encyclopedia of Philosophy, are the Superiority Theory, the Relief Theory and the Incongruity Theory. 

The Supriority Theory, simply put, supports that “our laughter expresses feelings of superiority over other people or over a former state of ourselves,” mentions John Morreall -a Doctor of Philosophy and Emeritus Professor of Religious Studies at the College of William and Mary in Williamsburg, Virginia – in his Stanford Encyclopedia entry about the philosophy of humor. According to Morreall, the Superiority Theory is based partially on René Descartes’ explanation of laughter in his 1649 book Passions of the Soul that mentions that “laughter accompanies three of the six basic emotions—wonder, love, (mild) hatred, desire, joy, and sadness. Although admitting that there are other causes of laughter than hatred, in Part 3 of this book, “Of Particular Passions,” he considers laughter only as an expression of scorn and ridicule.” However, later, in 1750 the Irish philosopher Francis Hutcheson argued that Feelings of superiority are neither necessary nor sufficient for laughter.

Similarly, when I analyzed UC Berkeley jokes using the Word-Emotion Lexicon, “EmoLex”, and we checked for anger, joy and fear we found no association between higher ratings and the existence of these emotions. 

The dominance of the Superiority Theory weakened even further in the 18th century when two new accounts of laughter started to be discussed Relief Theory and the Incongruity Theory. 

As Morreall puts it “The Relief Theory is an hydraulic explanation in which laughter does in the nervous system what a pressure-relief valve does in a steam boiler.” The idea is that laughter releases nervous energy. In 1894 the American philosopher and psychologist John Dewey said that laughter marks the ending of a period of suspense or expectation. It is a “sudden relaxation of strain, so far as occurring through the medium of the breathing and vocal apparatus… The laugh is thus a phenomenon of the same general kind as the sigh of relief.”

As Morreall puts it “The Incongruity Theory says that it is the perception of something incongruous—something that violates our mental patterns and expectations.” This theory, which was adopted by Immanuel Kant and refined by Arthur Schopenhauer, supports that what makes us laugh is the incongruity between what we expect and what actually happens. However, as mentioned in the book, in the beginning in the 1970s, “psychologists began to revise Kant's notion into what is now called the Incongruity-Resolution theory: People laugh at a situation not just because it's incongruous, but because they realize that the incongruity can be resolved or interpreted in a different way.” And this makes sense as many dramatic surprises are not pleasant at all. 

In sequence to this theory, my emotion analysis showed that positivity slightly influences the ratings of jokes by the users, while negativity didn’t play any role in their ratings. The surprise was the emotion that seemed to play some role, with jokes that have an increased level of surprise to be rated better than other. Finally, and surprisingly, the level of anticipation of the jokes was not only unimportant, but seemed to play a negative role in the ratings. 

---


<img width="526" alt="scatter3" src="https://user-images.githubusercontent.com/28814404/29440359-1a5e3c7e-8392-11e7-8bb3-60b4d455dc1a.png">




---

The two most positive jokes are considered the following:


![what_difference](https://user-images.githubusercontent.com/28814404/29440205-d737a422-8390-11e7-9e89-202301857452.png)


![what_does](https://user-images.githubusercontent.com/28814404/29440202-d45f3008-8390-11e7-9b08-1dced07088b6.png)

---



The jokes with the highest level of surprise are considered the following:


![what_hurricane](https://user-images.githubusercontent.com/28814404/29440197-cd6884f2-8390-11e7-8341-514e7011fe97.png)


![cannibals](https://user-images.githubusercontent.com/28814404/29440199-d0dc44ca-8390-11e7-82a4-88ec0231fab2.png)


---



The joke with the highest level of anticipation is considered:

![bill](https://user-images.githubusercontent.com/28814404/29440190-c8e164e4-8390-11e7-95c8-95f5e853e89f.png)



---


To explore further the question what makes a popular joke I clustered the jokes in different categories using a machine learning tool that automatically groups similar objects into sets and I present the ratings of the jokes in each group. 

---


<img width="526" alt="scatter2" src="https://user-images.githubusercontent.com/28814404/29440186-c42554c4-8390-11e7-8b06-0bee46e5ebe5.png">



---

 
As this graph shows, groups 7 and 8 received higher ratings than the rest of groups of jokes. Group 7 was characterized by words such as “father, school, little, boy, teacher, son, mother” – words that indicate that the topic is related to the family. However, the topics of some groups were more difficult to identify than others. Group 8 was characterized by words such as “engineer, hell, parrot”. Similarly, groups 1, 3 and 6 did not include words that point to one specific topic. On the other hand group 2 was related to the topic of death, group 9 was mainly mentioning the words “woman, man” and the topic of group 10 was related to doctors and diseases. Finally, the jokes of group 4 were usually following the format “What’s the difference…?”, while those of group 5 “How many … does it take to …?”.

In the following graph we can see the most popular jokes by topic/group. 

---


<img width="525" alt="scatter2long" src="https://user-images.githubusercontent.com/28814404/29440183-c0467824-8390-11e7-9160-e4390aca6409.png">



---


Surprisingly, the majority of these jokes include long texts. Most people believe that a good joke is a short joke. However, this doesn’t seem to be the case. 

---
<img width="525" alt="bar" src="https://user-images.githubusercontent.com/28814404/29440173-b3ff606c-8390-11e7-8efc-d99e82a00109.png">




## Details

**Headline:** 
What makes people laugh?
Testing the theories of humor

**Published website version:**
https://adaskalopoulou.github.io/studio-projects/project-2/

**Code repository:**
https://github.com/adaskalopoulou/studio-projects/tree/master/code/project2

**Final data set(s):** 
https://github.com/adaskalopoulou/studio-projects/tree/master/code/project2

## What did you find to be the most difficult part of this project?
Reaching meaningful conclusions. 

## Are you satisfied with what you produced? Is there anything you would like to change or improve?
Yes, I believe that given the subject matter I explored deeply the potential of the database. 

## Checklist

- [x] I have included my visuals
- [x] I have posted my project to my project website
- [x] I have been updating my DIARY.md with details about my process
- [x] I have uploaded/updated any Jupyter Notebooks or other datasets into my code repository
