### ISSUE TITLE
The handing down of buzz words [Project]

### ISSUE THREAD

**Issue by wonderfulexperience** [jsoma/data-studio-projects#85]
# Pitch

## Summary

I want to expand on my first individual project, analyzing the anecdotal macroeconomic observations by the Fed, called the Fed Beige Books. They could give insights into sectors and regions which might be more detailed and fast than official statistics.

https://wonderfulexperience.github.io/

<img width="865" alt="bildschirmfoto 2017-08-07 um 11 06 30" src="https://user-images.githubusercontent.com/28814374/29032720-7de1ba3a-7b60-11e7-881a-529ca722176b.png">

## Details

**Possible headline(s):** 
What the Fed heard about the economy

**Data set(s):** 
Building an own data set. Scraping Fed Beige Books. Doing sentiment analysis or clustering analysis.

**Code repository:** 

**Possible problems/fears/questions:** 
- no clear result from using the datasets
- problems in scraping the databases

## Work so far
- Did some work in my first project which did some very elementary sentiment analysis (positive, neutral, negative).

## Checklist

This checklist must be completed before you submit your draft.

- [X] I have already spent time with my data set, opening it, exploring it, etc
- [ ] I have created a "DIARY.md" file to save links and list all of the terrible, no good problems I come across
- [X] My issue issue has `[Project]` in the title
- [ ] My issue links to my data set(s)
- [ ] My issue links to my code repository
- [X] My issue explains what I'd like to explore in the data set
- [X] My issue includes images - either inspiration or what I've done so far
- [ ] I have received two comments of peer feedback on my pitch issue

**Comment by qdinhbui2** [comment]
What you've built is already fun. I think this is a good opportunity for small multiples. You don't want to hide the data. Toggling is hard work! The most interesting thing is the differences in Federal Reserve Districts so I wouldn't even bother with the National level of data. 

While not the most necessary thing: a good accompanying table would be the most important phrases for each variable according to each macro topic. For instance each row would be a district, each column a macro topic and each cell would be a small list of phrases that stood out or really drove the attitude.

**Comment by wonderfulexperience** [comment]
# Update
	
## Content
	I ported my work until now from Leaflet on D3.js. 
https://wonderfulexperience.github.io/fed-sentiment/

The code repository is here:
https://github.com/wonderfulexperience/data-studio-projects/tree/master/code/Project-4

<img width="883" alt="bildschirmfoto 2017-08-14 um 09 46 26" src="https://user-images.githubusercontent.com/28814374/29274325-79e06858-80d5-11e7-90c9-d736b3645283.png">

## Any changes in direction or topic?
I will work on the table to give more insights into what is the sentiment for each district / sector.
	
## Problems/Questions
Too much data. Still not 100% happy with the sentiment analysis. And it's much 	

## Checklist
	
- [X] I have included my visuals
- [X ] I have added writing about my topic
- [X] I have been updating my DIARY.md with details about my process
- [X] I have uploaded/updated any Jupyter Notebooks or other datasets into my code repository
- [ ] I have received two comments of peer feedback on my project update
