### ISSUE TITLE
Deadly traffic accidents in Switzerland [Project]

### ISSUE THREAD

**Issue by peterjost** [jsoma/data-studio-projects#86]
# Pitch

## Summary

The number of traffic fatalities in Switzerland has been decreasing for years. But still: Are some days more dangerous than others? At what time do we count the highest number of deadly accidents? Are there some changes over the years?

## Details

**Possible headline(s):** 
Please drive carefully on friday afternoon

**Data set(s):** 
http://www.bfu.ch/de/Documents/04_Forschung_und_Statistik/02_Statistik/2016/Zeitreihen/Excel/USV.WT.05_d.xlsx
http://www.bfu.ch/de/Documents/04_Forschung_und_Statistik/02_Statistik/2016/Zeitreihen/Excel/USV.WT.08_d.xlsx

**Code repository:** 
https://github.com/peterjost/studio-projects

**Possible problems/fears/questions:** 
Do I really find some patterns in the data?

## Work so far

![image](https://user-images.githubusercontent.com/28814371/29045048-0d70a61e-7b90-11e7-8f70-f6f8141b5008.png)

![image](https://user-images.githubusercontent.com/28814371/29045139-6e40dfa4-7b90-11e7-9ac0-59d9ba58e00e.png)

![image](https://user-images.githubusercontent.com/28814371/29045085-333c3660-7b90-11e7-8337-3845c2aebd7b.png)

Explored the data, made some first visualizations. Surprise: Most deadly accidents in the afternoon, not during the night.
## Checklist

This checklist must be completed before you submit your draft.

- [x] I have already spent time with my data set, opening it, exploring it, etc
- [x] I have created a "DIARY.md" file to save links and list all of the terrible, no good problems I come across
- [x] My issue issue has `[Project]` in the title
- [x] My issue links to my data set(s)
- [x] My issue links to my code repository
- [x] My issue explains what I'd like to explore in the data set
- [x] My issue includes images - either inspiration or what I've done so far
- [ ] I have received two comments of peer feedback on my pitch issue

**Comment by chrgavalas** [comment]
Peter! Car accidents are going down in Switzerland? This sounds logical for such an organized country, but if you can show that a significant amount of accident happens during a specific time of day/week and explain why this happens, it'd be newsworthy!

**Comment by wonderfulexperience** [comment]
This is for sure interesting. Is it possible to correlate it with the overall traffic on roads? The number of accidents at night might be much lower because traffic is much lighter.
