### ISSUE TITLE
Comparing congressmen speeches in Dilma Rousseff's impeachment trial and Michel Temer's corruption charges votes [Project]

### ISSUE THREAD

**Issue by RodrigoMenegat** [jsoma/data-studio-projects#88]
# Pitch
I was working in my previous pitch about [secret payments](https://github.com/jsoma/data-studio-projects/issues/63) but there was no story there. This is my new #3 pitch!

## Summary
In 2016 and 2017, two brazilian presidents have faced the threat of being outed from office. Last year, Dilma Rousseff was impeached after losing a vote in both the higher and upper Houses of Brazilian Congress. Last week, the current president Michel Temer won his battle for survival when the lower house saved him from being persecuted in corruption charges.
 
In both cases, congressmen used the opportunity to appear into national television. Therefore, we saw some memorable (for all the good and bad reasons imaginable) speeches. But how do they compare, statiscally?

## Details
I want to do text analysis and discover some differences between the speeches. I am using the Portuguese version of the LIWC Dictionary to measure sentiments and doing some word counting.
**Possible headline(s):** 

**Data set(s):** 
- [Brazilian House of Representatives, department of transcriptions](http://www2.camara.leg.br/atividade-legislativa/plenario/discursos/notas.html)
- [Jornalistas Livres spreadsheet](https://www.facebook.com/jornalistaslivres/posts/361114270679123), [made by Patrícia Cornils](https://docs.google.com/spreadsheets/d/1rTFC9kbPqeHWrr2JalcvehgRXdAu03BwyBTgTL6oFC8/edit#gid=177016461)
- [Portuguese LIWC Dictionary](http://143.107.183.175:21380/portlex/index.php/pt/projetos/liwc)

**Code repository:** [Here!](https://github.com/RodrigoMenegat/studio-projects/tree/master/code/speeches-congress)
	
**Possible problems/fears/questions:** The two votes were similar in substance: representatives were deciding if the president should or should not be investigated for presumed crimes. Nevertheless, we are looking at different juridical/political proccesses: Dilma's vote was an impeachment trial, judging political crimes, and Temer's vote was about accusations that he commited a common crime. The House Speaker has also changed during this period, and some regimental rules are different for each case. I need to take this into account.

## Work so far
**What I already know?** Temer defenders made shorter and less agressive speeches than Dilma's defenders. The left-wing parties were the more aggresive and vocal in both cases.

**A graph:**
![violin](https://user-images.githubusercontent.com/28814352/29048899-0f2170a4-7ba1-11e7-9e43-7f1a629679c1.jpg)

## Checklist

This checklist must be completed before you submit your draft.

- [x] I have already spent time with my data set, opening it, exploring it, etc
- [x] I have created a "DIARY.md" file to save links and list all of the terrible, no good problems I come across
- [x] My issue issue has `[Project]` in the title
- [x] My issue links to my data set(s)
- [x] My issue links to my code repository
- [x] My issue explains what I'd like to explore in the data set
- [x] My issue includes images - either inspiration or what I've done so far
- [x] I have received two comments of peer feedback on my pitch issue

**Comment by simon-pinkmartini** [comment]
Sounds like a worthy analysis! Maybe you could compile a list of very rude words and check who used them more often (as an indication for the style of the parties)? Perhaps some analysis on the level of sentences and words could also be useful to see which side makes the more complex arguments and which speeches are more simplistic?

**Comment by RodrigoMenegat** [comment]
# Update
Pheeew! That was some hardwork, but now I have a lead and what I think is a cool hero graphic.

## Content
![party_case_sized](https://user-images.githubusercontent.com/28814352/29107481-707eb0ca-7ca8-11e7-9d92-5b491de9d955.png)

	
## Any changes in direction or topic?
I found a lead and will build my story/viz around it:

*Even if they ended up winning the vote and kept the president in office for now, Michel Temer's allies seem to have ran away from the spotlight. Their speeches were shorter and less virulent than those made by the opposition.*

*This behavior is completely different than the one displayed by the representatives that defended Dilma Rousseff during her impeachment vote: they spoke for longer and in a more beligerant tone.*

## Problems/Questions
*TO DO*:
- Put the length violin plot (see [first comment](https://github.com/jsoma/data-studio-projects/issues/88#issue-248556321)) into the chart.
- Edit and bulletproof the annotations
- Write a small text
- Better typohrapgy in chart's labels and titles

**SHOULD I?**
- Think about a way to visualize the share of chairs that each party has - now the marker size is displaying the percentage of each vote inside a given party.

## Checklist
	
- [x] I have included my visuals
- [x] I have added writing about my topic
- [x] I have been updating my DIARY.md with details about my process
- [x] I have uploaded/updated any Jupyter Notebooks or other datasets into my code repository
- [ ] I have received two comments of peer feedback on my project update

**Comment by edl2118** [comment]
Rodrigo, your graphic is really beautiful and informative! I especially like how you have categorized the speeches into the different houses of congress and further into defenders and opponents. One thing that I was a little confused by in the beginning was keeping all of the visual cues in mind. You had a lot going with the colors, the size of the circles, the houses on the y axis,  and the average of angry words on the x axis. Just a personal preference but maybe you can move the x axis label (0-5) to the top? I had to scroll down to understand what the position of the circles meant. At first I thought the colors signified the anger in the speeches and the position of the bubble was the number of words used. But then after reading the legend, I realized what the colors and positions actually mean. Maybe I don't really understand the context enough, but I was wondering what the value is in comparing their two speeches? It's such a beautiful graphic though and as you say maybe with a bit more writing on your topic and it'll be perfect.

**Comment by RodrigoMenegat** [comment]
# Final
## Project visuals/text
### In the vote about corruption charges, Temer supporters avoided the spotlight
*Comparatively, allies of Dilma Rousseff spoke for longer and used more aggressive vocabulary when defending her against the impeachment*

##### RODRIGO MENEGAT

*“I vote yes”*. Those brief, concise words were spoken hundreds of times at the Câmara dos Deputados – the lower house of Brazilian Congress – in the evening of August 2. By voting “yes” to a special commission report that said Mr. Michel Temer was innocent, 263 of the 513 representatives decided to stop the corruption charges against the current President. If he had lost, the Supreme Federal Court could order an official investigation and remove him from office.

Temer’s allies won by a wide margin. For the investigation to continue, the opposition needed to gather 342 votes, but only reached 227. Despite being the undisputable majority, though, they seem to have ran away from the spotlight. The speeches they delivered when voting were shorter and less virulent than those of the the opposition. This behavior is completely different than the one displayed by the representatives that defended Dilma Rousseff during her impeachment vote, in 2016: even being far outnumbered, her supporters spoke for longer and in a more belligerent tone.

A quantitative analysis of the words used by congressmen in both occasions shows precisely that. Most of the representatives who sided with Temer used around 50 characters in their pronouncements. This is barely sufficient to say, in Portuguese, “I vote yes with the report, Mr. President”. Not only Dilma’s defenders spoke considerably more, but they also used a bigger percentage of words that express anger. 

Possibly, Temer supporters were trying to avoid a strong association with the president that has the lowest popularity ratings in Brazilian politics since the direct elections were reestablished in the country, in 1992. Dilma's ratings were also low in 2016, but some sectors of Brazilian society gave her vocal support until the very end. The perspective of seeing their president deposed in what they considered a "soft coup" may have sparked rage among those who sided with her.

But, after all, what is considered an angry word? Those calculations were made using a dictionary that puts words in 64 different categories, translated from english by researchers of the [Interinstitutional Center for Computational Linguistics]( http://www.nilc.icmc.usp.br/nilc/index.php/) from the University of São Paulo (USP). “Anger” is one of those bins.

Results should be taken with a grain of salt: since we are evaluating standalone words, the measure will overlook more complex usages of language such as irony, contempt or hidden threats.

![party_case_small](https://user-images.githubusercontent.com/28814352/29222653-66478588-7e91-11e7-8d4c-1c21b92972f5.png)

![violin-length](https://user-images.githubusercontent.com/28814352/29222652-662fc4fc-7e91-11e7-86a5-e8c3b1812f50.png)

## Details

**Headline:** In the vote about corruption charges, Temer supporters avoided the spotlight

**Published website version:** [Here!](http://rodrigomenegat.github.io/studio-projects/sentiment-votes)

**Code repository:** [Here!](https://github.com/RodrigoMenegat/studio-projects/tree/master/code/speeches-congress)

**Final data set(s):** See [repository](https://github.com/RodrigoMenegat/studio-projects/tree/master/code/speeches-congress)

## What did you find to be the most difficult part of this project?
Coming up with the visuals. I ended up making the bubble changes by size because I wasn't able to make them change by color. Also, I had to manually scale them on Illustrator, as well! I also found it hard to present the story for a non-Brazilian audience. If you're familiar with Brazilian politics, less explaining needs to be done and the overall trend is more evident.

## Are you satisfied with what you produced? Is there anything you would like to change or improve?
Yes. I think the main chart is complex, yes, but **if** the reader take the time to actually read it, it shows some nice insights. I am not sure of how many people would do that, though. I probably cound find a way of presenting the story in a simpler way to a wider audience.

## Checklist

- [x] I have included my visuals
- [x] I have posted my project to my project website
- [x] I have been updating my DIARY.md with details about my process
- [x] I have uploaded/updated any Jupyter Notebooks or other datasets into my code repository
