### ISSUE TITLE
Visualizing the use of magic in Harry Potter books [Project]

### ISSUE THREAD

**Issue by RodrigoMenegat** [jsoma/data-studio-projects#89]
# Pitch
I think I deserve a break from Brazilian politics. Pitch #4 is about Harry Potter, yay!

## Summary
Using a text file for each one of the seven books in the original series and a list of all the known spells in the Wizarding Word, I wanna discover which spells are more common throughout the series. 

## Details
Since wizards cast spells by basically saying the incantation words, I can easily find out when each spell was used. Ok, people could be TALKING about the spell as well (e.g "Harry, this spell is called Avada Kedavra...), and thus would mention the same words... But I think we can live with that!

What I already know: the series got more magical in the latter books. The Unforgivable Curses also got more popular in the last few installments - basically when everybody started to die. Accio, the spell of the lazy wizard (basically, it brings an object to the hand of the caster) also became HUGE near the end.

**Possible headline(s):** Wands don't kill people. Wizards do. 

**Data set(s):** See [repository](https://github.com/RodrigoMenegat/studio-projects/tree/master/code/harry-potter-spells)

**Code repository:** [Here](https://github.com/RodrigoMenegat/studio-projects/tree/master/code/harry-potter-spells)
	
**Possible problems/fears/questions:** This is kind of silly and has a questionable methodology - counting the ammount of times incantantion words are said is the same as measuring spell usage?

## Work so far
![magic-usage](https://user-images.githubusercontent.com/28814352/29049921-bd28f58c-7ba6-11e7-8f52-7c42f119341a.png)

## Checklist

This checklist must be completed before you submit your draft.

- [x] I have already spent time with my data set, opening it, exploring it, etc
- [x] I have created a "DIARY.md" file to save links and list all of the terrible, no good problems I come across
- [x] My issue issue has `[Project]` in the title
- [x] My issue links to my data set(s)
- [x] My issue links to my code repository
- [x] My issue explains what I'd like to explore in the data set
- [x] My issue includes images - either inspiration or what I've done so far
- [x] I have received two comments of peer feedback on my pitch issue

**Comment by RodrigoMenegat** [comment]
# Update
	
## Content
I have the data for every spell used/incantation words said, both as a percentage of total and as an absolute number. I wanna do something that is ENTIRELY visual now, not relying in a supporting story, so I am planning my visualization beforehand. Here is the template:


![template](https://user-images.githubusercontent.com/28814352/29232861-e961bed2-7ebb-11e7-8248-c2a07741ae13.png)

Story-wise, I'll go for something like "as the story progressed, characters relied more on magic". Nothing really exciting, but kind of appealing to the Harry Potter fan - and there are load of them. *He that never wrote a silly story among you, let him first cast a stone!*
	
## Any changes in direction or topic?
Not so far.
	
## Problems/Questions
For this to be minimally appealing, I'll have to put in some eye-candy. My design/Illustrator skills are not that good, though, and it mind end up looking awful. I wanna get better at this, anyway.
	
## Checklist
	
- [x] I have included my visuals
- [x] I have added writing about my topic
- [x] I have been updating my DIARY.md with details about my process
- [x] I have uploaded/updated any Jupyter Notebooks or other datasets into my code repository
- [ ] I have received two comments of peer feedback on my project update

**Comment by demetriospogkas** [comment]
As a die-hard fan, I'm looking forward to the final outcome!!!!!

**Comment by RodrigoMenegat** [comment]
# Final

## Project visuals/text
![template](https://user-images.githubusercontent.com/28814352/29572691-09973b6a-872b-11e7-9ae1-e1b66758d41c.png)

## Details

**Headline:**  How has the 

**Published website version:** Coming soon!

**Code repository:** [Here!](https://github.com/RodrigoMenegat/studio-projects/tree/master/code/harry-potter-spells)

**Final data set(s):** See repository

## What did you find to be the most difficult part of this project?
Making things look kind of nice in Illustrator.

## Are you satisfied with what you produced? Is there anything you would like to change or improve?
Not really. I think the story is superficial, and I could have done more interesting stuff with the data - find a way to break it down by chapter, for instance. Nevertheless, I did this mostly as an Adobe Illustrator exercise, in order to get better with the tool.

## Checklist

- [x] I have included my visuals
- [x] I have posted my project to my project website
- [x] I have been updating my DIARY.md with details about my process
- [x] I have uploaded/updated any Jupyter Notebooks or other datasets into my code repository
