### ISSUE TITLE
Who are the happy people? [Project]

### ISSUE THREAD

**Issue by wonderfulexperience** [jsoma/data-studio-projects#9]
# Pitch
Some people are very happy. Let's have a look who these people are.

## Summary
I want to explore what makes people happy. I am using survey results for Europe to compare individual characteristics of these people. 

## Details
The European Social Survey (ESS) asked people all over Europe how happy they are. The survey also provides country, personal values, family situation, and income data for these people. So who are the happiest people? Where do they live? Are they religious? Are the rich? And how old are they?

Inspiration: Bangladesh is surprisingly one of the happiest countries
<img width="613" alt="bildschirmfoto 2017-07-17 um 10 37 57" src="https://user-images.githubusercontent.com/28814374/28273319-0e867b1a-6adc-11e7-809e-eaac3d7f0671.png">

**Possible headline(s):**
- "Hey, why are you happy?"
- "People are not happy for the reason you think"

**Data set(s):** 
European Social Survey (2014)
http://www.europeansocialsurvey.org/data/round-index.html

**Code repository:** 
https://github.com/wonderfulexperience/data-studio-projects/tree/master/code/Project_1
	
**Possible problems/fears/questions:** 
- Too much data, too many variables to compare the happiness indicator

## Work so far
- Looking at some data and variables

## Checklist

This checklist must be completed before you submit your draft.

- [X] I have already spent time with my data set, opening it, exploring it, etc
- [x] I have created a "DIARY.md" file to save links and list all of the terrible, no good problems I come across
- [X] My issue issue has `[Project]` in the title
- [X] My issue links to my data set(s)
- [X] My issue links to my code repository
- [X] My issue explains what I'd like to explore in the data set
- [x] My issue includes images - either inspiration or what I've done so far
- [x] I have received two comments of peer feedback on my pitch issue

**Comment by maijaliisa** [comment]
How cool! Would love to see how individuals in different countries qualify their happiness. If you can narrow down to a few specific variables that might help you get through the dataset more efficiently

**Comment by deniseajiri83** [comment]
I think it'd be great if you could find some trends (e.g. in this region people seem to be happier, people with this social/economic status tend to be happier,...) . I guess it'd be easier if you focus only on a limited number of variables.

**Comment by SYChJung** [comment]
This will be really helpful. We can make someone happy, if we know what makes people happy in the country he or she is from.

**Comment by wonderfulexperience** [comment]
# Update
I wanted to go crazy a bit. With interactive charts and an innovative way to build a website. I also wanted to involve the user by comparing him to the dataset.

I used for the first time D3.js and JavaScript. The result was a lot of time spend learning new stuff on D3, JQuery and CSS. But it was worth it.

I have a draft website now. Please visit it:
https://wonderfulexperience.github.io/happiness/index.html

## Content
The European Social Survey has asked more than 40'000 Europeans how happy they feel. First, I aggregated the data to compare "very happy" to "not very happy" people. I compare them by different categories (e.g. income, age, partner).

Then I wanted to do some interactive chart on a website. But I thought the individual data would be too big. So I used five categories (age, income, religiousness, health, number of friends) to group the data and run averages on each permutation of these categories. I exported this aggregated data (more than 2000 lines) to a CSV and imported it by D3.

On the website, people can enter their personal situation and see how the distribution of happiness changes according to the data they enter.

A map slider to compare country and regional happiness levels:
<img width="50%" height="50%" alt="bildschirmfoto 2017-07-20 um 13 29 56" src="https://user-images.githubusercontent.com/28814374/28431652-0e0fba4c-6d53-11e7-8b36-db0d3ecdf635.png">

Divided in different tabs, I provide more aggregated data:
<img width="50%" height="50%" alt="bildschirmfoto 2017-07-20 um 13 30 23" src="https://user-images.githubusercontent.com/28814374/28431659-1394b6e8-6d53-11e7-9992-1a37bf6af2fa.png">

Comparing your own situation to the survey results:
<img width="50%" height="50%" alt="bildschirmfoto 2017-07-20 um 13 30 13" src="https://user-images.githubusercontent.com/28814374/28431655-0fde9f78-6d53-11e7-9da3-726ef97684cd.png">

Drilling down on the data, until you find your exact comparison group:
<img width="50%" height="50%" alt="bildschirmfoto 2017-07-20 um 13 45 19" src="https://user-images.githubusercontent.com/28814374/28431662-155d2eec-6d53-11e7-95eb-c5f30035904e.png">


## Any changes in direction or topic?
Instead of working on aggregating data, I use an interactive part to let users explore the date in more detail.

## Problems/Questions
- I didn't do too much analysis on all relevant criteria for happiness as I focused more on the technical implementation.
- The charts to show on the interactive part on the website is a bit complicated. I hope I can make it more intuitive. Does anybody understands it?
	
## Checklist
	
- [x] I have included my visuals
- [x] I have added writing about my topic
- [x] I have been updating my DIARY.md with details about my process
- [x] I have uploaded/updated any Jupyter Notebooks or other datasets into my code repository
- [x] I have received two comments of peer feedback on my project update

**Comment by SYChJung** [comment]
The graphs show clearly which countries have happier people, and which countries don't. The display is really neat.

**Comment by deniseajiri83** [comment]
I really like the fact that the reader can engage with the data by customizing it. It's very interactive and keeps the reader interested in the topic. Great work!

**Comment by wonderfulexperience** [comment]
# Final

## Project visuals/text
The European Social Survey has asked more than 40'000 Europeans how happy they feel. First, I aggregated the data to compare "very happy" to "not very happy" people. I compare them by different categories (e.g. income, age, partner).

I found aggregated data informative, but not very engaging. Therefore I added an interactive chart on a website. As the individual data would be too big, I used five categories (age, income, religiousness, health, number of friends) to group the data and run averages on each permutation of these categories. I exported this aggregated data (more than 2000 lines) to a CSV and imported it by D3.

On the website, people can enter their personal situation and see how the distribution of happiness changes according to the data they enter.

A map slider to compare country and regional happiness levels:
<img width="412" alt="28431652-0e0fba4c-6d53-11e7-8b36-db0d3ecdf635" src="https://user-images.githubusercontent.com/28814374/28644910-6e9a0928-7229-11e7-993e-a08f0280514a.png">

Divided in different tabs, I provide more aggregated data:
<img width="547" alt="28431659-1394b6e8-6d53-11e7-9992-1a37bf6af2fa" src="https://user-images.githubusercontent.com/28814374/28644907-6c906f3c-7229-11e7-9eb7-75133265a63b.png">

Comparing your own situation to the survey results:
<img width="582" alt="28431655-0fde9f78-6d53-11e7-9da3-726ef97684cd" src="https://user-images.githubusercontent.com/28814374/28644919-75d1cfe6-7229-11e7-8d23-740480a56dba.png">

Drilling down on the data, until you find your exact comparison group:
<img width="548" alt="28431662-155d2eec-6d53-11e7-95eb-c5f30035904e" src="https://user-images.githubusercontent.com/28814374/28644924-7b98986a-7229-11e7-908d-b1a1f599658d.png">

## Details

**Headline:** 
"Who are the happy people?"

**Published website version:**
https://wonderfulexperience.github.io/happiness/index.html

**Code repository:**
https://github.com/wonderfulexperience/data-studio-projects/tree/master/code/Project_1

**Final data set(s):** 
European Social Survey Data (saved in the code repository)

## What did you find to be the most difficult part of this project?
Learning some unknown charting library (D3) and using a lot of JavaScript.

## Are you satisfied with what you produced? Is there anything you would like to change or improve?
Yes, I like it very much. Even if the result is not publishable in a newspaper, I learned a lot regarding D3.

## Checklist

- [X] I have included my visuals
- [X] I have posted my project to my project website
- [X] I have been updating my DIARY.md with details about my process
- [X] I have uploaded/updated any Jupyter Notebooks or other datasets into my code repository
