### ISSUE TITLE
NY Philharmonic [Project]

### ISSUE THREAD

**Issue by mathieulede** [jsoma/data-studio-projects#91]
# Pitch
What kind of evolution the NY Philharmonic and the music in general encountered after more than 150 years of performances. By looking at the repertoire and the choices made during these years, the apparition of performances, jazz, electronic music and dance becomes visible on a timeline.
Does the Philharmonic continue to play the classic pieces, what place for the contemporary pieces, etc.

## Summary
NY Philharmonic over time

## Details
The New York Philharmonic played its first concert on December 7, 1842. The Performance History database documents all its known concerts, amounting to more than 20,000 performances.

[Link to the database](https://www.kaggle.com/nyphil/perf-history)

**Possible headline(s):** 
* 

**Data set(s):** 
[Link to the database](https://www.kaggle.com/nyphil/perf-history)

**Code repository:** 
[Project 4](mathieulede.github.io/data-studio/ny_philharmonic)

**Possible problems/fears/questions:** 

## Checklist

This checklist must be completed before you submit your draft.

- [x] I have already spent time with my data set, opening it, exploring it, etc
- [x] I have created a "DIARY.md" file to save links and list all of the terrible, no good problems I come across
- [x] My issue issue has `[Project]` in the title
- [x] My issue links to my data set(s)
- [x] My issue links to my code repository
- [x] My issue explains what I'd like to explore in the data set
- [ ] My issue includes images - either inspiration or what I've done so far
- [ ] I have received two comments of peer feedback on my pitch issue

**Comment by qdinhbui2** [comment]
Without knowing much about the data. I think streamgraphs would be fun. You can group by different composers or genres. 

https://bl.ocks.org/mbostock/4060954

http://www.nytimes.com/interactive/2008/02/23/movies/20080223_REVENUE_GRAPHIC.html

**Comment by mathieulede** [comment]
Cool! Just tried to make this streamgraph with D3 and here is the result (10 most popular composers)

![screen shot 2017-08-10 at 3 31 48 pm](https://user-images.githubusercontent.com/28827574/29198863-aa0fbc94-7e15-11e7-81e1-a105e87488f9.png)

**Comment by qdinhbui2** [comment]
Very good. Is there a way you can smooth the data so its less noisey? Start in 1920. Include a legend! I want to see the patterns!

**Comment by qdinhbui2** [comment]
Can you do all the composers? Or maybe group by composer nationality?

**Comment by mathieulede** [comment]
https://mathieulede.github.io/data-studio/ny_philharmonic/

![output-1](https://user-images.githubusercontent.com/28827574/29473338-74bed8d4-8425-11e7-988b-ff324362f240.jpg)

![output-2](https://user-images.githubusercontent.com/28827574/29473278-2a159dcc-8425-11e7-88b7-f2e9099b87c7.jpg)

![output-3](https://user-images.githubusercontent.com/28827574/29473281-2b6ea3e4-8425-11e7-8f37-769cba31d870.jpg)
