### ISSUE TITLE
How To Craft The Perfect August-Speech [Project]

### ISSUE THREAD

**Issue by simon-pinkmartini** [jsoma/data-studio-projects#92]
# Update

## Summary
The project took a different turn (for now) - it's become a bit artsy, if not to say impressionistic. My new output is an animated visualization of the speeches.

## Details
As I started looking into d3, I came across this code block here by Mike Bostock:
https://bl.ocks.org/mbostock/3808234
It shows how single letters get updated and removed from a text string. I wanted to see how far I can get adapting this idea to whole words: select a couple of important words from a speech in year x, and see which ones get replaced in year x + 1. Over time, the exercise took its own dynamics and morphed into something... well, just see.

## Image
<img width="780" alt="screen shot 2017-08-17 at 00 28 14" src="https://user-images.githubusercontent.com/28814395/29396127-e66b0202-82e3-11e7-8669-1eaaba2ab780.png">

## Live Example
Version 1: http://165.227.144.49/Augustansprachen/web/wordanimation%201.html
Version 2: http://165.227.144.49/Augustansprachen/web/wordanimation%202.html
Version 3: http://165.227.144.49/Augustansprachen/web/wordanimation%203b.html
Version 4: http://165.227.144.49/Augustansprachen/web/wordanimation%204.html
Version 5: http://165.227.144.49/Augustansprachen/web/wordanimation.html

## What the hell is this?!
* As of version 5, I am using a Tfidf vectorizer to pick a number of important words from a speech. I am using the speeches from 2000-2017. I use stop_words to filter out meaningless fill-words and also min_df to eliminate all the words that are only mentioned in a fraction of the speeches. This way, I end up with about 40 words per speech, which are at once a reflection of dominant themes over the whole body of speeches and secondly show the focus of what each individual speech was about. I generate a wordlist by multiplying the tfidf-number with some arbitrary integer and rounding the result (which gives me a "fake" count vectorizer - in earlier versions I used a real count vectorizer, maybe I will go back). I export the wordlist for each speech and add info on the speaker.
* The animation first takes the wordlist and shuffles it for each year. Some words occur multiple times, other words only once. Then, it creates a steady "rain" of these words, taking as inputs the series of speeches starting in 2000. Words with a high frequency ("important words") are made bigger. Whenever a word is in the pipeline that is already in the image, there is no new raindrop, but instead the existing word gets re-elevated up in the sky. The words are colored according to the political party of the speaker. As a new speaker from a different party picks up an existing word, the color of this word changes and so does its size, depending of the importance of this particular word in the new speech.

## Problems / Questions
* I am not sure if this animation has any value besides being nice to look at
* Moving the words around in the image without creating a mess is quite tricky
* TODO: Title and text etc

# Pitch
How To Craft The Perfect August-Speech - a guideline for actual and wannabe-presidents

## Summary
The 1st of August is Switzerland's national celebration day (equivalent of the 4th of July in the US). On this day, all the seven members of the Bundesrat (the executive branch of government) swarm out into the country to give speeches. A set of 100-200 speeches is available on the Swiss government's website, going back over the last decades. Based on this sample and on a data analysis of it, I will come up with a guideline on how to craft the "perfect" August-speech. 

## Details
The guide will include things like length and other linguistic features. It will talk about topics to cover, depending on what party you belong to. Each point is accompanied by a small chart or table giving an overview of the available examples. It will also include some hints on what you have to do to be "special" (like: don't start your speech with "dear co-citizens" but with some other sentence). This is a way to show the outliers in the sample. The guide is to be taken with a pinch of salt. It's meant to be educative and funny at the same time. It should show how similar (and thus predictable) many speeches are, but also give some credit to politicians who didn't follow the typical pattern.

**Possible headline(s):** 
How To Craft The Perfect August-Speech

**Data set(s):** 
https://www.admin.ch/gov/de/start/dokumentation/reden/ansprachen-zum-nationalfeiertag.html
and
https://www.admin.ch/gov/de/start/dokumentation/reden/reden-der-bundesraete.html

**Code repository:** 
https://github.com/simon-pinkmartini/studio-projects/tree/master/code/Augustansprachen
	
**Possible problems/fears/questions:** 
The humourous aspect is very important in this story. I need to come up with enough "funny" point in the data analysis.

## Work so far
- I manually downloaded about 50 speech texts and created an excel with the texts and some meta-information. Automating the process is tricky because the webpages are all differently structured.
- I applied some text analysis techniques that we learned over the last days, like sentiment analysis and clustering (using scikit-learn). This worked out fine, even if the results are not spectacular.

## Images
Here are some (poorly annotated) screenshots that illustrate the mostly exploratory work I did so far:
**Some word clustering by politicians of different parties**
![index](https://user-images.githubusercontent.com/28814395/29083125-aa421c5c-7c35-11e7-87a6-114831e83fbb.png)
**A measure of conventionality by parties**
![index2](https://user-images.githubusercontent.com/28814395/29083179-cd609e98-7c35-11e7-8313-5b77ee04c2e5.png)
**Positivity (blue) vs negativity (red) over time**
![index3](https://user-images.githubusercontent.com/28814395/29083228-faa9a80e-7c35-11e7-9c36-2e244bfa4622.png)

## Checklist

This checklist must be completed before you submit your draft.

- [x] I have already spent time with my data set, opening it, exploring it, etc
- [x] I have created a "DIARY.md" file to save links and list all of the terrible, no good problems I come across
- [x] My issue issue has `[Project]` in the title
- [x] My issue links to my data set(s)
- [x] My issue links to my code repository
- [x] My issue explains what I'd like to explore in the data set
- [x] My issue includes images - either inspiration or what I've done so far
- [x] I have received two comments of peer feedback on my pitch issue

**Comment by cathrinesot** [comment]
It' s a very interesting idea, that will both inform and entertain! The visualization should be also kind of funny! Maybe you can include a video or two of the most common speech - tricks !

**Comment by IoannisAntypas** [comment]
I think its a great idea, go for it! Maybe you could also create some politician classification, based on how joyous or angry their speeches are.

**Comment by wonderfulexperience** [comment]
I am interested in the phrases politicians use. Maybe the left party tries to invoke solidarity, while the conservative parties try to appellate to the national feelings?
