### ISSUE TITLE
Sentiment analysis on the Eurogroup [Project]

### ISSUE THREAD

**Issue by IoannisAntypas** [jsoma/data-studio-projects#93]
Please complete all of the following sections, or a robot will spookily dance around your issue! A completed version of this template can be found at https://github.com/jsoma/data-studio-projects/issues/1

# Pitch

## Summary

We will examine the sentiments of two key EU figures, Jeroen Dijsselbloem (Dutch finance minister and President of the Eurogroup) and Pierre Moscovici (French, Commissioner for Economic and Financial Affairs, Taxation and Customs), in his post Eurogroup press conferences regarding Greece, and figure out their sentiments when speaking about Greece, and what they can tell us about the manner of speech of top EU bureaucrats.

## Details

Once a month, or when things are really bad, multiple times per month (or multiple times per week, [it has happened]), the EU finance ministers whose countries have adopted the Euro currency, gather up and form the notorious Eurogroup, an informal council of ministers, where some of the most important decisions for the economy of Europe are taken. 

Greece has been experiencing a seemingly unending economic crisis the past 7 years, often being at the center of the Eurogroup discussions. In fact, the Dutch finance minister Jeroen Dijsselbloem who was selected by the other Euro-area finance ministers to be the President of the Eurogroup, placed Greece in the agenda of every meeting for the entire year preemptively.

**Possible headline(s):** 

Just how sentimental does the Eurogroup get about Greece/ Moscovici and Dijsselbloem, two sentimental figures when it comes to Greece

**Data set(s):** 

We will get the speeches at the eurogroup website, http://www.consilium.europa.eu/en/meetings/eurogroup/2016/06/16/ and the greek related statements of the Commissioner at https://ec.europa.eu/commission/commissioners/announcements/38_en

![screen shot 2017-08-06 at 10 40 47 pm](https://user-images.githubusercontent.com/28814422/29089559-a5d957e2-7c4a-11e7-9e43-98007be6a3a4.png)

**Code repository:** 
	
**Possible problems/fears/questions:** 

## Work so far

Work in progress

Ive analysed two Dijsselbloem speeches. They showed a lot of anticipation and joy

![screen shot 2017-08-07 at 2 51 22 pm](https://user-images.githubusercontent.com/28814422/29089603-c2c0f9b4-7c4a-11e7-8f1a-eab9a558349e.png)

## Checklist

This checklist must be completed before you submit your draft.

- [x ] I have already spent time with my data set, opening it, exploring it, etc
- [ x] I have created a "DIARY.md" file to save links and list all of the terrible, no good problems I come across
- [ x] My issue issue has `[Project]` in the title
- [ x] My issue links to my data set(s)
- [ ] My issue links to my code repository
- [ x] My issue explains what I'd like to explore in the data set
- [ x] My issue includes images - either inspiration or what I've done so far
- [ ] I have received two comments of peer feedback on my pitch issue

**Comment by simon-pinkmartini** [comment]
Joy! What an interesting result from the side of Dijsselbloem. I am actually not sure if we can use sentiment analysis here to compare emotions against each other (eg joy vs anger). But maybe if you check each of the emotions over time, you will see some changes (a heightened sense of anger during the high tide of the crisis)?

**Comment by wonderfulexperience** [comment]
There could be some bias as politician try to sound upbeat. Interesting would be to have also the speeches of German finance minister Schäuble analyzed. I would guess he would be much less joyful. If you have time, you could also analyze when different phrases were started to be used ("fiscal reforms", etc.)
