### ISSUE TITLE
Chop Suey: As American as Apple Pie? [Project]

### ISSUE THREAD

**Issue by edl2118** [jsoma/data-studio-projects#94]
Please complete all of the following sections, or a robot will spookily dance around your issue! A completed version of this template can be found at https://github.com/jsoma/data-studio-projects/issues/1

# Pitch

## Summary
Chop Suey is one of those items you don’t see very much of on Chinese menus these days. It’s gone out of style because for some it screams fake Chinese food. So when you do spot this dish nowadays, it’s most likely positioned at the bottom of a menu. This made me wonder how it got on the menu in the first place? What's the history behind Chop Suey? Reading through some academic research and immigration data, a story started to emerge about how the first wave of Chinese immigrants adapted to Chinese Exclusion policies in America by becoming restaurant owners and creating a new kind of Chinese Cuisine. To survive and be profitable, restaurants needed to appeal to the American palate. Americans took to Chop Suey and it was featured pretty prominently in most Chinese menus. 

My main research question is whether we actually see a sharp rise in popularity for Chop Suey after 1915. This date is important because the modification made to the Chinese Exclusion Act at this time consequently led to an increase in the number of Chinese restaurants according to the academic research. I’m interested to see whether the rise and fall of Chop Suey in menus correlates with this period after the 1915 modification and the repeal of the Exclusion Act in the 1960s. 

## Details

**Possible headline(s):** 
Chop Suey: As American as Apple Pie? 
Chop Suey: when immigration policies impact a food trend

**Data set(s):** 
http://nypl.github.io/menus-api/
https://www.dhs.gov/xlibrary/assets/statistics/yearbook/2008/ois_yb_2008.pdf

**Code repository:** 
https://github.com/edl2118/studio-projects.git
	
**Possible problems/fears/questions:** 
While the NYPL’s menu database is very comprehensive, it’s still in the process of being transcribed so I’m concerned that my data is incomplete and I'm not really seeing any correlation in the frequency of "Chop Suey" and the years when the Exclusion Clause was in place. 

## Work so far
![immigration](https://user-images.githubusercontent.com/28814369/29094725-56cfb5c6-7c5c-11e7-83ee-640733e4fb22.png)

![correlation](https://user-images.githubusercontent.com/28814369/29097963-bf62953c-7c6a-11e7-8bd3-16d5d7da9e46.jpg)

## Checklist

This checklist must be completed before you submit your draft.

- [x] I have already spent time with my data set, opening it, exploring it, etc
- [x] I have created a "DIARY.md" file to save links and list all of the terrible, no good problems I come across
- [x] My issue issue has `[Project]` in the title
- [x] My issue links to my data set(s)
- [x] My issue links to my code repository
- [x] My issue explains what I'd like to explore in the data set
- [x] My issue includes images - either inspiration or what I've done so far
- [ ] I have received two comments of peer feedback on my pitch issue

**Comment by amandolinjames** [comment]
Love this topic! And that you got the dataset from the New York Public Library.

**Comment by edl2118** [comment]
# Update
	
## Content
	
## Any changes in direction or topic?
The holes in the data set are significant and are preventing me from making any reliable conclusions about the evolution of chop suey as a dish or as a set of ingredients over time. The issue is in the numbers of menus collected. Some years we actually don't have any menus collected/transcribed and others there is only one. Although historical research bears it out, it would be misleading to use this data to say anything about the changing importance of chop suey over time. 
	
## Problems/Questions
I should have checked the validity of the data set before starting and wasted too much time trying to make the data say something it didn't

![ingredients](https://user-images.githubusercontent.com/28814369/29480546-0d0a7564-8447-11e7-9fc5-041b205fbb21.jpg)

![dish_per_resto](https://user-images.githubusercontent.com/28814369/29480501-ba676628-8446-11e7-94d1-5c10657f7da9.jpg)
	
## Checklist
	
- [ ] I have included my visuals
- [ ] I have added writing about my topic
- [x] I have been updating my DIARY.md with details about my process
- [x] I have uploaded/updated any Jupyter Notebooks or other datasets into my code repository
- [ ] I have received two comments of peer feedback on my project update
